//! @brief Top-Level 16-bit Block Floating-Point FFT Processor.
//! This module integrates all sub-components of the FFT architecture:
//! the Address Generation Unit (AGU), Ping-Pong Dual-Port RAM, Twiddle Factor ROM,
//! Block Floating Point (BFP) Shifter, Butterfly Unit (BFU), and BFP Scanner.
//! It includes critical pipeline alignment registers to ensure that data fetched
//! from memory, scaled by the shifter, and twiddle factors fetched from ROM all
//! arrive at the computational Butterfly Unit on the exact same clock edge.
module fft_top #(
    //! Number of FFT points (Default: 1024).
    parameter N = 2048,

    //! Bit width of the data path and twiddle factors (Default: 16-bit Q1.15).
    parameter DATA_WIDTH = 16,

    //! Log base 2 of N, representing the number of address bits.
    parameter LOG2_N = 11
  )(
    //! System clock.
    input wire clk,

    //! Synchronous active-high reset.
    input wire rst,

    //! Master enable signal to begin FFT processing.
    input wire start_fft,

    //! The final global exponent after all stages are processed.
    output wire signed [7:0] final_exponent,

    //! Pulses high for exactly 1 cycle when the FFT has completely finished all processing and memory dumps.
    output wire fft_done
  );


  // AGU Signals
  wire [LOG2_N-1:0] rd_addr_a, rd_addr_b; //! Read addresses for RAM Port A and B
  wire [LOG2_N-1:0] wr_addr_a, wr_addr_b; //! Write addresses for RAM Port A and B
  wire [LOG2_N-2:0] twiddle_addr; //! Address for Twiddle ROM
  wire bank_sel_read, bank_sel_write, write_enable, new_stage; //! Control signals for RAM and AGU

  // RAM Output Signals (17-bit to ingest precision BFU results preserving sign logic during growth)
  wire signed [DATA_WIDTH:0] ram_out_a_re, ram_out_a_im; //! Read data from RAM Port A
  wire signed [DATA_WIDTH:0] ram_out_b_re, ram_out_b_im; //! Read data from RAM Port B

  // Twiddle ROM Output Signals
  wire signed [DATA_WIDTH-1:0] w_re, w_im; //! Twiddle factors from ROM

  // BFP Shifter Output Signals
  wire signed [DATA_WIDTH-1:0] shifted_a_re, shifted_a_im; //! Scaled data from BFP Shifter
  wire signed [DATA_WIDTH-1:0] shifted_b_re, shifted_b_im; //! Scaled data from BFP Shifter

  // Butterfly Unit Output Signals (17-bit to accommodate bit growth)
  wire signed [DATA_WIDTH:0] bfu_out_a_re, bfu_out_a_im; //! Output data from Butterfly Unit
  wire signed [DATA_WIDTH:0] bfu_out_b_re, bfu_out_b_im; //! Output data from Butterfly Unit

  // BFP Scanner Signals
  wire [3:0] block_shift_amount; //! Block shift amount from BFP Scanner
  wire early_stop; //! Early stop signal from BFP Scanner


  //! @brief Address Generation Unit (AGU).
  //! @details The "brain". It automatically aligns RAM and ROM fetches.
  AGU #(
        .N(N),
        .LOG2_N(LOG2_N),
        .RAM_LATENCY(1),
        .ROM_LATENCY(3),
        .BFU_LATENCY(6) // 1 (Shifter) + 5 (BFU: 4 mult + 1 add) = 6 cycles
      ) u_agu (
        .clk(clk),
        .rst(rst),
        .enable(start_fft),
        .rd_addr_a(rd_addr_a),
        .rd_addr_b(rd_addr_b),
        .twiddle_addr(twiddle_addr),
        .wr_addr_a(wr_addr_a),
        .wr_addr_b(wr_addr_b),
        .bank_sel_read(bank_sel_read),
        .bank_sel_write(bank_sel_write),
        .write_enable(write_enable),
        .new_stage(new_stage),
        .done(fft_done)
      );

  //! @brief Twiddle Factor ROM.
  //! @details 3-clock-cycle latency. Uses 1/8 cycle compression.
  twiddle_rom #(
                .N(N),
                .WIDTH(DATA_WIDTH)
              ) u_twiddle_rom (
                .clk(clk),
                .k(twiddle_addr),
                .w_re(w_re),
                .w_im(w_im)
              );

  //! @brief Dual-Port RAM.
  //! @details 1-clock-cycle read latency. Widened to (DATA_WIDTH + 1) to securely preserve BFU bit growths safely across stages.
  RAM #(
        .N(N),
        .LOG2_N(LOG2_N),
        .DATA_WIDTH(DATA_WIDTH + 1)
      ) u_ram (
        .clk(clk),
        .bank_sel_read(bank_sel_read),
        .bank_sel_write(bank_sel_write),
        .we(write_enable),
        .read_addr_a(rd_addr_a),
        .read_addr_b(rd_addr_b),
        .write_addr_a(wr_addr_a),
        .write_addr_b(wr_addr_b),
        .din_a_re(bfu_out_a_re),
        .din_a_im(bfu_out_a_im),
        .din_b_re(bfu_out_b_re),
        .din_b_im(bfu_out_b_im),
        .dout_a_re(ram_out_a_re),
        .dout_a_im(ram_out_a_im),
        .dout_b_re(ram_out_b_re),
        .dout_b_im(ram_out_b_im)
      );

  reg [3:0] latched_shift_amount; //! Latched shift amount from BFP Scanner
  reg signed [7:0] current_exponent; //! Current exponent from BFP Scanner


  reg [8:0] new_stage_delay_pipe; //! Delay pipeline for new stage signal
  //! @brief The 'new_stage' flag is generated by the AGU during the drain state.
  //! We need TWO different delay taps from this signal:
  //! @details   1) BFP Tracker: Must latch the scanner result BEFORE the first new-stage data
  //!      reaches the shifter (at new_stage + 5). Tap [3] gives delay of 4 cycles.
  //!   2) Scanner Reset: Must reset AFTER all old-stage writes finish draining
  //!      through the pipeline (at new_stage + TOTAL_WRITE_DELAY = new_stage + 9).
  //!      Tap [8] gives delay of 9 cycles.
  always @(posedge clk)
  begin : NEW_STAGE_DELAY
    if (rst)
      new_stage_delay_pipe <= 0;
    else
      new_stage_delay_pipe <= {new_stage_delay_pipe[7:0], new_stage};
  end

  wire bfp_latch_trigger  = new_stage_delay_pipe[2]; //! For tracker: latch shift before data arrives
  wire scanner_reset_trigger = new_stage_delay_pipe[8]; //! For scanner: reset after old writes drain

  //! @brief BFP Tracker.
  //! @details Updates the global exponent based on the block shift amount.
  always @(posedge clk)
  begin : BFP_TRACKER
    if (rst)
    begin
      latched_shift_amount <= 4'd1; // Neutral baseline shift
      current_exponent <= 8'sd0;
    end
    else if (bfp_latch_trigger)
    begin
      // Only trigger scaling adjustments at the exact transition point between macro stages
      latched_shift_amount <= block_shift_amount;

      case (block_shift_amount)
        4'd0:
          current_exponent <= current_exponent + 8'sd1;
        4'd1:
          current_exponent <= current_exponent;
        4'd2:
          current_exponent <= current_exponent - 8'sd1;
        4'd3:
          current_exponent <= current_exponent - 8'sd2;
        4'd4:
          current_exponent <= current_exponent - 8'sd3;
        4'd5:
          current_exponent <= current_exponent - 8'sd4;
        4'd6:
          current_exponent <= current_exponent - 8'sd5;
        4'd7:
          current_exponent <= current_exponent - 8'sd6;
        default:
          current_exponent <= current_exponent - 8'sd7;
      endcase
    end
  end

  //! @brief Block Floating Point Shifter.
  //! @details 1-clock-cycle latency. Scales the data dynamically based on the previous stage lock block_clz.
  bfp_shifter #(
                .INPUT_WIDTH(DATA_WIDTH + 1), 
                .OUTPUT_WIDTH(DATA_WIDTH)
              ) u_shifter (
                .clk(clk),
                .rst(rst),
                .a_in_re(ram_out_a_re),
                .a_in_im(ram_out_a_im),
                .b_in_re(ram_out_b_re),
                .b_in_im(ram_out_b_im),
                .block_clz(latched_shift_amount),
                .exp_in(8'sd0),
                .a_out_re(shifted_a_re),
                .a_out_im(shifted_a_im),
                .b_out_re(shifted_b_re),
                .b_out_im(shifted_b_im),
                .exp_out()
              );


  reg signed [DATA_WIDTH-1:0] w_re_aligned, w_im_aligned; //! Delayed twiddle factors

  //! @brief Pipeline Alignment Registers.
  //! The AGU natively aligns the raw RAM outputs and Twiddle outputs to the same cycle.
  //! Because the RAM data takes 1 additional cycle to pass through the BFP Shifter,
  //! we must delay the Twiddle factors by 1 cycle so they hit the BFU perfectly together.
  always @(posedge clk)
  begin : TWIDDLE_ALIGNMENT_DELAY
    w_re_aligned <= w_re;
    w_im_aligned <= w_im;
  end


  //! @brief Butterfly Arithmetic Unit.
  //! @details 5-clock-cycle latency. Outputs 17-bit data.
  butterfly_unit #(
                   .DATA_WIDTH(DATA_WIDTH),
                   .TWIDDLE_WIDTH(DATA_WIDTH)
                 ) u_bfu (
                   .clk(clk),
                   .a_re(shifted_a_re),
                   .a_im(shifted_a_im),
                   .b_re(shifted_b_re),
                   .b_im(shifted_b_im),
                   .w_re(w_re_aligned),
                   .w_im(w_im_aligned),
                   .a_prime_re(bfu_out_a_re),
                   .a_prime_im(bfu_out_a_im),
                   .b_prime_re(bfu_out_b_re),
                   .b_prime_im(bfu_out_b_im)
                 );

  //! @brief Block Floating Point Scanner.
  //! @details Analyzes the 17-bit BFU output dynamically to find the optimal shift amount.
  bfp_scanner #(
                .INPUT_WIDTH(DATA_WIDTH + 1) // 17 bits natively generated logic boundaries
              ) u_scanner (
                .clk(clk),
                .rst(rst),
                .new_stage(scanner_reset_trigger),
                .valid_in(write_enable),             // Only scan when writing valid data
                .a_prime_re(bfu_out_a_re),
                .a_prime_im(bfu_out_a_im),
                .b_prime_re(bfu_out_b_re),
                .b_prime_im(bfu_out_b_im),
                .block_shift_amount(block_shift_amount),
                .early_stop(early_stop)
              );


  assign final_exponent = current_exponent;

endmodule
