//! @brief Testbench for the FFT Processor.
//! This module instantiates the FFT processor and provides stimulus to it.
//! It also provides output to verify the FFT processor.

`timescale 1ns / 1ps

module fft_tb;

  parameter N = 2048; //! Number of FFT points
  parameter DATA_WIDTH = 16; //! Bit width of the data path and twiddle factors
  parameter LOG2_N = 11; //! Log base 2 of N

  // Signal Declarations
  reg clk; //! System clock
  reg rst; //! Synchronous active-high reset
  reg start_fft; //! Master enable signal to begin FFT processing

  // Outputs
  wire signed [7:0] final_exponent; //! The final global exponent after all stages are processed
  wire fft_done; //! Pulses high for exactly 1 cycle when the FFT has completely finished all processing and memory dumps.


  //! @brief Top-Level 16-bit Block Floating-Point FFT Processor.
  fft_top #(
            .N(N),
            .DATA_WIDTH(DATA_WIDTH),
            .LOG2_N(LOG2_N)
          ) u_fft_top (
            .clk(clk),
            .rst(rst),
            .start_fft(start_fft),
            .final_exponent(final_exponent),
            .fft_done(fft_done)
          );

  //! @brief Clock Generation (100MHz mapping).
  initial
  begin
    clk = 0;
    forever
      #5 clk = ~clk;
  end

  integer i; //! Loop counter for iterating through the FFT bins
  integer fd; //! File descriptor for writing output files

  // Temporary arrays for loading test signals from files
  reg signed [16:0] test_re [0:N-1]; //! Array to store the real part of the test signal
  reg signed [16:0] test_im [0:N-1]; //! Array to store the imaginary part of the test signal

  //! Testbench Main Stimulus Loop.
  initial
  begin
    // Setup waveform dump for GTKWave/Vivado visualization
    $dumpfile("fft_tb.vcd");
    $dumpvars(0, fft_tb);

    // Initial default pin states
    rst = 1;
    start_fft = 0;

    // Flush the global reset system pipeline for 100ns
    #100;

    // Safely de-assert reset aligned to logic edge
    @(negedge clk);
    rst = 0;

    //! PHASE 1: LOAD TEST SIGNAL FROM FILE.
    //! Load the test signals generated by Python
    $readmemh("stimulus_re.mem", test_re);
    $readmemh("stimulus_im.mem", test_im);

    $display("\n>>> Loading test signal from stimulus_re.mem and stimulus_im.mem...");
    for (i = 0; i < N; i = i + 1)
    begin
      //! Load both real and imaginary inputs into Bank 0
      u_fft_top.u_ram.bank0_re[i] = test_re[i];
      u_fft_top.u_ram.bank0_im[i] = test_im[i];

      //! Initialize Bank 1 to zero
      u_fft_top.u_ram.bank1_re[i] = 17'sd0;
      u_fft_top.u_ram.bank1_im[i] = 17'sd0;
    end
    $display(">>> Test signals loaded. %0d samples.", N);

    //! PHASE 2: TRIGGER PROCESSOR.
    @(posedge clk);
    start_fft = 1;
    $display(">>> Firing FFT State Machine Sequence...");

    //! PHASE 3: HARVEST COMPUTATION.
    wait(fft_done == 1'b1);

    $display("\n==================================================");
    $display("FFT PIPELINE HARVEST SECURED.");
    $display("==================================================");

    //! Log the BFP exponent.
    $display("Global Logic Scaling (Final Exponent): %d", final_exponent);

    //! Write the exponent to a file for the Python script.
    fd = $fopen("hw_exponent.txt", "w");
    $fwrite(fd, "%0d\n", final_exponent);
    $fclose(fd);

    //! Write all N output bins (real, imag) to CSV.
    fd = $fopen("hw_output.csv", "w");
    for (i = 0; i < N; i = i + 1)
    begin
      if (LOG2_N % 2 == 0)
      begin
        $fwrite(fd, "%0d,%0d\n",
                $signed(u_fft_top.u_ram.bank0_re[i]),
                $signed(u_fft_top.u_ram.bank0_im[i]));
      end
      else
      begin
        $fwrite(fd, "%0d,%0d\n",
                $signed(u_fft_top.u_ram.bank1_re[i]),
                $signed(u_fft_top.u_ram.bank1_im[i]));
      end
    end
    $fclose(fd);
    $display(">>> Written %0d bins to hw_output.csv", N);

    //! Print the first 16 bins to console for quick inspection.
    $display("--------------------------------------------------");
    $display("Bin Index\t| Real Spectrum\t\t| Imaginary Spectrum");
    $display("--------------------------------------------------");
    for (i = 0; i < 16; i = i + 1)
    begin
      if (LOG2_N % 2 == 0)
      begin
        $display("%d\t\t| %d\t\t\t| %d", i, $signed(u_fft_top.u_ram.bank0_re[i]), $signed(u_fft_top.u_ram.bank0_im[i]));
      end
      else
      begin
        $display("%d\t\t| %d\t\t\t| %d", i, $signed(u_fft_top.u_ram.bank1_re[i]), $signed(u_fft_top.u_ram.bank1_im[i]));
      end
    end
    $display("...");
    // Also print around the expected peak
    $display("--- Around expected peak (bin 50) ---");
    for (i = 45; i < 55; i = i + 1)
    begin
      if (LOG2_N % 2 == 0)
      begin
        $display("%d\t\t| %d\t\t\t| %d", i, $signed(u_fft_top.u_ram.bank0_re[i]), $signed(u_fft_top.u_ram.bank0_im[i]));
      end
      else
      begin
        $display("%d\t\t| %d\t\t\t| %d", i, $signed(u_fft_top.u_ram.bank1_re[i]), $signed(u_fft_top.u_ram.bank1_im[i]));
      end
    end

    $display("--------------------------------------------------");
    $display(">>> Simulation Finished.");
    $finish;
  end

endmodule
