-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_mdf_axis_to_word is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_in_TVALID : IN STD_LOGIC;
    w_in_din : OUT STD_LOGIC_VECTOR (128 downto 0);
    w_in_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
    w_in_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
    w_in_full_n : IN STD_LOGIC;
    w_in_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    s_in_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    s_in_TREADY : OUT STD_LOGIC;
    s_in_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    s_in_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
    s_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of fft_mdf_axis_to_word is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal icmp_ln301_fu_95_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln301_reg_134 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln301_reg_134_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal s_in_TDATA_blk_n : STD_LOGIC;
    signal w_in_blk_n : STD_LOGIC;
    signal x_data_reg_138 : STD_LOGIC_VECTOR (127 downto 0);
    signal x_last_reg_143 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_58 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal i_4_fu_101_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal regslice_both_s_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal s_in_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal s_in_TVALID_int_regslice : STD_LOGIC;
    signal s_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal s_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_s_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal s_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_s_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_in_V_user_V_U_apdone_blk : STD_LOGIC;
    signal s_in_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_in_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_in_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal s_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_in_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_in_V_id_V_U_apdone_blk : STD_LOGIC;
    signal s_in_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_in_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_in_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_in_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal s_in_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_in_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_in_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_condition_77 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component fft_mdf_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component fft_mdf_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component fft_mdf_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_s_in_V_data_V_U : component fft_mdf_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_in_TDATA,
        vld_in => s_in_TVALID,
        ack_in => regslice_both_s_in_V_data_V_U_ack_in,
        data_out => s_in_TDATA_int_regslice,
        vld_out => s_in_TVALID_int_regslice,
        ack_out => s_in_TREADY_int_regslice,
        apdone_blk => regslice_both_s_in_V_data_V_U_apdone_blk);

    regslice_both_s_in_V_keep_V_U : component fft_mdf_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_in_TKEEP,
        vld_in => s_in_TVALID,
        ack_in => regslice_both_s_in_V_keep_V_U_ack_in,
        data_out => s_in_TKEEP_int_regslice,
        vld_out => regslice_both_s_in_V_keep_V_U_vld_out,
        ack_out => s_in_TREADY_int_regslice,
        apdone_blk => regslice_both_s_in_V_keep_V_U_apdone_blk);

    regslice_both_s_in_V_strb_V_U : component fft_mdf_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_in_TSTRB,
        vld_in => s_in_TVALID,
        ack_in => regslice_both_s_in_V_strb_V_U_ack_in,
        data_out => s_in_TSTRB_int_regslice,
        vld_out => regslice_both_s_in_V_strb_V_U_vld_out,
        ack_out => s_in_TREADY_int_regslice,
        apdone_blk => regslice_both_s_in_V_strb_V_U_apdone_blk);

    regslice_both_s_in_V_user_V_U : component fft_mdf_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_in_TUSER,
        vld_in => s_in_TVALID,
        ack_in => regslice_both_s_in_V_user_V_U_ack_in,
        data_out => s_in_TUSER_int_regslice,
        vld_out => regslice_both_s_in_V_user_V_U_vld_out,
        ack_out => s_in_TREADY_int_regslice,
        apdone_blk => regslice_both_s_in_V_user_V_U_apdone_blk);

    regslice_both_s_in_V_last_V_U : component fft_mdf_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_in_TLAST,
        vld_in => s_in_TVALID,
        ack_in => regslice_both_s_in_V_last_V_U_ack_in,
        data_out => s_in_TLAST_int_regslice,
        vld_out => regslice_both_s_in_V_last_V_U_vld_out,
        ack_out => s_in_TREADY_int_regslice,
        apdone_blk => regslice_both_s_in_V_last_V_U_apdone_blk);

    regslice_both_s_in_V_id_V_U : component fft_mdf_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_in_TID,
        vld_in => s_in_TVALID,
        ack_in => regslice_both_s_in_V_id_V_U_ack_in,
        data_out => s_in_TID_int_regslice,
        vld_out => regslice_both_s_in_V_id_V_U_vld_out,
        ack_out => s_in_TREADY_int_regslice,
        apdone_blk => regslice_both_s_in_V_id_V_U_apdone_blk);

    regslice_both_s_in_V_dest_V_U : component fft_mdf_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_in_TDEST,
        vld_in => s_in_TVALID,
        ack_in => regslice_both_s_in_V_dest_V_U_ack_in,
        data_out => s_in_TDEST_int_regslice,
        vld_out => regslice_both_s_in_V_dest_V_U_vld_out,
        ack_out => s_in_TREADY_int_regslice,
        apdone_blk => regslice_both_s_in_V_dest_V_U_apdone_blk);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_loop_exit_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    i_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_77)) then
                if ((icmp_ln301_fu_95_p2 = ap_const_lv1_0)) then 
                    i_fu_58 <= i_4_fu_101_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_58 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                icmp_ln301_reg_134 <= icmp_ln301_fu_95_p2;
                x_data_reg_138 <= s_in_TDATA_int_regslice;
                x_last_reg_143 <= s_in_TLAST_int_regslice;
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (ap_CS_iter0_fsm, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, ap_done_reg, ap_block_state1_pp0_stage0_iter0, icmp_ln301_reg_134_pp0_iter0_reg, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                elsif (((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (icmp_ln301_reg_134_pp0_iter0_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0)))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter1_fsm_state2_blk_assign_proc : process(ap_block_state2_pp0_stage0_iter1)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) then 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(icmp_ln301_fu_95_p2, ap_done_reg, ap_start_int, s_in_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((icmp_ln301_fu_95_p2 = ap_const_lv1_0) and (s_in_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(w_in_full_n, icmp_ln301_reg_134)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln301_reg_134 = ap_const_lv1_0) and (w_in_full_n = ap_const_logic_0));
    end process;


    ap_condition_77_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
                ap_condition_77 <= (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_iter0_fsm_state1, icmp_ln301_fu_95_p2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (icmp_ln301_fu_95_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_done_reg, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_iter0_fsm_state1, i_fu_58, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_58;
        end if; 
    end process;

    i_4_fu_101_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv9_1));
    icmp_ln301_fu_95_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv9_100) else "0";
    icmp_ln301_reg_134_pp0_iter0_reg <= icmp_ln301_reg_134;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    s_in_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, icmp_ln301_fu_95_p2, ap_done_reg, ap_start_int, s_in_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0))) and (icmp_ln301_fu_95_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            s_in_TDATA_blk_n <= s_in_TVALID_int_regslice;
        else 
            s_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_in_TREADY <= regslice_both_s_in_V_data_V_U_ack_in;

    s_in_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, icmp_ln301_fu_95_p2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (icmp_ln301_fu_95_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            s_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            s_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    w_in_blk_n_assign_proc : process(w_in_full_n, icmp_ln301_reg_134, ap_CS_iter1_fsm_state2)
    begin
        if (((icmp_ln301_reg_134 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            w_in_blk_n <= w_in_full_n;
        else 
            w_in_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    w_in_din <= (x_last_reg_143 & x_data_reg_138);

    w_in_write_assign_proc : process(ap_done_reg, icmp_ln301_reg_134, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (icmp_ln301_reg_134 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            w_in_write <= ap_const_logic_1;
        else 
            w_in_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
