-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_mdf_Loop_read_loop_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    w_out_din : OUT STD_LOGIC_VECTOR (128 downto 0);
    w_out_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
    w_out_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
    w_out_full_n : IN STD_LOGIC;
    w_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (0 downto 0);
    bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_ce0 : OUT STD_LOGIC;
    bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_1_ce0 : OUT STD_LOGIC;
    bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of fft_mdf_Loop_read_loop_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter2_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter2_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_FF : STD_LOGIC_VECTOR (8 downto 0) := "011111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter2_fsm_state0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal icmp_ln271_reg_217 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_reg_217_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_CS_iter2_fsm_state3 : STD_LOGIC;
    signal icmp_ln271_fu_115_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal w_out_blk_n : STD_LOGIC;
    signal p_read_1_reg_212 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_last_fu_143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_last_reg_231 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_last_reg_231_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln286_fu_161_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln286_reg_236 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_i_i_reg_241 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_i_i_reg_246 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_i_i_reg_251 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln282_fu_137_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_64 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal i_6_fu_121_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (8 downto 0);
    signal rev_fu_127_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal raw_fu_154_p3 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_iter2_fsm_state3_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_84 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component fft_mdf_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component fft_mdf_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter2_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
            else
                ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    i_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_84)) then
                if ((icmp_ln271_fu_115_p2 = ap_const_lv1_0)) then 
                    i_fu_64 <= i_6_fu_121_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_64 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln271_reg_217 <= icmp_ln271_fu_115_p2;
                p_read_1_reg_212 <= p_read;
                y_last_reg_231 <= y_last_fu_143_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                icmp_ln271_reg_217_pp0_iter1_reg <= icmp_ln271_reg_217;
                tmp_10_i_i_reg_251 <= raw_fu_154_p3(127 downto 96);
                tmp_7_i_i_reg_241 <= raw_fu_154_p3(95 downto 64);
                tmp_9_i_i_reg_246 <= raw_fu_154_p3(63 downto 32);
                trunc_ln286_reg_236 <= trunc_ln286_fu_161_p1;
                y_last_reg_231_pp0_iter1_reg <= y_last_reg_231;
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (ap_CS_iter0_fsm, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter2_fsm_assign_proc : process (ap_CS_iter2_fsm, ap_done_reg, ap_CS_iter1_fsm_state2, icmp_ln271_reg_217_pp0_iter1_reg, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter2_fsm is
            when ap_ST_iter2_fsm_state3 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_0 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                elsif (((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (icmp_ln271_reg_217_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                end if;
            when ap_ST_iter2_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter2_fsm <= "XX";
        end case;
    end process;
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);
    ap_CS_iter2_fsm_state0 <= ap_CS_iter2_fsm(0);
    ap_CS_iter2_fsm_state3 <= ap_CS_iter2_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_iter2_fsm_state3_blk_assign_proc : process(ap_block_state3_pp0_stage0_iter2)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) then 
            ap_ST_iter2_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_iter2_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(w_out_full_n, icmp_ln271_reg_217_pp0_iter1_reg)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln271_reg_217_pp0_iter1_reg = ap_const_lv1_0) and (w_out_full_n = ap_const_logic_0));
    end process;


    ap_condition_84_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
                ap_condition_84 <= (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3, icmp_ln271_fu_115_p2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (icmp_ln271_fu_115_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_done_reg, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0, ap_CS_iter2_fsm_state0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_iter2_fsm_state0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_iter0_fsm_state1, i_fu_64, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_64;
        end if; 
    end process;

    bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_1_address0 <= zext_ln282_fu_137_p1(8 - 1 downto 0);

    bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_1_ce0_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_1_ce0 <= ap_const_logic_1;
        else 
            bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_address0 <= zext_ln282_fu_137_p1(8 - 1 downto 0);

    bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_ce0_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_ce0 <= ap_const_logic_1;
        else 
            bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    i_6_fu_121_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv9_1));
    icmp_ln271_fu_115_p2 <= "1" when (ap_sig_allocacmp_i_5 = ap_const_lv9_100) else "0";
    raw_fu_154_p3 <= 
        bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_1_q0 when (p_read_1_reg_212(0) = '1') else 
        bit_reverse_buf_stream_mdf_word_t_0_stream_mdf_word_t_0_bank_q0;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    
    rev_fu_127_p4_proc : process(ap_sig_allocacmp_i_5)
    variable vlo_cpy : STD_LOGIC_VECTOR(9+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(9+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(9 - 1 downto 0);
    variable rev_fu_127_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(9 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(9 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(9 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(4 - 1 downto 0) := ap_const_lv32_7(4 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(4 - 1 downto 0) := ap_const_lv32_0(4 - 1 downto 0);
        v0_cpy := ap_sig_allocacmp_i_5;
        if (vlo_cpy(4 - 1 downto 0) > vhi_cpy(4 - 1 downto 0)) then
            vhi_cpy(4-1 downto 0) := std_logic_vector(9-1-unsigned(ap_const_lv32_0(4-1 downto 0)));
            vlo_cpy(4-1 downto 0) := std_logic_vector(9-1-unsigned(ap_const_lv32_7(4-1 downto 0)));
            for rev_fu_127_p4_i in 0 to 9-1 loop
                v0_cpy(rev_fu_127_p4_i) := ap_sig_allocacmp_i_5(9-1-rev_fu_127_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(4-1 downto 0)))));

        section := (others=>'0');
        section(4-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(4-1 downto 0)) - unsigned(vlo_cpy(4-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(9-1 downto 0)))));
        res_mask := res_mask(9-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        rev_fu_127_p4 <= resvalue(8-1 downto 0);
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln286_fu_161_p1 <= raw_fu_154_p3(32 - 1 downto 0);

    w_out_blk_n_assign_proc : process(w_out_full_n, icmp_ln271_reg_217_pp0_iter1_reg, ap_CS_iter2_fsm_state3)
    begin
        if (((icmp_ln271_reg_217_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
            w_out_blk_n <= w_out_full_n;
        else 
            w_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    w_out_din <= ((((y_last_reg_231_pp0_iter1_reg & tmp_10_i_i_reg_251) & tmp_9_i_i_reg_246) & tmp_7_i_i_reg_241) & trunc_ln286_reg_236);

    w_out_write_assign_proc : process(ap_done_reg, icmp_ln271_reg_217_pp0_iter1_reg, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (icmp_ln271_reg_217_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
            w_out_write <= ap_const_logic_1;
        else 
            w_out_write <= ap_const_logic_0;
        end if; 
    end process;

    y_last_fu_143_p2 <= "1" when (ap_sig_allocacmp_i_5 = ap_const_lv9_FF) else "0";
    zext_ln282_fu_137_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rev_fu_127_p4),64));
end behav;
