// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_serial_fft_serial_Pipeline_bfly_loop11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        re_address0,
        re_ce0,
        re_we0,
        re_d0,
        re_q0,
        re_address1,
        re_ce1,
        re_we1,
        re_d1,
        re_q1,
        re_1_address0,
        re_1_ce0,
        re_1_we0,
        re_1_d0,
        re_1_q0,
        re_1_address1,
        re_1_ce1,
        re_1_we1,
        re_1_d1,
        re_1_q1,
        clz_next_6,
        im_address0,
        im_ce0,
        im_we0,
        im_d0,
        im_q0,
        im_address1,
        im_ce1,
        im_we1,
        im_d1,
        im_q1,
        im_1_address0,
        im_1_ce0,
        im_1_we0,
        im_1_d0,
        im_1_q0,
        im_1_address1,
        im_1_ce1,
        im_1_we1,
        im_1_d1,
        im_1_q1,
        TW_COS_LUT_address0,
        TW_COS_LUT_ce0,
        TW_COS_LUT_q0,
        TW_SIN_LUT_address0,
        TW_SIN_LUT_ce0,
        TW_SIN_LUT_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] re_address0;
output   re_ce0;
output   re_we0;
output  [16:0] re_d0;
input  [16:0] re_q0;
output  [8:0] re_address1;
output   re_ce1;
output   re_we1;
output  [16:0] re_d1;
input  [16:0] re_q1;
output  [8:0] re_1_address0;
output   re_1_ce0;
output   re_1_we0;
output  [16:0] re_1_d0;
input  [16:0] re_1_q0;
output  [8:0] re_1_address1;
output   re_1_ce1;
output   re_1_we1;
output  [16:0] re_1_d1;
input  [16:0] re_1_q1;
input  [3:0] clz_next_6;
output  [8:0] im_address0;
output   im_ce0;
output   im_we0;
output  [16:0] im_d0;
input  [16:0] im_q0;
output  [8:0] im_address1;
output   im_ce1;
output   im_we1;
output  [16:0] im_d1;
input  [16:0] im_q1;
output  [8:0] im_1_address0;
output   im_1_ce0;
output   im_1_we0;
output  [16:0] im_1_d0;
input  [16:0] im_1_q0;
output  [8:0] im_1_address1;
output   im_1_ce1;
output   im_1_we1;
output  [16:0] im_1_d1;
input  [16:0] im_1_q1;
output  [7:0] TW_COS_LUT_address0;
output   TW_COS_LUT_ce0;
input  [14:0] TW_COS_LUT_q0;
output  [7:0] TW_SIN_LUT_address0;
output   TW_SIN_LUT_ce0;
input  [14:0] TW_SIN_LUT_q0;

reg ap_idle;
reg[8:0] re_address0;
reg re_ce0;
reg re_we0;
reg[8:0] re_address1;
reg re_ce1;
reg re_we1;
reg[8:0] re_1_address0;
reg re_1_ce0;
reg re_1_we0;
reg[8:0] re_1_address1;
reg re_1_ce1;
reg re_1_we1;
reg im_ce0;
reg im_we0;
reg im_ce1;
reg im_we1;
reg im_1_ce0;
reg im_1_we0;
reg im_1_ce1;
reg im_1_we1;
reg TW_COS_LUT_ce0;
reg TW_SIN_LUT_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln132_fu_276_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln132_reg_943;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln132_fu_288_p1;
reg   [0:0] trunc_ln132_reg_947;
reg   [8:0] re_addr_reg_955;
reg   [8:0] re_1_addr_reg_960;
wire   [2:0] select_ln21_75_fu_456_p3;
reg   [2:0] select_ln21_75_reg_965;
wire   [0:0] icmp_ln21_45_fu_464_p2;
reg   [0:0] icmp_ln21_45_reg_970;
wire   [0:0] icmp_ln21_46_fu_470_p2;
reg   [0:0] icmp_ln21_46_reg_978;
reg   [8:0] im_addr_reg_986;
reg   [8:0] im_1_addr_reg_991;
reg   [8:0] re_addr_8_reg_996;
reg   [8:0] re_1_addr_8_reg_1001;
reg   [8:0] im_addr_8_reg_1006;
reg   [8:0] im_1_addr_8_reg_1011;
reg   [1:0] trunc_ln21_6_reg_1016;
reg   [16:0] re_load_reg_1033;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [16:0] re_1_load_reg_1038;
wire   [15:0] zext_ln21_fu_523_p1;
reg   [15:0] zext_ln21_reg_1043;
wire   [15:0] w_im_fu_662_p2;
reg  signed [15:0] w_im_reg_1050;
wire  signed [31:0] sext_ln159_fu_668_p1;
reg  signed [31:0] sext_ln159_reg_1055;
wire  signed [31:0] sext_ln159_7_fu_672_p1;
reg  signed [31:0] sext_ln159_7_reg_1061;
reg   [16:0] im_load_reg_1067;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [16:0] im_1_load_reg_1072;
wire   [16:0] v_30_fu_682_p3;
reg   [16:0] v_30_reg_1077;
wire   [15:0] b_im_31_fu_693_p1;
reg   [15:0] b_im_31_reg_1082;
wire   [0:0] icmp_ln24_21_fu_697_p2;
reg   [0:0] icmp_ln24_21_reg_1087;
wire   [15:0] b_im_32_fu_703_p2;
reg   [15:0] b_im_32_reg_1092;
wire  signed [31:0] sext_ln160_7_fu_708_p1;
reg  signed [31:0] sext_ln160_7_reg_1097;
wire   [15:0] a_re_34_fu_767_p3;
reg   [15:0] a_re_34_reg_1103;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire   [15:0] b_im_34_fu_797_p3;
reg  signed [15:0] b_im_34_reg_1108;
wire   [15:0] a_im_34_fu_855_p3;
reg   [15:0] a_im_34_reg_1113;
wire    ap_block_pp0_stage4_11001;
wire  signed [31:0] sext_ln160_fu_862_p1;
reg  signed [31:0] sext_ln160_reg_1118;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln140_fu_322_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln141_fu_336_p1;
wire   [63:0] zext_ln25_fu_512_p1;
reg   [9:0] bfly_10_fu_136;
wire   [9:0] bfly_11_fu_282_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_bfly;
wire   [16:0] a_re_out_fu_877_p2;
wire    ap_block_pp0_stage4;
wire   [16:0] b_re_out_fu_885_p2;
wire    ap_block_pp0_stage1;
wire   [16:0] a_im_out_fu_905_p2;
wire   [16:0] b_im_out_fu_913_p2;
wire   [2:0] tmp_s_fu_292_p4;
wire   [4:0] tmp_4_fu_302_p4;
wire   [8:0] lshr_ln140_4_fu_312_p4;
wire   [8:0] or_ln141_fu_330_p2;
wire   [3:0] trunc_ln142_fu_344_p1;
wire   [0:0] icmp_ln21_44_fu_386_p2;
wire   [0:0] icmp_ln21_43_fu_380_p2;
wire   [0:0] icmp_ln21_fu_374_p2;
wire   [0:0] icmp_ln21_42_fu_368_p2;
wire   [0:0] icmp_ln21_41_fu_362_p2;
wire   [0:0] icmp_ln21_40_fu_356_p2;
wire   [0:0] or_ln21_fu_400_p2;
wire   [2:0] select_ln21_fu_392_p3;
wire   [2:0] select_ln21_71_fu_406_p3;
wire   [0:0] or_ln21_19_fu_414_p2;
wire   [0:0] or_ln21_20_fu_428_p2;
wire   [2:0] select_ln21_72_fu_420_p3;
wire   [0:0] or_ln21_21_fu_442_p2;
wire   [2:0] select_ln21_73_fu_434_p3;
wire   [2:0] select_ln21_74_fu_448_p3;
wire   [6:0] tw_n_fu_348_p3;
wire   [7:0] zext_ln22_fu_494_p1;
wire   [0:0] tmp_fu_486_p3;
wire   [7:0] sub_ln23_fu_498_p2;
wire   [7:0] rom_addr_fu_504_p3;
wire   [16:0] v_29_fu_526_p3;
wire   [1:0] trunc_ln19_23_fu_533_p1;
wire   [0:0] icmp_ln24_20_fu_541_p2;
wire   [16:0] zext_ln24_20_fu_547_p1;
wire   [16:0] rounded_25_fu_551_p2;
wire   [15:0] b_re_31_fu_537_p1;
wire   [15:0] b_re_32_fu_567_p2;
wire   [15:0] b_re_fu_557_p4;
wire   [15:0] b_re_33_fu_573_p3;
wire   [0:0] icmp_ln28_fu_595_p2;
wire   [14:0] select_ln28_16_fu_600_p3;
wire   [15:0] zext_ln28_fu_608_p1;
wire   [0:0] icmp_ln28_11_fu_618_p2;
wire   [15:0] zext_ln26_fu_591_p1;
wire   [15:0] w_re_36_fu_612_p2;
wire   [0:0] icmp_ln28_12_fu_631_p2;
wire   [15:0] zext_ln151_fu_587_p1;
wire   [15:0] w_re_37_fu_623_p3;
wire   [0:0] or_ln28_fu_644_p2;
wire   [14:0] w_re_39_fu_650_p3;
wire   [15:0] zext_ln151_6_fu_658_p1;
wire  signed [15:0] b_re_34_fu_580_p3;
wire  signed [15:0] w_re_38_fu_636_p3;
wire    ap_block_pp0_stage2;
wire   [1:0] trunc_ln19_24_fu_689_p1;
wire  signed [15:0] grp_fu_711_p1;
wire    ap_block_pp0_stage3;
wire   [16:0] v_fu_716_p3;
wire   [1:0] trunc_ln19_fu_721_p1;
wire   [0:0] icmp_ln24_fu_729_p2;
wire   [16:0] zext_ln24_fu_735_p1;
wire   [16:0] rounded_fu_739_p2;
wire   [15:0] a_re_31_fu_725_p1;
wire   [15:0] a_re_32_fu_755_p2;
wire   [15:0] a_re_fu_745_p4;
wire   [15:0] a_re_33_fu_760_p3;
wire   [16:0] zext_ln24_21_fu_774_p1;
wire   [16:0] rounded_26_fu_777_p2;
wire   [15:0] b_im_fu_782_p4;
wire   [15:0] b_im_33_fu_792_p3;
wire   [16:0] v_28_fu_804_p3;
wire   [1:0] trunc_ln19_22_fu_809_p1;
wire   [0:0] icmp_ln24_19_fu_817_p2;
wire   [16:0] zext_ln24_19_fu_823_p1;
wire   [16:0] rounded_24_fu_827_p2;
wire   [15:0] a_im_31_fu_813_p1;
wire   [15:0] a_im_32_fu_843_p2;
wire   [15:0] a_im_fu_833_p4;
wire   [15:0] a_im_33_fu_848_p3;
wire  signed [31:0] grp_fu_921_p3;
wire   [16:0] wb_re_s_fu_865_p4;
wire  signed [16:0] sext_ln175_fu_874_p1;
wire  signed [31:0] grp_fu_929_p3;
wire   [16:0] wb_im_s_fu_893_p4;
wire  signed [16:0] sext_ln176_fu_902_p1;
wire  signed [15:0] grp_fu_921_p0;
wire  signed [31:0] grp_fu_676_p2;
wire  signed [15:0] grp_fu_929_p0;
wire  signed [15:0] grp_fu_929_p1;
wire  signed [31:0] grp_fu_711_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 bfly_10_fu_136 = 10'd0;
#0 ap_done_reg = 1'b0;
end

fft_serial_mul_16s_16s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_4_1_U103(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_re_38_fu_636_p3),
    .din1(b_re_34_fu_580_p3),
    .ce(1'b1),
    .dout(grp_fu_676_p2)
);

fft_serial_mul_16s_16s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_4_1_U104(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_im_reg_1050),
    .din1(grp_fu_711_p1),
    .ce(1'b1),
    .dout(grp_fu_711_p2)
);

fft_serial_mac_mulsub_16s_16s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_mulsub_16s_16s_32s_32_1_1_U105(
    .din0(grp_fu_921_p0),
    .din1(b_im_34_reg_1108),
    .din2(grp_fu_676_p2),
    .dout(grp_fu_921_p3)
);

fft_serial_mac_muladd_16s_16s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_1_1_U106(
    .din0(grp_fu_929_p0),
    .din1(grp_fu_929_p1),
    .din2(grp_fu_711_p2),
    .dout(grp_fu_929_p3)
);

fft_serial_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln132_fu_276_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            bfly_10_fu_136 <= bfly_11_fu_282_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            bfly_10_fu_136 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        a_im_34_reg_1113 <= a_im_34_fu_855_p3;
        sext_ln160_reg_1118 <= sext_ln160_fu_862_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        a_re_34_reg_1103 <= a_re_34_fu_767_p3;
        b_im_34_reg_1108 <= b_im_34_fu_797_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_im_31_reg_1082 <= b_im_31_fu_693_p1;
        b_im_32_reg_1092 <= b_im_32_fu_703_p2;
        icmp_ln24_21_reg_1087 <= icmp_ln24_21_fu_697_p2;
        sext_ln160_7_reg_1097 <= sext_ln160_7_fu_708_p1;
        v_30_reg_1077 <= v_30_fu_682_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln132_reg_943 <= icmp_ln132_fu_276_p2;
        icmp_ln21_45_reg_970 <= icmp_ln21_45_fu_464_p2;
        icmp_ln21_46_reg_978 <= icmp_ln21_46_fu_470_p2;
        im_1_addr_8_reg_1011[4 : 0] <= zext_ln141_fu_336_p1[4 : 0];
im_1_addr_8_reg_1011[8 : 6] <= zext_ln141_fu_336_p1[8 : 6];
        im_1_addr_reg_991[4 : 0] <= zext_ln140_fu_322_p1[4 : 0];
im_1_addr_reg_991[8 : 6] <= zext_ln140_fu_322_p1[8 : 6];
        im_addr_8_reg_1006[4 : 0] <= zext_ln141_fu_336_p1[4 : 0];
im_addr_8_reg_1006[8 : 6] <= zext_ln141_fu_336_p1[8 : 6];
        im_addr_reg_986[4 : 0] <= zext_ln140_fu_322_p1[4 : 0];
im_addr_reg_986[8 : 6] <= zext_ln140_fu_322_p1[8 : 6];
        re_1_addr_8_reg_1001[4 : 0] <= zext_ln141_fu_336_p1[4 : 0];
re_1_addr_8_reg_1001[8 : 6] <= zext_ln141_fu_336_p1[8 : 6];
        re_1_addr_reg_960[4 : 0] <= zext_ln140_fu_322_p1[4 : 0];
re_1_addr_reg_960[8 : 6] <= zext_ln140_fu_322_p1[8 : 6];
        re_addr_8_reg_996[4 : 0] <= zext_ln141_fu_336_p1[4 : 0];
re_addr_8_reg_996[8 : 6] <= zext_ln141_fu_336_p1[8 : 6];
        re_addr_reg_955[4 : 0] <= zext_ln140_fu_322_p1[4 : 0];
re_addr_reg_955[8 : 6] <= zext_ln140_fu_322_p1[8 : 6];
        select_ln21_75_reg_965 <= select_ln21_75_fu_456_p3;
        trunc_ln132_reg_947 <= trunc_ln132_fu_288_p1;
        trunc_ln21_6_reg_1016 <= {{ap_sig_allocacmp_bfly[5:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        im_1_load_reg_1072 <= im_1_q1;
        im_load_reg_1067 <= im_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        re_1_load_reg_1038 <= re_1_q1;
        re_load_reg_1033 <= re_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sext_ln159_7_reg_1061 <= sext_ln159_7_fu_672_p1;
        sext_ln159_reg_1055 <= sext_ln159_fu_668_p1;
        w_im_reg_1050 <= w_im_fu_662_p2;
        zext_ln21_reg_1043[2 : 0] <= zext_ln21_fu_523_p1[2 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW_COS_LUT_ce0 = 1'b1;
    end else begin
        TW_COS_LUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW_SIN_LUT_ce0 = 1'b1;
    end else begin
        TW_SIN_LUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln132_fu_276_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_bfly = 10'd0;
    end else begin
        ap_sig_allocacmp_bfly = bfly_10_fu_136;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_1_ce0 = 1'b1;
    end else begin
        im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_1_ce1 = 1'b1;
    end else begin
        im_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_947 == 1'd1))) begin
        im_1_we0 = 1'b1;
    end else begin
        im_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_947 == 1'd1))) begin
        im_1_we1 = 1'b1;
    end else begin
        im_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_ce0 = 1'b1;
    end else begin
        im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_ce1 = 1'b1;
    end else begin
        im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_947 == 1'd0))) begin
        im_we0 = 1'b1;
    end else begin
        im_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_947 == 1'd0))) begin
        im_we1 = 1'b1;
    end else begin
        im_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_1_address0 = re_1_addr_8_reg_1001;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_1_address0 = zext_ln141_fu_336_p1;
        end else begin
            re_1_address0 = 'bx;
        end
    end else begin
        re_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_1_address1 = re_1_addr_reg_960;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_1_address1 = zext_ln140_fu_322_p1;
        end else begin
            re_1_address1 = 'bx;
        end
    end else begin
        re_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_1_ce0 = 1'b1;
    end else begin
        re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_1_ce1 = 1'b1;
    end else begin
        re_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_947 == 1'd1) & (icmp_ln132_reg_943 == 1'd0))) begin
        re_1_we0 = 1'b1;
    end else begin
        re_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_947 == 1'd1) & (icmp_ln132_reg_943 == 1'd0))) begin
        re_1_we1 = 1'b1;
    end else begin
        re_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_address0 = re_addr_8_reg_996;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_address0 = zext_ln141_fu_336_p1;
        end else begin
            re_address0 = 'bx;
        end
    end else begin
        re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_address1 = re_addr_reg_955;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_address1 = zext_ln140_fu_322_p1;
        end else begin
            re_address1 = 'bx;
        end
    end else begin
        re_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_ce0 = 1'b1;
    end else begin
        re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_ce1 = 1'b1;
    end else begin
        re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_947 == 1'd0) & (icmp_ln132_reg_943 == 1'd0))) begin
        re_we0 = 1'b1;
    end else begin
        re_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_947 == 1'd0) & (icmp_ln132_reg_943 == 1'd0))) begin
        re_we1 = 1'b1;
    end else begin
        re_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign TW_COS_LUT_address0 = zext_ln25_fu_512_p1;

assign TW_SIN_LUT_address0 = zext_ln25_fu_512_p1;

assign a_im_31_fu_813_p1 = v_28_fu_804_p3[15:0];

assign a_im_32_fu_843_p2 = a_im_31_fu_813_p1 << zext_ln21_reg_1043;

assign a_im_33_fu_848_p3 = ((icmp_ln21_45_reg_970[0:0] == 1'b1) ? a_im_31_fu_813_p1 : a_im_32_fu_843_p2);

assign a_im_34_fu_855_p3 = ((icmp_ln21_46_reg_978[0:0] == 1'b1) ? a_im_fu_833_p4 : a_im_33_fu_848_p3);

assign a_im_fu_833_p4 = {{rounded_24_fu_827_p2[16:1]}};

assign a_im_out_fu_905_p2 = ($signed(wb_im_s_fu_893_p4) + $signed(sext_ln176_fu_902_p1));

assign a_re_31_fu_725_p1 = v_fu_716_p3[15:0];

assign a_re_32_fu_755_p2 = a_re_31_fu_725_p1 << zext_ln21_reg_1043;

assign a_re_33_fu_760_p3 = ((icmp_ln21_45_reg_970[0:0] == 1'b1) ? a_re_31_fu_725_p1 : a_re_32_fu_755_p2);

assign a_re_34_fu_767_p3 = ((icmp_ln21_46_reg_978[0:0] == 1'b1) ? a_re_fu_745_p4 : a_re_33_fu_760_p3);

assign a_re_fu_745_p4 = {{rounded_fu_739_p2[16:1]}};

assign a_re_out_fu_877_p2 = ($signed(wb_re_s_fu_865_p4) + $signed(sext_ln175_fu_874_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_im_31_fu_693_p1 = v_30_fu_682_p3[15:0];

assign b_im_32_fu_703_p2 = b_im_31_fu_693_p1 << zext_ln21_reg_1043;

assign b_im_33_fu_792_p3 = ((icmp_ln21_45_reg_970[0:0] == 1'b1) ? b_im_31_reg_1082 : b_im_32_reg_1092);

assign b_im_34_fu_797_p3 = ((icmp_ln21_46_reg_978[0:0] == 1'b1) ? b_im_fu_782_p4 : b_im_33_fu_792_p3);

assign b_im_fu_782_p4 = {{rounded_26_fu_777_p2[16:1]}};

assign b_im_out_fu_913_p2 = ($signed(sext_ln176_fu_902_p1) - $signed(wb_im_s_fu_893_p4));

assign b_re_31_fu_537_p1 = v_29_fu_526_p3[15:0];

assign b_re_32_fu_567_p2 = b_re_31_fu_537_p1 << zext_ln21_fu_523_p1;

assign b_re_33_fu_573_p3 = ((icmp_ln21_45_reg_970[0:0] == 1'b1) ? b_re_31_fu_537_p1 : b_re_32_fu_567_p2);

assign b_re_34_fu_580_p3 = ((icmp_ln21_46_reg_978[0:0] == 1'b1) ? b_re_fu_557_p4 : b_re_33_fu_573_p3);

assign b_re_fu_557_p4 = {{rounded_25_fu_551_p2[16:1]}};

assign b_re_out_fu_885_p2 = ($signed(sext_ln175_fu_874_p1) - $signed(wb_re_s_fu_865_p4));

assign bfly_11_fu_282_p2 = (ap_sig_allocacmp_bfly + 10'd1);

assign grp_fu_711_p1 = sext_ln159_reg_1055;

assign grp_fu_921_p0 = sext_ln160_7_reg_1097;

assign grp_fu_929_p0 = sext_ln159_7_reg_1061;

assign grp_fu_929_p1 = sext_ln160_reg_1118;

assign icmp_ln132_fu_276_p2 = ((ap_sig_allocacmp_bfly == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln21_40_fu_356_p2 = ((clz_next_6 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln21_41_fu_362_p2 = ((clz_next_6 == 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln21_42_fu_368_p2 = ((clz_next_6 == 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln21_43_fu_380_p2 = ((clz_next_6 == 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln21_44_fu_386_p2 = ((clz_next_6 == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln21_45_fu_464_p2 = ((clz_next_6 == 4'd1) ? 1'b1 : 1'b0);

assign icmp_ln21_46_fu_470_p2 = ((clz_next_6 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_374_p2 = ((clz_next_6 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln24_19_fu_817_p2 = ((trunc_ln19_22_fu_809_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_20_fu_541_p2 = ((trunc_ln19_23_fu_533_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_21_fu_697_p2 = ((trunc_ln19_24_fu_689_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_729_p2 = ((trunc_ln19_fu_721_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln28_11_fu_618_p2 = ((trunc_ln21_6_reg_1016 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln28_12_fu_631_p2 = ((trunc_ln21_6_reg_1016 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_595_p2 = ((trunc_ln21_6_reg_1016 == 2'd2) ? 1'b1 : 1'b0);

assign im_1_address0 = im_1_addr_8_reg_1011;

assign im_1_address1 = im_1_addr_reg_991;

assign im_1_d0 = b_im_out_fu_913_p2;

assign im_1_d1 = a_im_out_fu_905_p2;

assign im_address0 = im_addr_8_reg_1006;

assign im_address1 = im_addr_reg_986;

assign im_d0 = b_im_out_fu_913_p2;

assign im_d1 = a_im_out_fu_905_p2;

assign lshr_ln140_4_fu_312_p4 = {{{tmp_s_fu_292_p4}, {1'd0}}, {tmp_4_fu_302_p4}};

assign or_ln141_fu_330_p2 = (lshr_ln140_4_fu_312_p4 | 9'd32);

assign or_ln21_19_fu_414_p2 = (icmp_ln21_fu_374_p2 | icmp_ln21_42_fu_368_p2);

assign or_ln21_20_fu_428_p2 = (icmp_ln21_41_fu_362_p2 | icmp_ln21_40_fu_356_p2);

assign or_ln21_21_fu_442_p2 = (or_ln21_fu_400_p2 | or_ln21_19_fu_414_p2);

assign or_ln21_fu_400_p2 = (icmp_ln21_44_fu_386_p2 | icmp_ln21_43_fu_380_p2);

assign or_ln28_fu_644_p2 = (icmp_ln28_fu_595_p2 | icmp_ln28_11_fu_618_p2);

assign re_1_d0 = b_re_out_fu_885_p2;

assign re_1_d1 = a_re_out_fu_877_p2;

assign re_d0 = b_re_out_fu_885_p2;

assign re_d1 = a_re_out_fu_877_p2;

assign rom_addr_fu_504_p3 = ((tmp_fu_486_p3[0:0] == 1'b1) ? sub_ln23_fu_498_p2 : zext_ln22_fu_494_p1);

assign rounded_24_fu_827_p2 = (v_28_fu_804_p3 + zext_ln24_19_fu_823_p1);

assign rounded_25_fu_551_p2 = (v_29_fu_526_p3 + zext_ln24_20_fu_547_p1);

assign rounded_26_fu_777_p2 = (v_30_reg_1077 + zext_ln24_21_fu_774_p1);

assign rounded_fu_739_p2 = (v_fu_716_p3 + zext_ln24_fu_735_p1);

assign select_ln21_71_fu_406_p3 = ((icmp_ln21_fu_374_p2[0:0] == 1'b1) ? 3'd3 : 3'd4);

assign select_ln21_72_fu_420_p3 = ((icmp_ln21_41_fu_362_p2[0:0] == 1'b1) ? 3'd5 : 3'd6);

assign select_ln21_73_fu_434_p3 = ((or_ln21_fu_400_p2[0:0] == 1'b1) ? select_ln21_fu_392_p3 : select_ln21_71_fu_406_p3);

assign select_ln21_74_fu_448_p3 = ((or_ln21_20_fu_428_p2[0:0] == 1'b1) ? select_ln21_72_fu_420_p3 : 3'd7);

assign select_ln21_75_fu_456_p3 = ((or_ln21_21_fu_442_p2[0:0] == 1'b1) ? select_ln21_73_fu_434_p3 : select_ln21_74_fu_448_p3);

assign select_ln21_fu_392_p3 = ((icmp_ln21_44_fu_386_p2[0:0] == 1'b1) ? 3'd1 : 3'd2);

assign select_ln28_16_fu_600_p3 = ((icmp_ln28_fu_595_p2[0:0] == 1'b1) ? TW_SIN_LUT_q0 : TW_COS_LUT_q0);

assign sext_ln159_7_fu_672_p1 = w_re_38_fu_636_p3;

assign sext_ln159_fu_668_p1 = b_re_34_fu_580_p3;

assign sext_ln160_7_fu_708_p1 = w_im_reg_1050;

assign sext_ln160_fu_862_p1 = b_im_34_reg_1108;

assign sext_ln175_fu_874_p1 = $signed(a_re_34_reg_1103);

assign sext_ln176_fu_902_p1 = $signed(a_im_34_reg_1113);

assign sub_ln23_fu_498_p2 = ($signed(8'd128) - $signed(zext_ln22_fu_494_p1));

assign tmp_4_fu_302_p4 = {{ap_sig_allocacmp_bfly[5:1]}};

assign tmp_fu_486_p3 = ap_sig_allocacmp_bfly[32'd4];

assign tmp_s_fu_292_p4 = {{ap_sig_allocacmp_bfly[8:6]}};

assign trunc_ln132_fu_288_p1 = ap_sig_allocacmp_bfly[0:0];

assign trunc_ln142_fu_344_p1 = ap_sig_allocacmp_bfly[3:0];

assign trunc_ln19_22_fu_809_p1 = v_28_fu_804_p3[1:0];

assign trunc_ln19_23_fu_533_p1 = v_29_fu_526_p3[1:0];

assign trunc_ln19_24_fu_689_p1 = v_30_fu_682_p3[1:0];

assign trunc_ln19_fu_721_p1 = v_fu_716_p3[1:0];

assign tw_n_fu_348_p3 = {{trunc_ln142_fu_344_p1}, {3'd0}};

assign v_28_fu_804_p3 = ((trunc_ln132_reg_947[0:0] == 1'b1) ? im_1_load_reg_1072 : im_load_reg_1067);

assign v_29_fu_526_p3 = ((trunc_ln132_reg_947[0:0] == 1'b1) ? re_1_q0 : re_q0);

assign v_30_fu_682_p3 = ((trunc_ln132_reg_947[0:0] == 1'b1) ? im_1_q0 : im_q0);

assign v_fu_716_p3 = ((trunc_ln132_reg_947[0:0] == 1'b1) ? re_1_load_reg_1038 : re_load_reg_1033);

assign w_im_fu_662_p2 = (zext_ln151_6_fu_658_p1 ^ 16'd65535);

assign w_re_36_fu_612_p2 = (zext_ln28_fu_608_p1 ^ 16'd65535);

assign w_re_37_fu_623_p3 = ((icmp_ln28_11_fu_618_p2[0:0] == 1'b1) ? zext_ln26_fu_591_p1 : w_re_36_fu_612_p2);

assign w_re_38_fu_636_p3 = ((icmp_ln28_12_fu_631_p2[0:0] == 1'b1) ? zext_ln151_fu_587_p1 : w_re_37_fu_623_p3);

assign w_re_39_fu_650_p3 = ((or_ln28_fu_644_p2[0:0] == 1'b1) ? TW_COS_LUT_q0 : TW_SIN_LUT_q0);

assign wb_im_s_fu_893_p4 = {{grp_fu_929_p3[31:15]}};

assign wb_re_s_fu_865_p4 = {{grp_fu_921_p3[31:15]}};

assign zext_ln140_fu_322_p1 = lshr_ln140_4_fu_312_p4;

assign zext_ln141_fu_336_p1 = or_ln141_fu_330_p2;

assign zext_ln151_6_fu_658_p1 = w_re_39_fu_650_p3;

assign zext_ln151_fu_587_p1 = TW_COS_LUT_q0;

assign zext_ln21_fu_523_p1 = select_ln21_75_reg_965;

assign zext_ln22_fu_494_p1 = tw_n_fu_348_p3;

assign zext_ln24_19_fu_823_p1 = icmp_ln24_19_fu_817_p2;

assign zext_ln24_20_fu_547_p1 = icmp_ln24_20_fu_541_p2;

assign zext_ln24_21_fu_774_p1 = icmp_ln24_21_reg_1087;

assign zext_ln24_fu_735_p1 = icmp_ln24_fu_729_p2;

assign zext_ln25_fu_512_p1 = rom_addr_fu_504_p3;

assign zext_ln26_fu_591_p1 = TW_SIN_LUT_q0;

assign zext_ln28_fu_608_p1 = select_ln28_16_fu_600_p3;

always @ (posedge ap_clk) begin
    re_addr_reg_955[5] <= 1'b0;
    re_1_addr_reg_960[5] <= 1'b0;
    im_addr_reg_986[5] <= 1'b0;
    im_1_addr_reg_991[5] <= 1'b0;
    re_addr_8_reg_996[5] <= 1'b1;
    re_1_addr_8_reg_1001[5] <= 1'b1;
    im_addr_8_reg_1006[5] <= 1'b1;
    im_1_addr_8_reg_1011[5] <= 1'b1;
    zext_ln21_reg_1043[15:3] <= 13'b0000000000000;
end

endmodule //fft_serial_fft_serial_Pipeline_bfly_loop11
