// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_serial_fft_serial_Pipeline_bfly_loop1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        re_address0,
        re_ce0,
        re_we0,
        re_d0,
        re_q0,
        re_address1,
        re_ce1,
        re_we1,
        re_d1,
        re_q1,
        re_1_address0,
        re_1_ce0,
        re_1_we0,
        re_1_d0,
        re_1_q0,
        re_1_address1,
        re_1_ce1,
        re_1_we1,
        re_1_d1,
        re_1_q1,
        clz_next_1,
        im_address0,
        im_ce0,
        im_we0,
        im_d0,
        im_q0,
        im_address1,
        im_ce1,
        im_we1,
        im_d1,
        im_q1,
        im_1_address0,
        im_1_ce0,
        im_1_we0,
        im_1_d0,
        im_1_q0,
        im_1_address1,
        im_1_ce1,
        im_1_we1,
        im_1_d1,
        im_1_q1,
        or_mask_2_out,
        or_mask_2_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] re_address0;
output   re_ce0;
output   re_we0;
output  [16:0] re_d0;
input  [16:0] re_q0;
output  [8:0] re_address1;
output   re_ce1;
output   re_we1;
output  [16:0] re_d1;
input  [16:0] re_q1;
output  [8:0] re_1_address0;
output   re_1_ce0;
output   re_1_we0;
output  [16:0] re_1_d0;
input  [16:0] re_1_q0;
output  [8:0] re_1_address1;
output   re_1_ce1;
output   re_1_we1;
output  [16:0] re_1_d1;
input  [16:0] re_1_q1;
input  [3:0] clz_next_1;
output  [8:0] im_address0;
output   im_ce0;
output   im_we0;
output  [16:0] im_d0;
input  [16:0] im_q0;
output  [8:0] im_address1;
output   im_ce1;
output   im_we1;
output  [16:0] im_d1;
input  [16:0] im_q1;
output  [8:0] im_1_address0;
output   im_1_ce0;
output   im_1_we0;
output  [16:0] im_1_d0;
input  [16:0] im_1_q0;
output  [8:0] im_1_address1;
output   im_1_ce1;
output   im_1_we1;
output  [16:0] im_1_d1;
input  [16:0] im_1_q1;
output  [7:0] or_mask_2_out;
output   or_mask_2_out_ap_vld;

reg ap_idle;
reg[8:0] re_address0;
reg re_ce0;
reg re_we0;
reg[8:0] re_address1;
reg re_ce1;
reg re_we1;
reg[8:0] re_1_address0;
reg re_1_ce0;
reg re_1_we0;
reg[8:0] re_1_address1;
reg re_1_ce1;
reg re_1_we1;
reg[8:0] im_address0;
reg im_ce0;
reg im_we0;
reg[8:0] im_address1;
reg im_ce1;
reg im_we1;
reg[8:0] im_1_address0;
reg im_1_ce0;
reg im_1_we0;
reg[8:0] im_1_address1;
reg im_1_ce1;
reg im_1_we1;
reg or_mask_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln126_fu_242_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln126_reg_1000;
wire   [9:0] bfly_12_fu_248_p2;
reg   [9:0] bfly_12_reg_1004;
wire   [0:0] j_fu_258_p1;
reg   [0:0] j_reg_1009;
reg   [8:0] re_addr_2_reg_1021;
reg   [8:0] re_1_addr_2_reg_1027;
wire   [2:0] select_ln21_5_fu_402_p3;
reg   [2:0] select_ln21_5_reg_1033;
wire   [0:0] icmp_ln21_6_fu_410_p2;
reg   [0:0] icmp_ln21_6_reg_1038;
wire   [0:0] icmp_ln21_7_fu_416_p2;
reg   [0:0] icmp_ln21_7_reg_1046;
reg   [8:0] im_addr_2_reg_1054;
reg   [8:0] im_1_addr_2_reg_1060;
reg   [8:0] re_addr_3_reg_1066;
reg   [8:0] re_1_addr_3_reg_1072;
reg   [8:0] im_addr_3_reg_1078;
reg   [8:0] im_1_addr_3_reg_1084;
wire   [16:0] v_fu_793_p2;
reg   [16:0] v_reg_1090;
wire    ap_CS_fsm_state2;
wire   [16:0] v_45_fu_805_p2;
reg   [16:0] v_45_reg_1096;
wire   [16:0] v_46_fu_813_p2;
reg   [16:0] v_46_reg_1102;
wire   [16:0] v_47_fu_819_p2;
reg   [16:0] v_47_reg_1110;
wire   [63:0] zext_ln134_fu_280_p1;
wire   [63:0] zext_ln135_fu_294_p1;
reg   [7:0] or_mask_2_fu_108;
wire   [7:0] or_mask_fu_966_p2;
wire    ap_loop_init;
reg   [9:0] bfly_1_fu_112;
reg   [9:0] ap_sig_allocacmp_bfly;
wire   [7:0] tmp_4_fu_262_p4;
wire   [8:0] and_ln1_fu_272_p3;
wire   [8:0] trunc_ln126_fu_254_p1;
wire   [8:0] or_ln135_fu_288_p2;
wire   [0:0] icmp_ln21_5_fu_332_p2;
wire   [0:0] icmp_ln21_4_fu_326_p2;
wire   [0:0] icmp_ln21_3_fu_320_p2;
wire   [0:0] icmp_ln21_2_fu_314_p2;
wire   [0:0] icmp_ln21_1_fu_308_p2;
wire   [0:0] icmp_ln21_fu_302_p2;
wire   [0:0] or_ln21_fu_346_p2;
wire   [2:0] select_ln21_fu_338_p3;
wire   [2:0] select_ln21_1_fu_352_p3;
wire   [0:0] or_ln21_1_fu_360_p2;
wire   [0:0] or_ln21_2_fu_374_p2;
wire   [2:0] select_ln21_2_fu_366_p3;
wire   [0:0] or_ln21_3_fu_388_p2;
wire   [2:0] select_ln21_3_fu_380_p3;
wire   [2:0] select_ln21_4_fu_394_p3;
wire   [16:0] v_8_fu_422_p3;
wire   [1:0] trunc_ln19_fu_429_p1;
wire   [0:0] icmp_ln24_fu_437_p2;
wire   [16:0] zext_ln24_fu_443_p1;
wire   [16:0] rounded_fu_447_p2;
wire   [15:0] a_re_fu_433_p1;
wire   [15:0] zext_ln21_fu_463_p1;
wire   [15:0] a_re_32_fu_466_p2;
wire   [15:0] a_re_1_fu_453_p4;
wire   [15:0] a_re_33_fu_472_p3;
wire   [16:0] v_9_fu_486_p3;
wire   [1:0] trunc_ln19_25_fu_493_p1;
wire   [0:0] icmp_ln24_1_fu_501_p2;
wire   [16:0] zext_ln24_1_fu_507_p1;
wire   [16:0] rounded_25_fu_511_p2;
wire   [15:0] a_im_fu_497_p1;
wire   [15:0] a_im_32_fu_527_p2;
wire   [15:0] a_im_1_fu_517_p4;
wire   [15:0] a_im_33_fu_533_p3;
wire   [16:0] v_10_fu_547_p3;
wire   [1:0] trunc_ln19_26_fu_554_p1;
wire   [0:0] icmp_ln24_2_fu_562_p2;
wire   [16:0] zext_ln24_2_fu_568_p1;
wire   [16:0] rounded_26_fu_572_p2;
wire   [15:0] b_re_fu_558_p1;
wire   [15:0] b_re_32_fu_588_p2;
wire   [15:0] b_re_1_fu_578_p4;
wire   [15:0] b_re_33_fu_594_p3;
wire   [16:0] v_11_fu_608_p3;
wire   [1:0] trunc_ln19_27_fu_615_p1;
wire   [0:0] icmp_ln24_3_fu_623_p2;
wire   [16:0] zext_ln24_3_fu_629_p1;
wire   [16:0] rounded_27_fu_633_p2;
wire   [15:0] b_im_fu_619_p1;
wire   [15:0] b_im_32_fu_649_p2;
wire   [15:0] b_im_1_fu_639_p4;
wire   [15:0] b_im_33_fu_655_p3;
wire  signed [15:0] b_re_34_fu_601_p3;
wire  signed [15:0] b_im_34_fu_662_p3;
wire   [30:0] shl_ln150_1_fu_685_p3;
wire   [30:0] select_ln150_fu_693_p3;
wire  signed [31:0] sext_ln150_6_fu_700_p1;
wire  signed [31:0] sext_ln150_2_fu_669_p1;
wire   [30:0] shl_ln150_2_fu_710_p3;
wire  signed [30:0] sext_ln150_5_fu_681_p1;
wire   [30:0] select_ln150_1_fu_718_p3;
wire   [31:0] sub_ln150_fu_704_p2;
wire  signed [31:0] sext_ln150_7_fu_725_p1;
wire  signed [30:0] sext_ln150_3_fu_673_p1;
wire   [30:0] select_ln151_fu_735_p3;
wire   [30:0] select_ln151_1_fu_746_p3;
wire  signed [31:0] sext_ln151_1_fu_753_p1;
wire  signed [31:0] sext_ln150_4_fu_677_p1;
wire   [31:0] sub_ln151_fu_757_p2;
wire  signed [31:0] sext_ln151_fu_742_p1;
wire   [31:0] wb_re_fu_729_p2;
wire   [31:0] wb_im_fu_763_p2;
wire   [15:0] a_re_34_fu_479_p3;
wire   [16:0] wb_re_s_fu_769_p4;
wire  signed [16:0] sext_ln158_fu_789_p1;
wire   [15:0] a_im_34_fu_540_p3;
wire   [16:0] wb_im_s_fu_779_p4;
wire  signed [16:0] sext_ln159_fu_801_p1;
wire   [7:0] top8_fu_828_p4;
wire   [0:0] tmp_fu_837_p3;
wire   [7:0] xor_ln67_4_fu_844_p2;
wire   [7:0] top8_25_fu_858_p4;
wire   [0:0] tmp_34_fu_867_p3;
wire   [7:0] xor_ln67_5_fu_874_p2;
wire   [7:0] top8_26_fu_888_p4;
wire   [0:0] tmp_35_fu_897_p3;
wire   [7:0] xor_ln67_6_fu_904_p2;
wire   [7:0] top8_27_fu_918_p4;
wire   [0:0] tmp_36_fu_927_p3;
wire   [7:0] xor_ln67_7_fu_934_p2;
wire   [7:0] select_ln67_7_fu_940_p3;
wire   [7:0] select_ln67_6_fu_910_p3;
wire   [7:0] or_ln166_5_fu_948_p2;
wire   [7:0] select_ln67_5_fu_880_p3;
wire   [7:0] or_ln166_4_fu_954_p2;
wire   [7:0] select_ln67_4_fu_850_p3;
wire   [7:0] or_ln166_6_fu_960_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 or_mask_2_fu_108 = 8'd0;
#0 bfly_1_fu_112 = 10'd0;
#0 ap_done_reg = 1'b0;
end

fft_serial_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        bfly_1_fu_112 <= 10'd0;
    end else if (((icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        bfly_1_fu_112 <= bfly_12_reg_1004;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        or_mask_2_fu_108 <= 8'd0;
    end else if (((icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        or_mask_2_fu_108 <= or_mask_fu_966_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        bfly_12_reg_1004 <= bfly_12_fu_248_p2;
        icmp_ln126_reg_1000 <= icmp_ln126_fu_242_p2;
        icmp_ln21_6_reg_1038 <= icmp_ln21_6_fu_410_p2;
        icmp_ln21_7_reg_1046 <= icmp_ln21_7_fu_416_p2;
        im_1_addr_2_reg_1060[8 : 1] <= zext_ln134_fu_280_p1[8 : 1];
        im_1_addr_3_reg_1084[8 : 1] <= zext_ln135_fu_294_p1[8 : 1];
        im_addr_2_reg_1054[8 : 1] <= zext_ln134_fu_280_p1[8 : 1];
        im_addr_3_reg_1078[8 : 1] <= zext_ln135_fu_294_p1[8 : 1];
        j_reg_1009 <= j_fu_258_p1;
        re_1_addr_2_reg_1027[8 : 1] <= zext_ln134_fu_280_p1[8 : 1];
        re_1_addr_3_reg_1072[8 : 1] <= zext_ln135_fu_294_p1[8 : 1];
        re_addr_2_reg_1021[8 : 1] <= zext_ln134_fu_280_p1[8 : 1];
        re_addr_3_reg_1066[8 : 1] <= zext_ln135_fu_294_p1[8 : 1];
        select_ln21_5_reg_1033 <= select_ln21_5_fu_402_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        v_45_reg_1096 <= v_45_fu_805_p2;
        v_46_reg_1102 <= v_46_fu_813_p2;
        v_47_reg_1110 <= v_47_fu_819_p2;
        v_reg_1090 <= v_fu_793_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln126_fu_242_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_bfly = 10'd0;
    end else begin
        ap_sig_allocacmp_bfly = bfly_1_fu_112;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        im_1_address0 = im_1_addr_2_reg_1060;
    end else if (((icmp_ln126_fu_242_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        im_1_address0 = zext_ln135_fu_294_p1;
    end else begin
        im_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd1) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        im_1_address1 = im_1_addr_3_reg_1084;
    end else if (((icmp_ln126_fu_242_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        im_1_address1 = zext_ln134_fu_280_p1;
    end else begin
        im_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((j_reg_1009 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln126_fu_242_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        im_1_ce0 = 1'b1;
    end else begin
        im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((j_reg_1009 == 1'd1) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln126_fu_242_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        im_1_ce1 = 1'b1;
    end else begin
        im_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        im_1_we0 = 1'b1;
    end else begin
        im_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd1) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        im_1_we1 = 1'b1;
    end else begin
        im_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        im_address0 = im_addr_2_reg_1054;
    end else if (((icmp_ln126_fu_242_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        im_address0 = zext_ln135_fu_294_p1;
    end else begin
        im_address0 = 'bx;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd0) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        im_address1 = im_addr_3_reg_1078;
    end else if (((icmp_ln126_fu_242_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        im_address1 = zext_ln134_fu_280_p1;
    end else begin
        im_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((j_reg_1009 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln126_fu_242_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        im_ce0 = 1'b1;
    end else begin
        im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((j_reg_1009 == 1'd0) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln126_fu_242_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        im_ce1 = 1'b1;
    end else begin
        im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        im_we0 = 1'b1;
    end else begin
        im_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd0) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        im_we1 = 1'b1;
    end else begin
        im_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln126_fu_242_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        or_mask_2_out_ap_vld = 1'b1;
    end else begin
        or_mask_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        re_1_address0 = re_1_addr_2_reg_1027;
    end else if (((icmp_ln126_fu_242_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        re_1_address0 = zext_ln135_fu_294_p1;
    end else begin
        re_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd1) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        re_1_address1 = re_1_addr_3_reg_1072;
    end else if (((icmp_ln126_fu_242_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        re_1_address1 = zext_ln134_fu_280_p1;
    end else begin
        re_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((j_reg_1009 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln126_fu_242_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        re_1_ce0 = 1'b1;
    end else begin
        re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((j_reg_1009 == 1'd1) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln126_fu_242_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        re_1_ce1 = 1'b1;
    end else begin
        re_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        re_1_we0 = 1'b1;
    end else begin
        re_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd1) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        re_1_we1 = 1'b1;
    end else begin
        re_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        re_address0 = re_addr_2_reg_1021;
    end else if (((icmp_ln126_fu_242_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        re_address0 = zext_ln135_fu_294_p1;
    end else begin
        re_address0 = 'bx;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd0) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        re_address1 = re_addr_3_reg_1066;
    end else if (((icmp_ln126_fu_242_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        re_address1 = zext_ln134_fu_280_p1;
    end else begin
        re_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((j_reg_1009 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln126_fu_242_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        re_ce0 = 1'b1;
    end else begin
        re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((j_reg_1009 == 1'd0) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln126_fu_242_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        re_ce1 = 1'b1;
    end else begin
        re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        re_we0 = 1'b1;
    end else begin
        re_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((j_reg_1009 == 1'd0) & (icmp_ln126_reg_1000 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        re_we1 = 1'b1;
    end else begin
        re_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln126_fu_242_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_im_1_fu_517_p4 = {{rounded_25_fu_511_p2[16:1]}};

assign a_im_32_fu_527_p2 = a_im_fu_497_p1 << zext_ln21_fu_463_p1;

assign a_im_33_fu_533_p3 = ((icmp_ln21_6_reg_1038[0:0] == 1'b1) ? a_im_fu_497_p1 : a_im_32_fu_527_p2);

assign a_im_34_fu_540_p3 = ((icmp_ln21_7_reg_1046[0:0] == 1'b1) ? a_im_1_fu_517_p4 : a_im_33_fu_533_p3);

assign a_im_fu_497_p1 = v_9_fu_486_p3[15:0];

assign a_re_1_fu_453_p4 = {{rounded_fu_447_p2[16:1]}};

assign a_re_32_fu_466_p2 = a_re_fu_433_p1 << zext_ln21_fu_463_p1;

assign a_re_33_fu_472_p3 = ((icmp_ln21_6_reg_1038[0:0] == 1'b1) ? a_re_fu_433_p1 : a_re_32_fu_466_p2);

assign a_re_34_fu_479_p3 = ((icmp_ln21_7_reg_1046[0:0] == 1'b1) ? a_re_1_fu_453_p4 : a_re_33_fu_472_p3);

assign a_re_fu_433_p1 = v_8_fu_422_p3[15:0];

assign and_ln1_fu_272_p3 = {{tmp_4_fu_262_p4}, {1'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_im_1_fu_639_p4 = {{rounded_27_fu_633_p2[16:1]}};

assign b_im_32_fu_649_p2 = b_im_fu_619_p1 << zext_ln21_fu_463_p1;

assign b_im_33_fu_655_p3 = ((icmp_ln21_6_reg_1038[0:0] == 1'b1) ? b_im_fu_619_p1 : b_im_32_fu_649_p2);

assign b_im_34_fu_662_p3 = ((icmp_ln21_7_reg_1046[0:0] == 1'b1) ? b_im_1_fu_639_p4 : b_im_33_fu_655_p3);

assign b_im_fu_619_p1 = v_11_fu_608_p3[15:0];

assign b_re_1_fu_578_p4 = {{rounded_26_fu_572_p2[16:1]}};

assign b_re_32_fu_588_p2 = b_re_fu_558_p1 << zext_ln21_fu_463_p1;

assign b_re_33_fu_594_p3 = ((icmp_ln21_6_reg_1038[0:0] == 1'b1) ? b_re_fu_558_p1 : b_re_32_fu_588_p2);

assign b_re_34_fu_601_p3 = ((icmp_ln21_7_reg_1046[0:0] == 1'b1) ? b_re_1_fu_578_p4 : b_re_33_fu_594_p3);

assign b_re_fu_558_p1 = v_10_fu_547_p3[15:0];

assign bfly_12_fu_248_p2 = (ap_sig_allocacmp_bfly + 10'd1);

assign icmp_ln126_fu_242_p2 = ((ap_sig_allocacmp_bfly == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln21_1_fu_308_p2 = ((clz_next_1 == 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln21_2_fu_314_p2 = ((clz_next_1 == 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln21_3_fu_320_p2 = ((clz_next_1 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln21_4_fu_326_p2 = ((clz_next_1 == 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln21_5_fu_332_p2 = ((clz_next_1 == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln21_6_fu_410_p2 = ((clz_next_1 == 4'd1) ? 1'b1 : 1'b0);

assign icmp_ln21_7_fu_416_p2 = ((clz_next_1 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_302_p2 = ((clz_next_1 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln24_1_fu_501_p2 = ((trunc_ln19_25_fu_493_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_2_fu_562_p2 = ((trunc_ln19_26_fu_554_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_3_fu_623_p2 = ((trunc_ln19_27_fu_615_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_437_p2 = ((trunc_ln19_fu_429_p1 == 2'd3) ? 1'b1 : 1'b0);

assign im_1_d0 = v_45_fu_805_p2;

assign im_1_d1 = v_47_reg_1110;

assign im_d0 = v_45_fu_805_p2;

assign im_d1 = v_47_reg_1110;

assign j_fu_258_p1 = ap_sig_allocacmp_bfly[0:0];

assign or_ln135_fu_288_p2 = (trunc_ln126_fu_254_p1 | 9'd1);

assign or_ln166_4_fu_954_p2 = (select_ln67_5_fu_880_p3 | or_ln166_5_fu_948_p2);

assign or_ln166_5_fu_948_p2 = (select_ln67_7_fu_940_p3 | select_ln67_6_fu_910_p3);

assign or_ln166_6_fu_960_p2 = (select_ln67_4_fu_850_p3 | or_ln166_4_fu_954_p2);

assign or_ln21_1_fu_360_p2 = (icmp_ln21_3_fu_320_p2 | icmp_ln21_2_fu_314_p2);

assign or_ln21_2_fu_374_p2 = (icmp_ln21_fu_302_p2 | icmp_ln21_1_fu_308_p2);

assign or_ln21_3_fu_388_p2 = (or_ln21_fu_346_p2 | or_ln21_1_fu_360_p2);

assign or_ln21_fu_346_p2 = (icmp_ln21_5_fu_332_p2 | icmp_ln21_4_fu_326_p2);

assign or_mask_2_out = or_mask_2_fu_108;

assign or_mask_fu_966_p2 = (or_mask_2_fu_108 | or_ln166_6_fu_960_p2);

assign re_1_d0 = v_fu_793_p2;

assign re_1_d1 = v_46_reg_1102;

assign re_d0 = v_fu_793_p2;

assign re_d1 = v_46_reg_1102;

assign rounded_25_fu_511_p2 = (v_9_fu_486_p3 + zext_ln24_1_fu_507_p1);

assign rounded_26_fu_572_p2 = (v_10_fu_547_p3 + zext_ln24_2_fu_568_p1);

assign rounded_27_fu_633_p2 = (v_11_fu_608_p3 + zext_ln24_3_fu_629_p1);

assign rounded_fu_447_p2 = (v_8_fu_422_p3 + zext_ln24_fu_443_p1);

assign select_ln150_1_fu_718_p3 = ((j_reg_1009[0:0] == 1'b1) ? shl_ln150_2_fu_710_p3 : sext_ln150_5_fu_681_p1);

assign select_ln150_fu_693_p3 = ((j_reg_1009[0:0] == 1'b1) ? 31'd0 : shl_ln150_1_fu_685_p3);

assign select_ln151_1_fu_746_p3 = ((j_reg_1009[0:0] == 1'b1) ? 31'd0 : shl_ln150_2_fu_710_p3);

assign select_ln151_fu_735_p3 = ((j_reg_1009[0:0] == 1'b1) ? shl_ln150_1_fu_685_p3 : sext_ln150_3_fu_673_p1);

assign select_ln21_1_fu_352_p3 = ((icmp_ln21_3_fu_320_p2[0:0] == 1'b1) ? 3'd3 : 3'd4);

assign select_ln21_2_fu_366_p3 = ((icmp_ln21_1_fu_308_p2[0:0] == 1'b1) ? 3'd5 : 3'd6);

assign select_ln21_3_fu_380_p3 = ((or_ln21_fu_346_p2[0:0] == 1'b1) ? select_ln21_fu_338_p3 : select_ln21_1_fu_352_p3);

assign select_ln21_4_fu_394_p3 = ((or_ln21_2_fu_374_p2[0:0] == 1'b1) ? select_ln21_2_fu_366_p3 : 3'd7);

assign select_ln21_5_fu_402_p3 = ((or_ln21_3_fu_388_p2[0:0] == 1'b1) ? select_ln21_3_fu_380_p3 : select_ln21_4_fu_394_p3);

assign select_ln21_fu_338_p3 = ((icmp_ln21_5_fu_332_p2[0:0] == 1'b1) ? 3'd1 : 3'd2);

assign select_ln67_4_fu_850_p3 = ((tmp_fu_837_p3[0:0] == 1'b1) ? xor_ln67_4_fu_844_p2 : top8_fu_828_p4);

assign select_ln67_5_fu_880_p3 = ((tmp_34_fu_867_p3[0:0] == 1'b1) ? xor_ln67_5_fu_874_p2 : top8_25_fu_858_p4);

assign select_ln67_6_fu_910_p3 = ((tmp_35_fu_897_p3[0:0] == 1'b1) ? xor_ln67_6_fu_904_p2 : top8_26_fu_888_p4);

assign select_ln67_7_fu_940_p3 = ((tmp_36_fu_927_p3[0:0] == 1'b1) ? xor_ln67_7_fu_934_p2 : top8_27_fu_918_p4);

assign sext_ln150_2_fu_669_p1 = b_re_34_fu_601_p3;

assign sext_ln150_3_fu_673_p1 = b_re_34_fu_601_p3;

assign sext_ln150_4_fu_677_p1 = b_im_34_fu_662_p3;

assign sext_ln150_5_fu_681_p1 = b_im_34_fu_662_p3;

assign sext_ln150_6_fu_700_p1 = $signed(select_ln150_fu_693_p3);

assign sext_ln150_7_fu_725_p1 = $signed(select_ln150_1_fu_718_p3);

assign sext_ln151_1_fu_753_p1 = $signed(select_ln151_1_fu_746_p3);

assign sext_ln151_fu_742_p1 = $signed(select_ln151_fu_735_p3);

assign sext_ln158_fu_789_p1 = $signed(a_re_34_fu_479_p3);

assign sext_ln159_fu_801_p1 = $signed(a_im_34_fu_540_p3);

assign shl_ln150_1_fu_685_p3 = {{b_re_34_fu_601_p3}, {15'd0}};

assign shl_ln150_2_fu_710_p3 = {{b_im_34_fu_662_p3}, {15'd0}};

assign sub_ln150_fu_704_p2 = ($signed(sext_ln150_6_fu_700_p1) - $signed(sext_ln150_2_fu_669_p1));

assign sub_ln151_fu_757_p2 = ($signed(sext_ln151_1_fu_753_p1) - $signed(sext_ln150_4_fu_677_p1));

assign tmp_34_fu_867_p3 = v_45_reg_1096[32'd16];

assign tmp_35_fu_897_p3 = v_46_reg_1102[32'd16];

assign tmp_36_fu_927_p3 = v_47_reg_1110[32'd16];

assign tmp_4_fu_262_p4 = {{ap_sig_allocacmp_bfly[8:1]}};

assign tmp_fu_837_p3 = v_reg_1090[32'd16];

assign top8_25_fu_858_p4 = {{v_45_reg_1096[15:8]}};

assign top8_26_fu_888_p4 = {{v_46_reg_1102[15:8]}};

assign top8_27_fu_918_p4 = {{v_47_reg_1110[15:8]}};

assign top8_fu_828_p4 = {{v_reg_1090[15:8]}};

assign trunc_ln126_fu_254_p1 = ap_sig_allocacmp_bfly[8:0];

assign trunc_ln19_25_fu_493_p1 = v_9_fu_486_p3[1:0];

assign trunc_ln19_26_fu_554_p1 = v_10_fu_547_p3[1:0];

assign trunc_ln19_27_fu_615_p1 = v_11_fu_608_p3[1:0];

assign trunc_ln19_fu_429_p1 = v_8_fu_422_p3[1:0];

assign v_10_fu_547_p3 = ((j_reg_1009[0:0] == 1'b1) ? re_1_q0 : re_q0);

assign v_11_fu_608_p3 = ((j_reg_1009[0:0] == 1'b1) ? im_1_q0 : im_q0);

assign v_45_fu_805_p2 = ($signed(wb_im_s_fu_779_p4) + $signed(sext_ln159_fu_801_p1));

assign v_46_fu_813_p2 = ($signed(sext_ln158_fu_789_p1) - $signed(wb_re_s_fu_769_p4));

assign v_47_fu_819_p2 = ($signed(sext_ln159_fu_801_p1) - $signed(wb_im_s_fu_779_p4));

assign v_8_fu_422_p3 = ((j_reg_1009[0:0] == 1'b1) ? re_1_q1 : re_q1);

assign v_9_fu_486_p3 = ((j_reg_1009[0:0] == 1'b1) ? im_1_q1 : im_q1);

assign v_fu_793_p2 = ($signed(wb_re_s_fu_769_p4) + $signed(sext_ln158_fu_789_p1));

assign wb_im_fu_763_p2 = ($signed(sub_ln151_fu_757_p2) - $signed(sext_ln151_fu_742_p1));

assign wb_im_s_fu_779_p4 = {{wb_im_fu_763_p2[31:15]}};

assign wb_re_fu_729_p2 = ($signed(sub_ln150_fu_704_p2) + $signed(sext_ln150_7_fu_725_p1));

assign wb_re_s_fu_769_p4 = {{wb_re_fu_729_p2[31:15]}};

assign xor_ln67_4_fu_844_p2 = (top8_fu_828_p4 ^ 8'd255);

assign xor_ln67_5_fu_874_p2 = (top8_25_fu_858_p4 ^ 8'd255);

assign xor_ln67_6_fu_904_p2 = (top8_26_fu_888_p4 ^ 8'd255);

assign xor_ln67_7_fu_934_p2 = (top8_27_fu_918_p4 ^ 8'd255);

assign zext_ln134_fu_280_p1 = and_ln1_fu_272_p3;

assign zext_ln135_fu_294_p1 = or_ln135_fu_288_p2;

assign zext_ln21_fu_463_p1 = select_ln21_5_reg_1033;

assign zext_ln24_1_fu_507_p1 = icmp_ln24_1_fu_501_p2;

assign zext_ln24_2_fu_568_p1 = icmp_ln24_2_fu_562_p2;

assign zext_ln24_3_fu_629_p1 = icmp_ln24_3_fu_623_p2;

assign zext_ln24_fu_443_p1 = icmp_ln24_fu_437_p2;

always @ (posedge ap_clk) begin
    re_addr_2_reg_1021[0] <= 1'b0;
    re_1_addr_2_reg_1027[0] <= 1'b0;
    im_addr_2_reg_1054[0] <= 1'b0;
    im_1_addr_2_reg_1060[0] <= 1'b0;
    re_addr_3_reg_1066[0] <= 1'b1;
    re_1_addr_3_reg_1072[0] <= 1'b1;
    im_addr_3_reg_1078[0] <= 1'b1;
    im_1_addr_3_reg_1084[0] <= 1'b1;
end

endmodule //fft_serial_fft_serial_Pipeline_bfly_loop1
