// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_serial_fft_serial_Pipeline_bfly_loop2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        re_address0,
        re_ce0,
        re_we0,
        re_d0,
        re_q0,
        re_address1,
        re_ce1,
        re_we1,
        re_d1,
        re_q1,
        re_1_address0,
        re_1_ce0,
        re_1_we0,
        re_1_d0,
        re_1_q0,
        re_1_address1,
        re_1_ce1,
        re_1_we1,
        re_1_d1,
        re_1_q1,
        clz_next_2,
        im_address0,
        im_ce0,
        im_we0,
        im_d0,
        im_q0,
        im_address1,
        im_ce1,
        im_we1,
        im_d1,
        im_q1,
        im_1_address0,
        im_1_ce0,
        im_1_we0,
        im_1_d0,
        im_1_q0,
        im_1_address1,
        im_1_ce1,
        im_1_we1,
        im_1_d1,
        im_1_q1,
        or_mask_3_out,
        or_mask_3_out_ap_vld,
        TW_COS_LUT_address0,
        TW_COS_LUT_ce0,
        TW_COS_LUT_q0,
        TW_SIN_LUT_address0,
        TW_SIN_LUT_ce0,
        TW_SIN_LUT_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] re_address0;
output   re_ce0;
output   re_we0;
output  [16:0] re_d0;
input  [16:0] re_q0;
output  [8:0] re_address1;
output   re_ce1;
output   re_we1;
output  [16:0] re_d1;
input  [16:0] re_q1;
output  [8:0] re_1_address0;
output   re_1_ce0;
output   re_1_we0;
output  [16:0] re_1_d0;
input  [16:0] re_1_q0;
output  [8:0] re_1_address1;
output   re_1_ce1;
output   re_1_we1;
output  [16:0] re_1_d1;
input  [16:0] re_1_q1;
input  [3:0] clz_next_2;
output  [8:0] im_address0;
output   im_ce0;
output   im_we0;
output  [16:0] im_d0;
input  [16:0] im_q0;
output  [8:0] im_address1;
output   im_ce1;
output   im_we1;
output  [16:0] im_d1;
input  [16:0] im_q1;
output  [8:0] im_1_address0;
output   im_1_ce0;
output   im_1_we0;
output  [16:0] im_1_d0;
input  [16:0] im_1_q0;
output  [8:0] im_1_address1;
output   im_1_ce1;
output   im_1_we1;
output  [16:0] im_1_d1;
input  [16:0] im_1_q1;
output  [7:0] or_mask_3_out;
output   or_mask_3_out_ap_vld;
output  [7:0] TW_COS_LUT_address0;
output   TW_COS_LUT_ce0;
input  [14:0] TW_COS_LUT_q0;
output  [7:0] TW_SIN_LUT_address0;
output   TW_SIN_LUT_ce0;
input  [14:0] TW_SIN_LUT_q0;

reg ap_idle;
reg re_ce0;
reg re_we0;
reg re_ce1;
reg re_we1;
reg re_1_ce0;
reg re_1_we0;
reg re_1_ce1;
reg re_1_we1;
reg[8:0] im_address0;
reg im_ce0;
reg im_we0;
reg[8:0] im_address1;
reg im_ce1;
reg im_we1;
reg[8:0] im_1_address0;
reg im_1_ce0;
reg im_1_we0;
reg[8:0] im_1_address1;
reg im_1_ce1;
reg im_1_we1;
reg or_mask_3_out_ap_vld;
reg TW_COS_LUT_ce0;
reg TW_SIN_LUT_ce0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln126_fu_274_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln126_reg_1071;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln126_fu_286_p1;
reg   [0:0] trunc_ln126_reg_1075;
reg   [8:0] re_addr_4_reg_1083;
reg   [8:0] re_1_addr_4_reg_1088;
wire   [2:0] select_ln21_19_fu_444_p3;
reg   [2:0] select_ln21_19_reg_1093;
wire   [0:0] icmp_ln21_14_fu_452_p2;
reg   [0:0] icmp_ln21_14_reg_1098;
wire   [0:0] icmp_ln21_15_fu_458_p2;
reg   [0:0] icmp_ln21_15_reg_1106;
reg   [8:0] im_addr_4_reg_1114;
reg   [8:0] im_1_addr_4_reg_1119;
reg   [8:0] re_addr_5_reg_1124;
reg   [8:0] re_1_addr_5_reg_1129;
reg   [8:0] im_addr_5_reg_1134;
reg   [8:0] im_1_addr_5_reg_1139;
wire   [0:0] icmp_ln28_fu_474_p2;
reg   [0:0] icmp_ln28_reg_1154;
wire   [0:0] icmp_ln28_1_fu_480_p2;
reg   [0:0] icmp_ln28_1_reg_1160;
wire   [0:0] icmp_ln28_2_fu_486_p2;
reg   [0:0] icmp_ln28_2_reg_1166;
wire   [15:0] zext_ln21_fu_497_p1;
reg   [15:0] zext_ln21_reg_1171;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [16:0] v_13_fu_500_p3;
reg   [16:0] v_13_reg_1177;
wire   [15:0] a_im_fu_511_p1;
reg   [15:0] a_im_reg_1182;
wire   [0:0] icmp_ln24_5_fu_515_p2;
reg   [0:0] icmp_ln24_5_reg_1187;
wire   [15:0] a_im_29_fu_521_p2;
reg   [15:0] a_im_29_reg_1192;
wire  signed [31:0] sext_ln150_9_fu_649_p1;
reg  signed [31:0] sext_ln150_9_reg_1197;
wire  signed [31:0] sext_ln150_10_fu_653_p1;
wire  signed [31:0] sext_ln150_11_fu_657_p1;
reg  signed [31:0] sext_ln150_11_reg_1209;
wire   [16:0] v_12_fu_661_p3;
reg   [16:0] v_12_reg_1215;
wire    ap_block_pp0_stage2_11001;
wire   [15:0] a_re_fu_672_p1;
reg   [15:0] a_re_reg_1220;
wire   [0:0] icmp_ln24_4_fu_676_p2;
reg   [0:0] icmp_ln24_4_reg_1225;
wire   [15:0] a_re_29_fu_682_p2;
reg   [15:0] a_re_29_reg_1230;
wire  signed [31:0] sext_ln150_8_fu_777_p1;
reg  signed [31:0] sext_ln150_8_reg_1235;
wire   [16:0] v_42_fu_799_p2;
reg   [16:0] v_42_reg_1240;
wire   [16:0] v_44_fu_807_p2;
reg   [16:0] v_44_reg_1246;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln134_fu_322_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln135_fu_336_p1;
wire   [63:0] select_ln25_fu_464_p3;
reg   [7:0] or_mask_3_fu_118;
wire   [7:0] or_mask_fu_1023_p2;
wire    ap_loop_init;
reg   [9:0] bfly_2_fu_122;
wire   [9:0] bfly_11_fu_280_p2;
reg   [9:0] ap_sig_allocacmp_bfly;
wire    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage1;
wire   [16:0] v_fu_862_p2;
wire   [16:0] v_43_fu_870_p2;
wire   [6:0] tmp_6_fu_294_p4;
wire   [0:0] tmp_fu_304_p3;
wire   [8:0] lshr_ln_fu_312_p4;
wire   [8:0] or_ln135_fu_330_p2;
wire   [0:0] icmp_ln21_13_fu_374_p2;
wire   [0:0] icmp_ln21_12_fu_368_p2;
wire   [0:0] icmp_ln21_11_fu_362_p2;
wire   [0:0] icmp_ln21_10_fu_356_p2;
wire   [0:0] icmp_ln21_9_fu_350_p2;
wire   [0:0] icmp_ln21_8_fu_344_p2;
wire   [0:0] or_ln21_4_fu_388_p2;
wire   [2:0] select_ln21_fu_380_p3;
wire   [2:0] select_ln21_15_fu_394_p3;
wire   [0:0] or_ln21_5_fu_402_p2;
wire   [0:0] or_ln21_6_fu_416_p2;
wire   [2:0] select_ln21_16_fu_408_p3;
wire   [0:0] or_ln21_7_fu_430_p2;
wire   [2:0] select_ln21_17_fu_422_p3;
wire   [2:0] select_ln21_18_fu_436_p3;
wire   [1:0] j_fu_290_p1;
wire   [1:0] trunc_ln19_22_fu_507_p1;
wire   [16:0] v_15_fu_527_p3;
wire   [1:0] trunc_ln19_24_fu_534_p1;
wire   [0:0] icmp_ln24_7_fu_542_p2;
wire   [16:0] zext_ln24_7_fu_548_p1;
wire   [16:0] rounded_24_fu_552_p2;
wire   [15:0] b_im_fu_538_p1;
wire   [15:0] b_im_29_fu_568_p2;
wire   [15:0] b_im_6_fu_558_p4;
wire   [15:0] b_im_30_fu_574_p3;
wire   [14:0] select_ln28_fu_596_p3;
wire   [15:0] zext_ln28_fu_603_p1;
wire   [15:0] zext_ln26_fu_592_p1;
wire   [15:0] w_re_36_fu_607_p2;
wire   [15:0] zext_ln145_fu_588_p1;
wire   [15:0] w_re_37_fu_613_p3;
wire   [0:0] or_ln28_fu_627_p2;
wire   [14:0] w_re_39_fu_631_p3;
wire   [15:0] zext_ln145_1_fu_639_p1;
wire  signed [15:0] w_re_38_fu_620_p3;
wire   [15:0] b_im_31_fu_581_p3;
wire  signed [15:0] w_im_fu_643_p2;
wire   [1:0] trunc_ln19_fu_668_p1;
wire   [16:0] zext_ln24_5_fu_687_p1;
wire   [16:0] rounded_22_fu_690_p2;
wire   [15:0] a_im_6_fu_695_p4;
wire   [15:0] a_im_30_fu_705_p3;
wire   [16:0] v_14_fu_717_p3;
wire   [1:0] trunc_ln19_23_fu_724_p1;
wire   [0:0] icmp_ln24_6_fu_732_p2;
wire   [16:0] zext_ln24_6_fu_738_p1;
wire   [16:0] rounded_23_fu_742_p2;
wire   [15:0] b_re_fu_728_p1;
wire   [15:0] b_re_29_fu_758_p2;
wire   [15:0] b_re_6_fu_748_p4;
wire   [15:0] b_re_30_fu_763_p3;
wire  signed [15:0] b_re_31_fu_770_p3;
wire  signed [15:0] mul_ln151_fu_781_p0;
wire  signed [31:0] grp_fu_1047_p3;
wire   [15:0] a_im_31_fu_710_p3;
wire   [16:0] wb_im_s_fu_786_p4;
wire  signed [16:0] sext_ln159_fu_795_p1;
wire   [16:0] zext_ln24_4_fu_815_p1;
wire   [16:0] rounded_fu_818_p2;
wire   [15:0] a_re_6_fu_823_p4;
wire   [15:0] a_re_30_fu_833_p3;
wire  signed [15:0] mul_ln150_fu_845_p0;
wire  signed [15:0] mul_ln150_fu_845_p1;
wire  signed [31:0] grp_fu_1038_p3;
wire   [15:0] a_re_31_fu_838_p3;
wire   [16:0] wb_re_s_fu_849_p4;
wire  signed [16:0] sext_ln158_fu_858_p1;
wire   [7:0] top8_fu_881_p4;
wire   [0:0] tmp_30_fu_891_p3;
wire   [7:0] xor_ln67_8_fu_899_p2;
wire   [7:0] top8_22_fu_913_p4;
wire   [0:0] tmp_31_fu_922_p3;
wire   [7:0] xor_ln67_9_fu_929_p2;
wire   [7:0] top8_23_fu_943_p4;
wire   [0:0] tmp_32_fu_953_p3;
wire   [7:0] xor_ln67_10_fu_961_p2;
wire   [7:0] top8_24_fu_975_p4;
wire   [0:0] tmp_33_fu_984_p3;
wire   [7:0] xor_ln67_11_fu_991_p2;
wire   [7:0] select_ln67_10_fu_967_p3;
wire   [7:0] select_ln67_11_fu_997_p3;
wire   [7:0] or_ln166_9_fu_1005_p2;
wire   [7:0] select_ln67_9_fu_935_p3;
wire   [7:0] or_ln166_8_fu_1011_p2;
wire   [7:0] select_ln67_8_fu_905_p3;
wire   [7:0] or_ln166_10_fu_1017_p2;
wire  signed [15:0] grp_fu_1038_p1;
wire  signed [31:0] mul_ln150_fu_845_p2;
wire  signed [15:0] grp_fu_1047_p1;
wire  signed [31:0] mul_ln151_fu_781_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 or_mask_3_fu_118 = 8'd0;
#0 bfly_2_fu_122 = 10'd0;
#0 ap_done_reg = 1'b0;
end

fft_serial_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U19(
    .din0(mul_ln151_fu_781_p0),
    .din1(b_re_31_fu_770_p3),
    .dout(mul_ln151_fu_781_p2)
);

fft_serial_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U20(
    .din0(mul_ln150_fu_845_p0),
    .din1(mul_ln150_fu_845_p1),
    .dout(mul_ln150_fu_845_p2)
);

fft_serial_mac_mulsub_16s_16s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_mulsub_16s_16s_32s_32_3_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_im_fu_643_p2),
    .din1(grp_fu_1038_p1),
    .din2(mul_ln150_fu_845_p2),
    .ce(1'b1),
    .dout(grp_fu_1038_p3)
);

fft_serial_mac_muladd_16s_16s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_2_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_re_38_fu_620_p3),
    .din1(grp_fu_1047_p1),
    .din2(mul_ln151_fu_781_p2),
    .ce(1'b1),
    .dout(grp_fu_1047_p3)
);

fft_serial_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_274_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            bfly_2_fu_122 <= bfly_11_fu_280_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            bfly_2_fu_122 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            or_mask_3_fu_118 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            or_mask_3_fu_118 <= or_mask_fu_1023_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_im_29_reg_1192 <= a_im_29_fu_521_p2;
        a_im_reg_1182 <= a_im_fu_511_p1;
        icmp_ln24_5_reg_1187 <= icmp_ln24_5_fu_515_p2;
        sext_ln150_11_reg_1209 <= sext_ln150_11_fu_657_p1;
        sext_ln150_9_reg_1197 <= sext_ln150_9_fu_649_p1;
        v_13_reg_1177 <= v_13_fu_500_p3;
        zext_ln21_reg_1171[2 : 0] <= zext_ln21_fu_497_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_re_29_reg_1230 <= a_re_29_fu_682_p2;
        a_re_reg_1220 <= a_re_fu_672_p1;
        icmp_ln24_4_reg_1225 <= icmp_ln24_4_fu_676_p2;
        sext_ln150_8_reg_1235 <= sext_ln150_8_fu_777_p1;
        v_12_reg_1215 <= v_12_fu_661_p3;
        v_42_reg_1240 <= v_42_fu_799_p2;
        v_44_reg_1246 <= v_44_fu_807_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln126_reg_1071 <= icmp_ln126_fu_274_p2;
        icmp_ln21_14_reg_1098 <= icmp_ln21_14_fu_452_p2;
        icmp_ln21_15_reg_1106 <= icmp_ln21_15_fu_458_p2;
        icmp_ln28_1_reg_1160 <= icmp_ln28_1_fu_480_p2;
        icmp_ln28_2_reg_1166 <= icmp_ln28_2_fu_486_p2;
        icmp_ln28_reg_1154 <= icmp_ln28_fu_474_p2;
        im_1_addr_4_reg_1119[0] <= zext_ln134_fu_322_p1[0];
im_1_addr_4_reg_1119[8 : 2] <= zext_ln134_fu_322_p1[8 : 2];
        im_1_addr_5_reg_1139[0] <= zext_ln135_fu_336_p1[0];
im_1_addr_5_reg_1139[8 : 2] <= zext_ln135_fu_336_p1[8 : 2];
        im_addr_4_reg_1114[0] <= zext_ln134_fu_322_p1[0];
im_addr_4_reg_1114[8 : 2] <= zext_ln134_fu_322_p1[8 : 2];
        im_addr_5_reg_1134[0] <= zext_ln135_fu_336_p1[0];
im_addr_5_reg_1134[8 : 2] <= zext_ln135_fu_336_p1[8 : 2];
        re_1_addr_4_reg_1088[0] <= zext_ln134_fu_322_p1[0];
re_1_addr_4_reg_1088[8 : 2] <= zext_ln134_fu_322_p1[8 : 2];
        re_1_addr_5_reg_1129[0] <= zext_ln135_fu_336_p1[0];
re_1_addr_5_reg_1129[8 : 2] <= zext_ln135_fu_336_p1[8 : 2];
        re_addr_4_reg_1083[0] <= zext_ln134_fu_322_p1[0];
re_addr_4_reg_1083[8 : 2] <= zext_ln134_fu_322_p1[8 : 2];
        re_addr_5_reg_1124[0] <= zext_ln135_fu_336_p1[0];
re_addr_5_reg_1124[8 : 2] <= zext_ln135_fu_336_p1[8 : 2];
        select_ln21_19_reg_1093 <= select_ln21_19_fu_444_p3;
        trunc_ln126_reg_1075 <= trunc_ln126_fu_286_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW_COS_LUT_ce0 = 1'b1;
    end else begin
        TW_COS_LUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW_SIN_LUT_ce0 = 1'b1;
    end else begin
        TW_SIN_LUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln126_fu_274_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_bfly = 10'd0;
    end else begin
        ap_sig_allocacmp_bfly = bfly_2_fu_122;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            im_1_address0 = im_1_addr_5_reg_1139;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            im_1_address0 = zext_ln135_fu_336_p1;
        end else begin
            im_1_address0 = 'bx;
        end
    end else begin
        im_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            im_1_address1 = im_1_addr_4_reg_1119;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            im_1_address1 = zext_ln134_fu_322_p1;
        end else begin
            im_1_address1 = 'bx;
        end
    end else begin
        im_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_1_ce0 = 1'b1;
    end else begin
        im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_1_ce1 = 1'b1;
    end else begin
        im_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (trunc_ln126_reg_1075 == 1'd1) & (icmp_ln126_reg_1071 == 1'd0))) begin
        im_1_we0 = 1'b1;
    end else begin
        im_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (trunc_ln126_reg_1075 == 1'd1) & (icmp_ln126_reg_1071 == 1'd0))) begin
        im_1_we1 = 1'b1;
    end else begin
        im_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            im_address0 = im_addr_5_reg_1134;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            im_address0 = zext_ln135_fu_336_p1;
        end else begin
            im_address0 = 'bx;
        end
    end else begin
        im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            im_address1 = im_addr_4_reg_1114;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            im_address1 = zext_ln134_fu_322_p1;
        end else begin
            im_address1 = 'bx;
        end
    end else begin
        im_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_ce0 = 1'b1;
    end else begin
        im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_ce1 = 1'b1;
    end else begin
        im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (trunc_ln126_reg_1075 == 1'd0) & (icmp_ln126_reg_1071 == 1'd0))) begin
        im_we0 = 1'b1;
    end else begin
        im_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (trunc_ln126_reg_1075 == 1'd0) & (icmp_ln126_reg_1071 == 1'd0))) begin
        im_we1 = 1'b1;
    end else begin
        im_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln126_fu_274_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_mask_3_out_ap_vld = 1'b1;
    end else begin
        or_mask_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_1_ce0 = 1'b1;
    end else begin
        re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_1_ce1 = 1'b1;
    end else begin
        re_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln126_reg_1075 == 1'd1))) begin
        re_1_we0 = 1'b1;
    end else begin
        re_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln126_reg_1075 == 1'd1))) begin
        re_1_we1 = 1'b1;
    end else begin
        re_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_ce0 = 1'b1;
    end else begin
        re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_ce1 = 1'b1;
    end else begin
        re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln126_reg_1075 == 1'd0))) begin
        re_we0 = 1'b1;
    end else begin
        re_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln126_reg_1075 == 1'd0))) begin
        re_we1 = 1'b1;
    end else begin
        re_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign TW_COS_LUT_address0 = select_ln25_fu_464_p3;

assign TW_SIN_LUT_address0 = select_ln25_fu_464_p3;

assign a_im_29_fu_521_p2 = a_im_fu_511_p1 << zext_ln21_fu_497_p1;

assign a_im_30_fu_705_p3 = ((icmp_ln21_14_reg_1098[0:0] == 1'b1) ? a_im_reg_1182 : a_im_29_reg_1192);

assign a_im_31_fu_710_p3 = ((icmp_ln21_15_reg_1106[0:0] == 1'b1) ? a_im_6_fu_695_p4 : a_im_30_fu_705_p3);

assign a_im_6_fu_695_p4 = {{rounded_22_fu_690_p2[16:1]}};

assign a_im_fu_511_p1 = v_13_fu_500_p3[15:0];

assign a_re_29_fu_682_p2 = a_re_fu_672_p1 << zext_ln21_reg_1171;

assign a_re_30_fu_833_p3 = ((icmp_ln21_14_reg_1098[0:0] == 1'b1) ? a_re_reg_1220 : a_re_29_reg_1230);

assign a_re_31_fu_838_p3 = ((icmp_ln21_15_reg_1106[0:0] == 1'b1) ? a_re_6_fu_823_p4 : a_re_30_fu_833_p3);

assign a_re_6_fu_823_p4 = {{rounded_fu_818_p2[16:1]}};

assign a_re_fu_672_p1 = v_12_fu_661_p3[15:0];

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_im_29_fu_568_p2 = b_im_fu_538_p1 << zext_ln21_fu_497_p1;

assign b_im_30_fu_574_p3 = ((icmp_ln21_14_reg_1098[0:0] == 1'b1) ? b_im_fu_538_p1 : b_im_29_fu_568_p2);

assign b_im_31_fu_581_p3 = ((icmp_ln21_15_reg_1106[0:0] == 1'b1) ? b_im_6_fu_558_p4 : b_im_30_fu_574_p3);

assign b_im_6_fu_558_p4 = {{rounded_24_fu_552_p2[16:1]}};

assign b_im_fu_538_p1 = v_15_fu_527_p3[15:0];

assign b_re_29_fu_758_p2 = b_re_fu_728_p1 << zext_ln21_reg_1171;

assign b_re_30_fu_763_p3 = ((icmp_ln21_14_reg_1098[0:0] == 1'b1) ? b_re_fu_728_p1 : b_re_29_fu_758_p2);

assign b_re_31_fu_770_p3 = ((icmp_ln21_15_reg_1106[0:0] == 1'b1) ? b_re_6_fu_748_p4 : b_re_30_fu_763_p3);

assign b_re_6_fu_748_p4 = {{rounded_23_fu_742_p2[16:1]}};

assign b_re_fu_728_p1 = v_14_fu_717_p3[15:0];

assign bfly_11_fu_280_p2 = (ap_sig_allocacmp_bfly + 10'd1);

assign grp_fu_1038_p1 = sext_ln150_10_fu_653_p1;

assign grp_fu_1047_p1 = sext_ln150_10_fu_653_p1;

assign icmp_ln126_fu_274_p2 = ((ap_sig_allocacmp_bfly == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln21_10_fu_356_p2 = ((clz_next_2 == 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln21_11_fu_362_p2 = ((clz_next_2 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln21_12_fu_368_p2 = ((clz_next_2 == 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln21_13_fu_374_p2 = ((clz_next_2 == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln21_14_fu_452_p2 = ((clz_next_2 == 4'd1) ? 1'b1 : 1'b0);

assign icmp_ln21_15_fu_458_p2 = ((clz_next_2 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln21_8_fu_344_p2 = ((clz_next_2 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln21_9_fu_350_p2 = ((clz_next_2 == 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln24_4_fu_676_p2 = ((trunc_ln19_fu_668_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_5_fu_515_p2 = ((trunc_ln19_22_fu_507_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_6_fu_732_p2 = ((trunc_ln19_23_fu_724_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_7_fu_542_p2 = ((trunc_ln19_24_fu_534_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln28_1_fu_480_p2 = ((j_fu_290_p1 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln28_2_fu_486_p2 = ((j_fu_290_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_474_p2 = ((j_fu_290_p1 == 2'd2) ? 1'b1 : 1'b0);

assign im_1_d0 = v_44_fu_807_p2;

assign im_1_d1 = v_42_fu_799_p2;

assign im_d0 = v_44_fu_807_p2;

assign im_d1 = v_42_fu_799_p2;

assign j_fu_290_p1 = ap_sig_allocacmp_bfly[1:0];

assign lshr_ln_fu_312_p4 = {{{tmp_6_fu_294_p4}, {1'd0}}, {tmp_fu_304_p3}};

assign mul_ln150_fu_845_p0 = sext_ln150_9_reg_1197;

assign mul_ln150_fu_845_p1 = sext_ln150_8_reg_1235;

assign mul_ln151_fu_781_p0 = sext_ln150_11_reg_1209;

assign or_ln135_fu_330_p2 = (lshr_ln_fu_312_p4 | 9'd2);

assign or_ln166_10_fu_1017_p2 = (select_ln67_8_fu_905_p3 | or_ln166_8_fu_1011_p2);

assign or_ln166_8_fu_1011_p2 = (select_ln67_9_fu_935_p3 | or_ln166_9_fu_1005_p2);

assign or_ln166_9_fu_1005_p2 = (select_ln67_11_fu_997_p3 | select_ln67_10_fu_967_p3);

assign or_ln21_4_fu_388_p2 = (icmp_ln21_13_fu_374_p2 | icmp_ln21_12_fu_368_p2);

assign or_ln21_5_fu_402_p2 = (icmp_ln21_11_fu_362_p2 | icmp_ln21_10_fu_356_p2);

assign or_ln21_6_fu_416_p2 = (icmp_ln21_9_fu_350_p2 | icmp_ln21_8_fu_344_p2);

assign or_ln21_7_fu_430_p2 = (or_ln21_5_fu_402_p2 | or_ln21_4_fu_388_p2);

assign or_ln28_fu_627_p2 = (icmp_ln28_reg_1154 | icmp_ln28_1_reg_1160);

assign or_mask_3_out = or_mask_3_fu_118;

assign or_mask_fu_1023_p2 = (or_mask_3_fu_118 | or_ln166_10_fu_1017_p2);

assign re_1_address0 = re_1_addr_5_reg_1129;

assign re_1_address1 = re_1_addr_4_reg_1088;

assign re_1_d0 = v_43_fu_870_p2;

assign re_1_d1 = v_fu_862_p2;

assign re_address0 = re_addr_5_reg_1124;

assign re_address1 = re_addr_4_reg_1083;

assign re_d0 = v_43_fu_870_p2;

assign re_d1 = v_fu_862_p2;

assign rounded_22_fu_690_p2 = (v_13_reg_1177 + zext_ln24_5_fu_687_p1);

assign rounded_23_fu_742_p2 = (v_14_fu_717_p3 + zext_ln24_6_fu_738_p1);

assign rounded_24_fu_552_p2 = (v_15_fu_527_p3 + zext_ln24_7_fu_548_p1);

assign rounded_fu_818_p2 = (v_12_reg_1215 + zext_ln24_4_fu_815_p1);

assign select_ln21_15_fu_394_p3 = ((icmp_ln21_11_fu_362_p2[0:0] == 1'b1) ? 3'd3 : 3'd4);

assign select_ln21_16_fu_408_p3 = ((icmp_ln21_9_fu_350_p2[0:0] == 1'b1) ? 3'd5 : 3'd6);

assign select_ln21_17_fu_422_p3 = ((or_ln21_4_fu_388_p2[0:0] == 1'b1) ? select_ln21_fu_380_p3 : select_ln21_15_fu_394_p3);

assign select_ln21_18_fu_436_p3 = ((or_ln21_6_fu_416_p2[0:0] == 1'b1) ? select_ln21_16_fu_408_p3 : 3'd7);

assign select_ln21_19_fu_444_p3 = ((or_ln21_7_fu_430_p2[0:0] == 1'b1) ? select_ln21_17_fu_422_p3 : select_ln21_18_fu_436_p3);

assign select_ln21_fu_380_p3 = ((icmp_ln21_13_fu_374_p2[0:0] == 1'b1) ? 3'd1 : 3'd2);

assign select_ln25_fu_464_p3 = ((trunc_ln126_fu_286_p1[0:0] == 1'b1) ? 64'd128 : 64'd0);

assign select_ln28_fu_596_p3 = ((icmp_ln28_reg_1154[0:0] == 1'b1) ? TW_SIN_LUT_q0 : TW_COS_LUT_q0);

assign select_ln67_10_fu_967_p3 = ((tmp_32_fu_953_p3[0:0] == 1'b1) ? xor_ln67_10_fu_961_p2 : top8_23_fu_943_p4);

assign select_ln67_11_fu_997_p3 = ((tmp_33_fu_984_p3[0:0] == 1'b1) ? xor_ln67_11_fu_991_p2 : top8_24_fu_975_p4);

assign select_ln67_8_fu_905_p3 = ((tmp_30_fu_891_p3[0:0] == 1'b1) ? xor_ln67_8_fu_899_p2 : top8_fu_881_p4);

assign select_ln67_9_fu_935_p3 = ((tmp_31_fu_922_p3[0:0] == 1'b1) ? xor_ln67_9_fu_929_p2 : top8_22_fu_913_p4);

assign sext_ln150_10_fu_653_p1 = $signed(b_im_31_fu_581_p3);

assign sext_ln150_11_fu_657_p1 = w_im_fu_643_p2;

assign sext_ln150_8_fu_777_p1 = b_re_31_fu_770_p3;

assign sext_ln150_9_fu_649_p1 = w_re_38_fu_620_p3;

assign sext_ln158_fu_858_p1 = $signed(a_re_31_fu_838_p3);

assign sext_ln159_fu_795_p1 = $signed(a_im_31_fu_710_p3);

assign tmp_30_fu_891_p3 = v_fu_862_p2[32'd16];

assign tmp_31_fu_922_p3 = v_42_reg_1240[32'd16];

assign tmp_32_fu_953_p3 = v_43_fu_870_p2[32'd16];

assign tmp_33_fu_984_p3 = v_44_reg_1246[32'd16];

assign tmp_6_fu_294_p4 = {{ap_sig_allocacmp_bfly[8:2]}};

assign tmp_fu_304_p3 = ap_sig_allocacmp_bfly[32'd1];

assign top8_22_fu_913_p4 = {{v_42_reg_1240[15:8]}};

assign top8_23_fu_943_p4 = {{v_43_fu_870_p2[15:8]}};

assign top8_24_fu_975_p4 = {{v_44_reg_1246[15:8]}};

assign top8_fu_881_p4 = {{v_fu_862_p2[15:8]}};

assign trunc_ln126_fu_286_p1 = ap_sig_allocacmp_bfly[0:0];

assign trunc_ln19_22_fu_507_p1 = v_13_fu_500_p3[1:0];

assign trunc_ln19_23_fu_724_p1 = v_14_fu_717_p3[1:0];

assign trunc_ln19_24_fu_534_p1 = v_15_fu_527_p3[1:0];

assign trunc_ln19_fu_668_p1 = v_12_fu_661_p3[1:0];

assign v_12_fu_661_p3 = ((trunc_ln126_reg_1075[0:0] == 1'b1) ? re_1_q1 : re_q1);

assign v_13_fu_500_p3 = ((trunc_ln126_reg_1075[0:0] == 1'b1) ? im_1_q1 : im_q1);

assign v_14_fu_717_p3 = ((trunc_ln126_reg_1075[0:0] == 1'b1) ? re_1_q0 : re_q0);

assign v_15_fu_527_p3 = ((trunc_ln126_reg_1075[0:0] == 1'b1) ? im_1_q0 : im_q0);

assign v_42_fu_799_p2 = ($signed(wb_im_s_fu_786_p4) + $signed(sext_ln159_fu_795_p1));

assign v_43_fu_870_p2 = ($signed(sext_ln158_fu_858_p1) - $signed(wb_re_s_fu_849_p4));

assign v_44_fu_807_p2 = ($signed(sext_ln159_fu_795_p1) - $signed(wb_im_s_fu_786_p4));

assign v_fu_862_p2 = ($signed(wb_re_s_fu_849_p4) + $signed(sext_ln158_fu_858_p1));

assign w_im_fu_643_p2 = (zext_ln145_1_fu_639_p1 ^ 16'd65535);

assign w_re_36_fu_607_p2 = (zext_ln28_fu_603_p1 ^ 16'd65535);

assign w_re_37_fu_613_p3 = ((icmp_ln28_1_reg_1160[0:0] == 1'b1) ? zext_ln26_fu_592_p1 : w_re_36_fu_607_p2);

assign w_re_38_fu_620_p3 = ((icmp_ln28_2_reg_1166[0:0] == 1'b1) ? zext_ln145_fu_588_p1 : w_re_37_fu_613_p3);

assign w_re_39_fu_631_p3 = ((or_ln28_fu_627_p2[0:0] == 1'b1) ? TW_COS_LUT_q0 : TW_SIN_LUT_q0);

assign wb_im_s_fu_786_p4 = {{grp_fu_1047_p3[31:15]}};

assign wb_re_s_fu_849_p4 = {{grp_fu_1038_p3[31:15]}};

assign xor_ln67_10_fu_961_p2 = (top8_23_fu_943_p4 ^ 8'd255);

assign xor_ln67_11_fu_991_p2 = (top8_24_fu_975_p4 ^ 8'd255);

assign xor_ln67_8_fu_899_p2 = (top8_fu_881_p4 ^ 8'd255);

assign xor_ln67_9_fu_929_p2 = (top8_22_fu_913_p4 ^ 8'd255);

assign zext_ln134_fu_322_p1 = lshr_ln_fu_312_p4;

assign zext_ln135_fu_336_p1 = or_ln135_fu_330_p2;

assign zext_ln145_1_fu_639_p1 = w_re_39_fu_631_p3;

assign zext_ln145_fu_588_p1 = TW_COS_LUT_q0;

assign zext_ln21_fu_497_p1 = select_ln21_19_reg_1093;

assign zext_ln24_4_fu_815_p1 = icmp_ln24_4_reg_1225;

assign zext_ln24_5_fu_687_p1 = icmp_ln24_5_reg_1187;

assign zext_ln24_6_fu_738_p1 = icmp_ln24_6_fu_732_p2;

assign zext_ln24_7_fu_548_p1 = icmp_ln24_7_fu_542_p2;

assign zext_ln26_fu_592_p1 = TW_SIN_LUT_q0;

assign zext_ln28_fu_603_p1 = select_ln28_fu_596_p3;

always @ (posedge ap_clk) begin
    re_addr_4_reg_1083[1] <= 1'b0;
    re_1_addr_4_reg_1088[1] <= 1'b0;
    im_addr_4_reg_1114[1] <= 1'b0;
    im_1_addr_4_reg_1119[1] <= 1'b0;
    re_addr_5_reg_1124[1] <= 1'b1;
    re_1_addr_5_reg_1129[1] <= 1'b1;
    im_addr_5_reg_1134[1] <= 1'b1;
    im_1_addr_5_reg_1139[1] <= 1'b1;
    zext_ln21_reg_1171[15:3] <= 13'b0000000000000;
end

endmodule //fft_serial_fft_serial_Pipeline_bfly_loop2
