// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_serial_fft_serial_Pipeline_bfly_loop8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        re_address0,
        re_ce0,
        re_we0,
        re_d0,
        re_q0,
        re_address1,
        re_ce1,
        re_we1,
        re_d1,
        re_q1,
        re_1_address0,
        re_1_ce0,
        re_1_we0,
        re_1_d0,
        re_1_q0,
        re_1_address1,
        re_1_ce1,
        re_1_we1,
        re_1_d1,
        re_1_q1,
        clz_next_8,
        im_address0,
        im_ce0,
        im_we0,
        im_d0,
        im_q0,
        im_address1,
        im_ce1,
        im_we1,
        im_d1,
        im_q1,
        im_1_address0,
        im_1_ce0,
        im_1_we0,
        im_1_d0,
        im_1_q0,
        im_1_address1,
        im_1_ce1,
        im_1_we1,
        im_1_d1,
        im_1_q1,
        or_mask_15_out,
        or_mask_15_out_ap_vld,
        TW_COS_LUT_address0,
        TW_COS_LUT_ce0,
        TW_COS_LUT_q0,
        TW_SIN_LUT_address0,
        TW_SIN_LUT_ce0,
        TW_SIN_LUT_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] re_address0;
output   re_ce0;
output   re_we0;
output  [16:0] re_d0;
input  [16:0] re_q0;
output  [8:0] re_address1;
output   re_ce1;
output   re_we1;
output  [16:0] re_d1;
input  [16:0] re_q1;
output  [8:0] re_1_address0;
output   re_1_ce0;
output   re_1_we0;
output  [16:0] re_1_d0;
input  [16:0] re_1_q0;
output  [8:0] re_1_address1;
output   re_1_ce1;
output   re_1_we1;
output  [16:0] re_1_d1;
input  [16:0] re_1_q1;
input  [3:0] clz_next_8;
output  [8:0] im_address0;
output   im_ce0;
output   im_we0;
output  [16:0] im_d0;
input  [16:0] im_q0;
output  [8:0] im_address1;
output   im_ce1;
output   im_we1;
output  [16:0] im_d1;
input  [16:0] im_q1;
output  [8:0] im_1_address0;
output   im_1_ce0;
output   im_1_we0;
output  [16:0] im_1_d0;
input  [16:0] im_1_q0;
output  [8:0] im_1_address1;
output   im_1_ce1;
output   im_1_we1;
output  [16:0] im_1_d1;
input  [16:0] im_1_q1;
output  [7:0] or_mask_15_out;
output   or_mask_15_out_ap_vld;
output  [7:0] TW_COS_LUT_address0;
output   TW_COS_LUT_ce0;
input  [14:0] TW_COS_LUT_q0;
output  [7:0] TW_SIN_LUT_address0;
output   TW_SIN_LUT_ce0;
input  [14:0] TW_SIN_LUT_q0;

reg ap_idle;
reg re_ce0;
reg re_we0;
reg re_ce1;
reg re_we1;
reg re_1_ce0;
reg re_1_we0;
reg re_1_ce1;
reg re_1_we1;
reg[8:0] im_address0;
reg im_ce0;
reg im_we0;
reg[8:0] im_address1;
reg im_ce1;
reg im_we1;
reg[8:0] im_1_address0;
reg im_1_ce0;
reg im_1_we0;
reg[8:0] im_1_address1;
reg im_1_ce1;
reg im_1_we1;
reg or_mask_15_out_ap_vld;
reg TW_COS_LUT_ce0;
reg TW_SIN_LUT_ce0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln126_fu_282_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln126_reg_1119;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln126_fu_294_p1;
reg   [0:0] trunc_ln126_reg_1123;
reg   [8:0] re_addr_reg_1131;
reg   [8:0] re_1_addr_reg_1136;
wire   [2:0] select_ln21_18_fu_460_p3;
reg   [2:0] select_ln21_18_reg_1141;
wire   [0:0] icmp_ln21_13_fu_468_p2;
reg   [0:0] icmp_ln21_13_reg_1146;
wire   [0:0] icmp_ln21_14_fu_474_p2;
reg   [0:0] icmp_ln21_14_reg_1154;
reg   [8:0] im_addr_reg_1162;
reg   [8:0] im_1_addr_reg_1167;
reg   [8:0] re_addr_2_reg_1172;
reg   [8:0] re_1_addr_2_reg_1177;
reg   [8:0] im_addr_2_reg_1182;
reg   [8:0] im_1_addr_2_reg_1187;
wire   [0:0] icmp_ln28_fu_522_p2;
reg   [0:0] icmp_ln28_reg_1202;
wire   [0:0] icmp_ln28_3_fu_528_p2;
reg   [0:0] icmp_ln28_3_reg_1208;
wire   [0:0] icmp_ln28_4_fu_534_p2;
reg   [0:0] icmp_ln28_4_reg_1214;
wire   [15:0] zext_ln21_fu_545_p1;
reg   [15:0] zext_ln21_reg_1219;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [16:0] v_8_fu_548_p3;
reg   [16:0] v_8_reg_1225;
wire   [15:0] a_im_5_fu_559_p1;
reg   [15:0] a_im_5_reg_1230;
wire   [0:0] icmp_ln24_4_fu_563_p2;
reg   [0:0] icmp_ln24_4_reg_1235;
wire   [15:0] a_im_6_fu_569_p2;
reg   [15:0] a_im_6_reg_1240;
wire  signed [31:0] sext_ln150_4_fu_697_p1;
reg  signed [31:0] sext_ln150_4_reg_1245;
wire  signed [31:0] sext_ln150_5_fu_701_p1;
wire  signed [31:0] sext_ln150_6_fu_705_p1;
reg  signed [31:0] sext_ln150_6_reg_1257;
wire   [16:0] v_fu_709_p3;
reg   [16:0] v_reg_1263;
wire    ap_block_pp0_stage2_11001;
wire   [15:0] a_re_5_fu_720_p1;
reg   [15:0] a_re_5_reg_1268;
wire   [0:0] icmp_ln24_fu_724_p2;
reg   [0:0] icmp_ln24_reg_1273;
wire   [15:0] a_re_6_fu_730_p2;
reg   [15:0] a_re_6_reg_1278;
wire  signed [31:0] sext_ln150_fu_825_p1;
reg  signed [31:0] sext_ln150_reg_1283;
wire   [16:0] v_12_fu_847_p2;
reg   [16:0] v_12_reg_1288;
wire   [16:0] v_14_fu_855_p2;
reg   [16:0] v_14_reg_1294;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln134_fu_326_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln135_fu_340_p1;
wire   [63:0] zext_ln25_fu_516_p1;
reg   [7:0] or_mask_fu_126;
wire   [7:0] or_mask_2_fu_1071_p2;
wire    ap_loop_init;
reg   [9:0] bfly_1_fu_130;
wire   [9:0] bfly_2_fu_288_p2;
reg   [9:0] ap_sig_allocacmp_bfly;
wire    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage1;
wire   [16:0] v_11_fu_910_p2;
wire   [16:0] v_13_fu_918_p2;
wire   [0:0] tmp_fu_298_p3;
wire   [6:0] tmp_s_fu_306_p4;
wire   [8:0] lshr_ln134_6_fu_316_p4;
wire   [8:0] or_ln135_fu_334_p2;
wire   [5:0] trunc_ln136_fu_348_p1;
wire   [0:0] icmp_ln21_12_fu_390_p2;
wire   [0:0] icmp_ln21_11_fu_384_p2;
wire   [0:0] icmp_ln21_10_fu_378_p2;
wire   [0:0] icmp_ln21_9_fu_372_p2;
wire   [0:0] icmp_ln21_8_fu_366_p2;
wire   [0:0] icmp_ln21_fu_360_p2;
wire   [0:0] or_ln21_fu_404_p2;
wire   [2:0] select_ln21_fu_396_p3;
wire   [2:0] select_ln21_14_fu_410_p3;
wire   [0:0] or_ln21_4_fu_418_p2;
wire   [0:0] or_ln21_5_fu_432_p2;
wire   [2:0] select_ln21_15_fu_424_p3;
wire   [0:0] or_ln21_6_fu_446_p2;
wire   [2:0] select_ln21_16_fu_438_p3;
wire   [2:0] select_ln21_17_fu_452_p3;
wire   [6:0] tw_n_fu_352_p3;
wire   [7:0] zext_ln22_fu_498_p1;
wire   [0:0] tmp_5_fu_490_p3;
wire   [7:0] sub_ln23_fu_502_p2;
wire   [7:0] rom_addr_fu_508_p3;
wire   [1:0] trunc_ln21_s_fu_480_p4;
wire   [1:0] trunc_ln19_4_fu_555_p1;
wire   [16:0] v_10_fu_575_p3;
wire   [1:0] trunc_ln19_6_fu_582_p1;
wire   [0:0] icmp_ln24_6_fu_590_p2;
wire   [16:0] zext_ln24_6_fu_596_p1;
wire   [16:0] rounded_6_fu_600_p2;
wire   [15:0] b_im_5_fu_586_p1;
wire   [15:0] b_im_6_fu_616_p2;
wire   [15:0] b_im_fu_606_p4;
wire   [15:0] b_im_7_fu_622_p3;
wire   [14:0] select_ln28_fu_644_p3;
wire   [15:0] zext_ln28_fu_651_p1;
wire   [15:0] zext_ln26_fu_640_p1;
wire   [15:0] w_re_6_fu_655_p2;
wire   [15:0] zext_ln145_fu_636_p1;
wire   [15:0] w_re_7_fu_661_p3;
wire   [0:0] or_ln28_fu_675_p2;
wire   [14:0] w_re_9_fu_679_p3;
wire   [15:0] zext_ln145_2_fu_687_p1;
wire  signed [15:0] w_re_8_fu_668_p3;
wire   [15:0] b_im_8_fu_629_p3;
wire  signed [15:0] w_im_fu_691_p2;
wire   [1:0] trunc_ln19_fu_716_p1;
wire   [16:0] zext_ln24_4_fu_735_p1;
wire   [16:0] rounded_4_fu_738_p2;
wire   [15:0] a_im_fu_743_p4;
wire   [15:0] a_im_7_fu_753_p3;
wire   [16:0] v_9_fu_765_p3;
wire   [1:0] trunc_ln19_5_fu_772_p1;
wire   [0:0] icmp_ln24_5_fu_780_p2;
wire   [16:0] zext_ln24_5_fu_786_p1;
wire   [16:0] rounded_5_fu_790_p2;
wire   [15:0] b_re_5_fu_776_p1;
wire   [15:0] b_re_6_fu_806_p2;
wire   [15:0] b_re_fu_796_p4;
wire   [15:0] b_re_7_fu_811_p3;
wire  signed [15:0] b_re_8_fu_818_p3;
wire  signed [15:0] mul_ln151_fu_829_p0;
wire  signed [31:0] grp_fu_1095_p3;
wire   [15:0] a_im_8_fu_758_p3;
wire   [16:0] wb_im_s_fu_834_p4;
wire  signed [16:0] sext_ln159_fu_843_p1;
wire   [16:0] zext_ln24_fu_863_p1;
wire   [16:0] rounded_fu_866_p2;
wire   [15:0] a_re_fu_871_p4;
wire   [15:0] a_re_7_fu_881_p3;
wire  signed [15:0] mul_ln150_fu_893_p0;
wire  signed [15:0] mul_ln150_fu_893_p1;
wire  signed [31:0] grp_fu_1086_p3;
wire   [15:0] a_re_8_fu_886_p3;
wire   [16:0] wb_re_s_fu_897_p4;
wire  signed [16:0] sext_ln158_fu_906_p1;
wire   [7:0] top8_fu_929_p4;
wire   [0:0] tmp_6_fu_939_p3;
wire   [7:0] xor_ln67_fu_947_p2;
wire   [7:0] top8_4_fu_961_p4;
wire   [0:0] tmp_7_fu_970_p3;
wire   [7:0] xor_ln67_4_fu_977_p2;
wire   [7:0] top8_5_fu_991_p4;
wire   [0:0] tmp_8_fu_1001_p3;
wire   [7:0] xor_ln67_5_fu_1009_p2;
wire   [7:0] top8_6_fu_1023_p4;
wire   [0:0] tmp_9_fu_1032_p3;
wire   [7:0] xor_ln67_6_fu_1039_p2;
wire   [7:0] select_ln67_5_fu_1015_p3;
wire   [7:0] select_ln67_6_fu_1045_p3;
wire   [7:0] or_ln166_fu_1053_p2;
wire   [7:0] select_ln67_4_fu_983_p3;
wire   [7:0] or_ln166_4_fu_1059_p2;
wire   [7:0] select_ln67_fu_953_p3;
wire   [7:0] or_ln166_5_fu_1065_p2;
wire  signed [15:0] grp_fu_1086_p1;
wire  signed [31:0] mul_ln150_fu_893_p2;
wire  signed [15:0] grp_fu_1095_p1;
wire  signed [31:0] mul_ln151_fu_829_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 or_mask_fu_126 = 8'd0;
#0 bfly_1_fu_130 = 10'd0;
#0 ap_done_reg = 1'b0;
end

fft_serial_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U94(
    .din0(mul_ln151_fu_829_p0),
    .din1(b_re_8_fu_818_p3),
    .dout(mul_ln151_fu_829_p2)
);

fft_serial_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U95(
    .din0(mul_ln150_fu_893_p0),
    .din1(mul_ln150_fu_893_p1),
    .dout(mul_ln150_fu_893_p2)
);

fft_serial_mac_mulsub_16s_16s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_mulsub_16s_16s_32s_32_3_1_U96(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_im_fu_691_p2),
    .din1(grp_fu_1086_p1),
    .din2(mul_ln150_fu_893_p2),
    .ce(1'b1),
    .dout(grp_fu_1086_p3)
);

fft_serial_mac_muladd_16s_16s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_2_1_U97(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_re_8_fu_668_p3),
    .din1(grp_fu_1095_p1),
    .din2(mul_ln151_fu_829_p2),
    .ce(1'b1),
    .dout(grp_fu_1095_p3)
);

fft_serial_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_282_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            bfly_1_fu_130 <= bfly_2_fu_288_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            bfly_1_fu_130 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            or_mask_fu_126 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            or_mask_fu_126 <= or_mask_2_fu_1071_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_im_5_reg_1230 <= a_im_5_fu_559_p1;
        a_im_6_reg_1240 <= a_im_6_fu_569_p2;
        icmp_ln24_4_reg_1235 <= icmp_ln24_4_fu_563_p2;
        sext_ln150_4_reg_1245 <= sext_ln150_4_fu_697_p1;
        sext_ln150_6_reg_1257 <= sext_ln150_6_fu_705_p1;
        v_8_reg_1225 <= v_8_fu_548_p3;
        zext_ln21_reg_1219[2 : 0] <= zext_ln21_fu_545_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_re_5_reg_1268 <= a_re_5_fu_720_p1;
        a_re_6_reg_1278 <= a_re_6_fu_730_p2;
        icmp_ln24_reg_1273 <= icmp_ln24_fu_724_p2;
        sext_ln150_reg_1283 <= sext_ln150_fu_825_p1;
        v_12_reg_1288 <= v_12_fu_847_p2;
        v_14_reg_1294 <= v_14_fu_855_p2;
        v_reg_1263 <= v_fu_709_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln126_reg_1119 <= icmp_ln126_fu_282_p2;
        icmp_ln21_13_reg_1146 <= icmp_ln21_13_fu_468_p2;
        icmp_ln21_14_reg_1154 <= icmp_ln21_14_fu_474_p2;
        icmp_ln28_3_reg_1208 <= icmp_ln28_3_fu_528_p2;
        icmp_ln28_4_reg_1214 <= icmp_ln28_4_fu_534_p2;
        icmp_ln28_reg_1202 <= icmp_ln28_fu_522_p2;
        im_1_addr_2_reg_1187[6 : 0] <= zext_ln135_fu_340_p1[6 : 0];
im_1_addr_2_reg_1187[8] <= zext_ln135_fu_340_p1[8];
        im_1_addr_reg_1167[6 : 0] <= zext_ln134_fu_326_p1[6 : 0];
im_1_addr_reg_1167[8] <= zext_ln134_fu_326_p1[8];
        im_addr_2_reg_1182[6 : 0] <= zext_ln135_fu_340_p1[6 : 0];
im_addr_2_reg_1182[8] <= zext_ln135_fu_340_p1[8];
        im_addr_reg_1162[6 : 0] <= zext_ln134_fu_326_p1[6 : 0];
im_addr_reg_1162[8] <= zext_ln134_fu_326_p1[8];
        re_1_addr_2_reg_1177[6 : 0] <= zext_ln135_fu_340_p1[6 : 0];
re_1_addr_2_reg_1177[8] <= zext_ln135_fu_340_p1[8];
        re_1_addr_reg_1136[6 : 0] <= zext_ln134_fu_326_p1[6 : 0];
re_1_addr_reg_1136[8] <= zext_ln134_fu_326_p1[8];
        re_addr_2_reg_1172[6 : 0] <= zext_ln135_fu_340_p1[6 : 0];
re_addr_2_reg_1172[8] <= zext_ln135_fu_340_p1[8];
        re_addr_reg_1131[6 : 0] <= zext_ln134_fu_326_p1[6 : 0];
re_addr_reg_1131[8] <= zext_ln134_fu_326_p1[8];
        select_ln21_18_reg_1141 <= select_ln21_18_fu_460_p3;
        trunc_ln126_reg_1123 <= trunc_ln126_fu_294_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW_COS_LUT_ce0 = 1'b1;
    end else begin
        TW_COS_LUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW_SIN_LUT_ce0 = 1'b1;
    end else begin
        TW_SIN_LUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln126_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_bfly = 10'd0;
    end else begin
        ap_sig_allocacmp_bfly = bfly_1_fu_130;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            im_1_address0 = im_1_addr_2_reg_1187;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            im_1_address0 = zext_ln135_fu_340_p1;
        end else begin
            im_1_address0 = 'bx;
        end
    end else begin
        im_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            im_1_address1 = im_1_addr_reg_1167;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            im_1_address1 = zext_ln134_fu_326_p1;
        end else begin
            im_1_address1 = 'bx;
        end
    end else begin
        im_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_1_ce0 = 1'b1;
    end else begin
        im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_1_ce1 = 1'b1;
    end else begin
        im_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (trunc_ln126_reg_1123 == 1'd1) & (icmp_ln126_reg_1119 == 1'd0))) begin
        im_1_we0 = 1'b1;
    end else begin
        im_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (trunc_ln126_reg_1123 == 1'd1) & (icmp_ln126_reg_1119 == 1'd0))) begin
        im_1_we1 = 1'b1;
    end else begin
        im_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            im_address0 = im_addr_2_reg_1182;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            im_address0 = zext_ln135_fu_340_p1;
        end else begin
            im_address0 = 'bx;
        end
    end else begin
        im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            im_address1 = im_addr_reg_1162;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            im_address1 = zext_ln134_fu_326_p1;
        end else begin
            im_address1 = 'bx;
        end
    end else begin
        im_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_ce0 = 1'b1;
    end else begin
        im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_ce1 = 1'b1;
    end else begin
        im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (trunc_ln126_reg_1123 == 1'd0) & (icmp_ln126_reg_1119 == 1'd0))) begin
        im_we0 = 1'b1;
    end else begin
        im_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (trunc_ln126_reg_1123 == 1'd0) & (icmp_ln126_reg_1119 == 1'd0))) begin
        im_we1 = 1'b1;
    end else begin
        im_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln126_fu_282_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_mask_15_out_ap_vld = 1'b1;
    end else begin
        or_mask_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_1_ce0 = 1'b1;
    end else begin
        re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_1_ce1 = 1'b1;
    end else begin
        re_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln126_reg_1123 == 1'd1))) begin
        re_1_we0 = 1'b1;
    end else begin
        re_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln126_reg_1123 == 1'd1))) begin
        re_1_we1 = 1'b1;
    end else begin
        re_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_ce0 = 1'b1;
    end else begin
        re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_ce1 = 1'b1;
    end else begin
        re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln126_reg_1123 == 1'd0))) begin
        re_we0 = 1'b1;
    end else begin
        re_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln126_reg_1123 == 1'd0))) begin
        re_we1 = 1'b1;
    end else begin
        re_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign TW_COS_LUT_address0 = zext_ln25_fu_516_p1;

assign TW_SIN_LUT_address0 = zext_ln25_fu_516_p1;

assign a_im_5_fu_559_p1 = v_8_fu_548_p3[15:0];

assign a_im_6_fu_569_p2 = a_im_5_fu_559_p1 << zext_ln21_fu_545_p1;

assign a_im_7_fu_753_p3 = ((icmp_ln21_13_reg_1146[0:0] == 1'b1) ? a_im_5_reg_1230 : a_im_6_reg_1240);

assign a_im_8_fu_758_p3 = ((icmp_ln21_14_reg_1154[0:0] == 1'b1) ? a_im_fu_743_p4 : a_im_7_fu_753_p3);

assign a_im_fu_743_p4 = {{rounded_4_fu_738_p2[16:1]}};

assign a_re_5_fu_720_p1 = v_fu_709_p3[15:0];

assign a_re_6_fu_730_p2 = a_re_5_fu_720_p1 << zext_ln21_reg_1219;

assign a_re_7_fu_881_p3 = ((icmp_ln21_13_reg_1146[0:0] == 1'b1) ? a_re_5_reg_1268 : a_re_6_reg_1278);

assign a_re_8_fu_886_p3 = ((icmp_ln21_14_reg_1154[0:0] == 1'b1) ? a_re_fu_871_p4 : a_re_7_fu_881_p3);

assign a_re_fu_871_p4 = {{rounded_fu_866_p2[16:1]}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_im_5_fu_586_p1 = v_10_fu_575_p3[15:0];

assign b_im_6_fu_616_p2 = b_im_5_fu_586_p1 << zext_ln21_fu_545_p1;

assign b_im_7_fu_622_p3 = ((icmp_ln21_13_reg_1146[0:0] == 1'b1) ? b_im_5_fu_586_p1 : b_im_6_fu_616_p2);

assign b_im_8_fu_629_p3 = ((icmp_ln21_14_reg_1154[0:0] == 1'b1) ? b_im_fu_606_p4 : b_im_7_fu_622_p3);

assign b_im_fu_606_p4 = {{rounded_6_fu_600_p2[16:1]}};

assign b_re_5_fu_776_p1 = v_9_fu_765_p3[15:0];

assign b_re_6_fu_806_p2 = b_re_5_fu_776_p1 << zext_ln21_reg_1219;

assign b_re_7_fu_811_p3 = ((icmp_ln21_13_reg_1146[0:0] == 1'b1) ? b_re_5_fu_776_p1 : b_re_6_fu_806_p2);

assign b_re_8_fu_818_p3 = ((icmp_ln21_14_reg_1154[0:0] == 1'b1) ? b_re_fu_796_p4 : b_re_7_fu_811_p3);

assign b_re_fu_796_p4 = {{rounded_5_fu_790_p2[16:1]}};

assign bfly_2_fu_288_p2 = (ap_sig_allocacmp_bfly + 10'd1);

assign grp_fu_1086_p1 = sext_ln150_5_fu_701_p1;

assign grp_fu_1095_p1 = sext_ln150_5_fu_701_p1;

assign icmp_ln126_fu_282_p2 = ((ap_sig_allocacmp_bfly == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln21_10_fu_378_p2 = ((clz_next_8 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln21_11_fu_384_p2 = ((clz_next_8 == 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln21_12_fu_390_p2 = ((clz_next_8 == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln21_13_fu_468_p2 = ((clz_next_8 == 4'd1) ? 1'b1 : 1'b0);

assign icmp_ln21_14_fu_474_p2 = ((clz_next_8 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln21_8_fu_366_p2 = ((clz_next_8 == 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln21_9_fu_372_p2 = ((clz_next_8 == 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_360_p2 = ((clz_next_8 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln24_4_fu_563_p2 = ((trunc_ln19_4_fu_555_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_5_fu_780_p2 = ((trunc_ln19_5_fu_772_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_6_fu_590_p2 = ((trunc_ln19_6_fu_582_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_724_p2 = ((trunc_ln19_fu_716_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln28_3_fu_528_p2 = ((trunc_ln21_s_fu_480_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln28_4_fu_534_p2 = ((trunc_ln21_s_fu_480_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_522_p2 = ((trunc_ln21_s_fu_480_p4 == 2'd2) ? 1'b1 : 1'b0);

assign im_1_d0 = v_14_fu_855_p2;

assign im_1_d1 = v_12_fu_847_p2;

assign im_d0 = v_14_fu_855_p2;

assign im_d1 = v_12_fu_847_p2;

assign lshr_ln134_6_fu_316_p4 = {{{tmp_fu_298_p3}, {1'd0}}, {tmp_s_fu_306_p4}};

assign mul_ln150_fu_893_p0 = sext_ln150_4_reg_1245;

assign mul_ln150_fu_893_p1 = sext_ln150_reg_1283;

assign mul_ln151_fu_829_p0 = sext_ln150_6_reg_1257;

assign or_ln135_fu_334_p2 = (lshr_ln134_6_fu_316_p4 | 9'd128);

assign or_ln166_4_fu_1059_p2 = (select_ln67_4_fu_983_p3 | or_ln166_fu_1053_p2);

assign or_ln166_5_fu_1065_p2 = (select_ln67_fu_953_p3 | or_ln166_4_fu_1059_p2);

assign or_ln166_fu_1053_p2 = (select_ln67_6_fu_1045_p3 | select_ln67_5_fu_1015_p3);

assign or_ln21_4_fu_418_p2 = (icmp_ln21_9_fu_372_p2 | icmp_ln21_10_fu_378_p2);

assign or_ln21_5_fu_432_p2 = (icmp_ln21_fu_360_p2 | icmp_ln21_8_fu_366_p2);

assign or_ln21_6_fu_446_p2 = (or_ln21_fu_404_p2 | or_ln21_4_fu_418_p2);

assign or_ln21_fu_404_p2 = (icmp_ln21_12_fu_390_p2 | icmp_ln21_11_fu_384_p2);

assign or_ln28_fu_675_p2 = (icmp_ln28_reg_1202 | icmp_ln28_3_reg_1208);

assign or_mask_15_out = or_mask_fu_126;

assign or_mask_2_fu_1071_p2 = (or_mask_fu_126 | or_ln166_5_fu_1065_p2);

assign re_1_address0 = re_1_addr_2_reg_1177;

assign re_1_address1 = re_1_addr_reg_1136;

assign re_1_d0 = v_13_fu_918_p2;

assign re_1_d1 = v_11_fu_910_p2;

assign re_address0 = re_addr_2_reg_1172;

assign re_address1 = re_addr_reg_1131;

assign re_d0 = v_13_fu_918_p2;

assign re_d1 = v_11_fu_910_p2;

assign rom_addr_fu_508_p3 = ((tmp_5_fu_490_p3[0:0] == 1'b1) ? sub_ln23_fu_502_p2 : zext_ln22_fu_498_p1);

assign rounded_4_fu_738_p2 = (v_8_reg_1225 + zext_ln24_4_fu_735_p1);

assign rounded_5_fu_790_p2 = (v_9_fu_765_p3 + zext_ln24_5_fu_786_p1);

assign rounded_6_fu_600_p2 = (v_10_fu_575_p3 + zext_ln24_6_fu_596_p1);

assign rounded_fu_866_p2 = (v_reg_1263 + zext_ln24_fu_863_p1);

assign select_ln21_14_fu_410_p3 = ((icmp_ln21_10_fu_378_p2[0:0] == 1'b1) ? 3'd3 : 3'd4);

assign select_ln21_15_fu_424_p3 = ((icmp_ln21_8_fu_366_p2[0:0] == 1'b1) ? 3'd5 : 3'd6);

assign select_ln21_16_fu_438_p3 = ((or_ln21_fu_404_p2[0:0] == 1'b1) ? select_ln21_fu_396_p3 : select_ln21_14_fu_410_p3);

assign select_ln21_17_fu_452_p3 = ((or_ln21_5_fu_432_p2[0:0] == 1'b1) ? select_ln21_15_fu_424_p3 : 3'd7);

assign select_ln21_18_fu_460_p3 = ((or_ln21_6_fu_446_p2[0:0] == 1'b1) ? select_ln21_16_fu_438_p3 : select_ln21_17_fu_452_p3);

assign select_ln21_fu_396_p3 = ((icmp_ln21_12_fu_390_p2[0:0] == 1'b1) ? 3'd1 : 3'd2);

assign select_ln28_fu_644_p3 = ((icmp_ln28_reg_1202[0:0] == 1'b1) ? TW_SIN_LUT_q0 : TW_COS_LUT_q0);

assign select_ln67_4_fu_983_p3 = ((tmp_7_fu_970_p3[0:0] == 1'b1) ? xor_ln67_4_fu_977_p2 : top8_4_fu_961_p4);

assign select_ln67_5_fu_1015_p3 = ((tmp_8_fu_1001_p3[0:0] == 1'b1) ? xor_ln67_5_fu_1009_p2 : top8_5_fu_991_p4);

assign select_ln67_6_fu_1045_p3 = ((tmp_9_fu_1032_p3[0:0] == 1'b1) ? xor_ln67_6_fu_1039_p2 : top8_6_fu_1023_p4);

assign select_ln67_fu_953_p3 = ((tmp_6_fu_939_p3[0:0] == 1'b1) ? xor_ln67_fu_947_p2 : top8_fu_929_p4);

assign sext_ln150_4_fu_697_p1 = w_re_8_fu_668_p3;

assign sext_ln150_5_fu_701_p1 = $signed(b_im_8_fu_629_p3);

assign sext_ln150_6_fu_705_p1 = w_im_fu_691_p2;

assign sext_ln150_fu_825_p1 = b_re_8_fu_818_p3;

assign sext_ln158_fu_906_p1 = $signed(a_re_8_fu_886_p3);

assign sext_ln159_fu_843_p1 = $signed(a_im_8_fu_758_p3);

assign sub_ln23_fu_502_p2 = ($signed(8'd128) - $signed(zext_ln22_fu_498_p1));

assign tmp_5_fu_490_p3 = ap_sig_allocacmp_bfly[32'd6];

assign tmp_6_fu_939_p3 = v_11_fu_910_p2[32'd16];

assign tmp_7_fu_970_p3 = v_12_reg_1288[32'd16];

assign tmp_8_fu_1001_p3 = v_13_fu_918_p2[32'd16];

assign tmp_9_fu_1032_p3 = v_14_reg_1294[32'd16];

assign tmp_fu_298_p3 = ap_sig_allocacmp_bfly[32'd8];

assign tmp_s_fu_306_p4 = {{ap_sig_allocacmp_bfly[7:1]}};

assign top8_4_fu_961_p4 = {{v_12_reg_1288[15:8]}};

assign top8_5_fu_991_p4 = {{v_13_fu_918_p2[15:8]}};

assign top8_6_fu_1023_p4 = {{v_14_reg_1294[15:8]}};

assign top8_fu_929_p4 = {{v_11_fu_910_p2[15:8]}};

assign trunc_ln126_fu_294_p1 = ap_sig_allocacmp_bfly[0:0];

assign trunc_ln136_fu_348_p1 = ap_sig_allocacmp_bfly[5:0];

assign trunc_ln19_4_fu_555_p1 = v_8_fu_548_p3[1:0];

assign trunc_ln19_5_fu_772_p1 = v_9_fu_765_p3[1:0];

assign trunc_ln19_6_fu_582_p1 = v_10_fu_575_p3[1:0];

assign trunc_ln19_fu_716_p1 = v_fu_709_p3[1:0];

assign trunc_ln21_s_fu_480_p4 = {{ap_sig_allocacmp_bfly[7:6]}};

assign tw_n_fu_352_p3 = {{trunc_ln136_fu_348_p1}, {1'd0}};

assign v_10_fu_575_p3 = ((trunc_ln126_reg_1123[0:0] == 1'b1) ? im_1_q0 : im_q0);

assign v_11_fu_910_p2 = ($signed(wb_re_s_fu_897_p4) + $signed(sext_ln158_fu_906_p1));

assign v_12_fu_847_p2 = ($signed(wb_im_s_fu_834_p4) + $signed(sext_ln159_fu_843_p1));

assign v_13_fu_918_p2 = ($signed(sext_ln158_fu_906_p1) - $signed(wb_re_s_fu_897_p4));

assign v_14_fu_855_p2 = ($signed(sext_ln159_fu_843_p1) - $signed(wb_im_s_fu_834_p4));

assign v_8_fu_548_p3 = ((trunc_ln126_reg_1123[0:0] == 1'b1) ? im_1_q1 : im_q1);

assign v_9_fu_765_p3 = ((trunc_ln126_reg_1123[0:0] == 1'b1) ? re_1_q0 : re_q0);

assign v_fu_709_p3 = ((trunc_ln126_reg_1123[0:0] == 1'b1) ? re_1_q1 : re_q1);

assign w_im_fu_691_p2 = (zext_ln145_2_fu_687_p1 ^ 16'd65535);

assign w_re_6_fu_655_p2 = (zext_ln28_fu_651_p1 ^ 16'd65535);

assign w_re_7_fu_661_p3 = ((icmp_ln28_3_reg_1208[0:0] == 1'b1) ? zext_ln26_fu_640_p1 : w_re_6_fu_655_p2);

assign w_re_8_fu_668_p3 = ((icmp_ln28_4_reg_1214[0:0] == 1'b1) ? zext_ln145_fu_636_p1 : w_re_7_fu_661_p3);

assign w_re_9_fu_679_p3 = ((or_ln28_fu_675_p2[0:0] == 1'b1) ? TW_COS_LUT_q0 : TW_SIN_LUT_q0);

assign wb_im_s_fu_834_p4 = {{grp_fu_1095_p3[31:15]}};

assign wb_re_s_fu_897_p4 = {{grp_fu_1086_p3[31:15]}};

assign xor_ln67_4_fu_977_p2 = (top8_4_fu_961_p4 ^ 8'd255);

assign xor_ln67_5_fu_1009_p2 = (top8_5_fu_991_p4 ^ 8'd255);

assign xor_ln67_6_fu_1039_p2 = (top8_6_fu_1023_p4 ^ 8'd255);

assign xor_ln67_fu_947_p2 = (top8_fu_929_p4 ^ 8'd255);

assign zext_ln134_fu_326_p1 = lshr_ln134_6_fu_316_p4;

assign zext_ln135_fu_340_p1 = or_ln135_fu_334_p2;

assign zext_ln145_2_fu_687_p1 = w_re_9_fu_679_p3;

assign zext_ln145_fu_636_p1 = TW_COS_LUT_q0;

assign zext_ln21_fu_545_p1 = select_ln21_18_reg_1141;

assign zext_ln22_fu_498_p1 = tw_n_fu_352_p3;

assign zext_ln24_4_fu_735_p1 = icmp_ln24_4_reg_1235;

assign zext_ln24_5_fu_786_p1 = icmp_ln24_5_fu_780_p2;

assign zext_ln24_6_fu_596_p1 = icmp_ln24_6_fu_590_p2;

assign zext_ln24_fu_863_p1 = icmp_ln24_reg_1273;

assign zext_ln25_fu_516_p1 = rom_addr_fu_508_p3;

assign zext_ln26_fu_640_p1 = TW_SIN_LUT_q0;

assign zext_ln28_fu_651_p1 = select_ln28_fu_644_p3;

always @ (posedge ap_clk) begin
    re_addr_reg_1131[7] <= 1'b0;
    re_1_addr_reg_1136[7] <= 1'b0;
    im_addr_reg_1162[7] <= 1'b0;
    im_1_addr_reg_1167[7] <= 1'b0;
    re_addr_2_reg_1172[7] <= 1'b1;
    re_1_addr_2_reg_1177[7] <= 1'b1;
    im_addr_2_reg_1182[7] <= 1'b1;
    im_1_addr_2_reg_1187[7] <= 1'b1;
    zext_ln21_reg_1219[15:3] <= 13'b0000000000000;
end

endmodule //fft_serial_fft_serial_Pipeline_bfly_loop8
