// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_mdf_Loop_VITIS_LOOP_95_1_proc717 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s6_dout,
        s6_num_data_valid,
        s6_fifo_cap,
        s6_empty_n,
        s6_read,
        s7_din,
        s7_num_data_valid,
        s7_fifo_cap,
        s7_full_n,
        s7_write,
        start_out,
        start_write
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [128:0] s6_dout;
input  [9:0] s6_num_data_valid;
input  [9:0] s6_fifo_cap;
input   s6_empty_n;
output   s6_read;
output  [128:0] s7_din;
input  [9:0] s7_num_data_valid;
input  [9:0] s7_fifo_cap;
input   s7_full_n;
output   s7_write;
output   start_out;
output   start_write;

reg ap_idle;
reg s6_read;
reg s7_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
reg   [1:0] ap_CS_iter5_fsm;
wire    ap_CS_iter5_fsm_state0;
wire    internal_ap_ready;
wire   [0:0] icmp_ln95_fu_207_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
wire    ap_CS_iter4_fsm_state5;
wire    ap_CS_iter3_fsm_state4;
wire    ap_CS_iter2_fsm_state3;
reg   [0:0] icmp_ln95_reg_1303;
reg   [0:0] icmp_ln95_reg_1303_pp0_iter4_reg;
reg    ap_block_state6_pp0_stage0_iter5;
wire    ap_CS_iter5_fsm_state6;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [15:0] void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_0;
reg   [15:0] void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_2_0;
reg   [15:0] void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_3_0;
reg   [15:0] void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_4_0;
reg   [15:0] void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_0;
reg   [15:0] void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_5_0;
reg   [15:0] void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_6_0;
reg   [15:0] void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_7_0;
reg    s7_blk_n;
reg    s6_blk_n;
reg   [0:0] icmp_ln95_reg_1303_pp0_iter1_reg;
reg   [0:0] icmp_ln95_reg_1303_pp0_iter2_reg;
reg   [0:0] icmp_ln95_reg_1303_pp0_iter3_reg;
wire   [0:0] trunc_ln95_fu_219_p1;
reg   [0:0] trunc_ln95_reg_1307;
wire   [0:0] trunc_ln95_reg_1307_pp0_iter0_reg;
reg   [0:0] trunc_ln95_reg_1307_pp0_iter1_reg;
reg   [0:0] trunc_ln95_reg_1307_pp0_iter2_reg;
reg   [0:0] trunc_ln95_reg_1307_pp0_iter3_reg;
reg   [0:0] y_last_reg_1311;
reg   [0:0] y_last_reg_1311_pp0_iter1_reg;
reg   [0:0] y_last_reg_1311_pp0_iter2_reg;
reg   [0:0] y_last_reg_1311_pp0_iter3_reg;
reg   [0:0] y_last_reg_1311_pp0_iter4_reg;
wire  signed [15:0] in_re_fu_231_p1;
reg  signed [15:0] in_re_reg_1316;
reg  signed [15:0] in_re_reg_1316_pp0_iter1_reg;
reg  signed [15:0] in_re_reg_1316_pp0_iter2_reg;
reg  signed [15:0] in_im_reg_1322;
reg  signed [15:0] in_im_reg_1322_pp0_iter1_reg;
reg  signed [15:0] in_im_reg_1322_pp0_iter2_reg;
reg  signed [15:0] in_re_1_reg_1328;
reg  signed [15:0] in_im_1_reg_1334;
reg  signed [15:0] in_im_1_reg_1334_pp0_iter1_reg;
reg  signed [15:0] in_re_2_reg_1340;
reg  signed [15:0] in_re_2_reg_1340_pp0_iter1_reg;
reg  signed [15:0] in_re_2_reg_1340_pp0_iter2_reg;
reg  signed [15:0] in_im_2_reg_1346;
reg  signed [15:0] in_im_2_reg_1346_pp0_iter1_reg;
reg  signed [15:0] in_im_2_reg_1346_pp0_iter2_reg;
reg  signed [15:0] in_re_3_reg_1352;
reg  signed [15:0] in_im_3_reg_1358;
wire  signed [30:0] sext_ln63_1_fu_322_p1;
reg   [15:0] trunc_ln53_4_reg_1370;
reg   [15:0] out_re_1_reg_1375;
reg   [15:0] out_re_1_reg_1375_pp0_iter2_reg;
reg   [15:0] out_re_1_reg_1375_pp0_iter3_reg;
reg   [15:0] trunc_ln53_s_reg_1380;
reg   [15:0] trunc_ln53_2_reg_1385;
reg   [15:0] out_re_3_reg_1390;
reg   [15:0] out_re_3_reg_1390_pp0_iter2_reg;
reg   [15:0] out_re_3_reg_1390_pp0_iter3_reg;
reg   [15:0] out_im_3_reg_1395;
reg   [15:0] out_im_3_reg_1395_pp0_iter2_reg;
reg   [15:0] out_im_3_reg_1395_pp0_iter3_reg;
wire   [30:0] mul_ln63_1_fu_594_p2;
reg  signed [30:0] mul_ln63_1_reg_1400;
wire   [30:0] mul_ln64_1_fu_600_p2;
reg  signed [30:0] mul_ln64_1_reg_1405;
reg   [15:0] trunc_ln53_5_reg_1410;
reg   [15:0] out_im_1_reg_1415;
reg   [15:0] out_im_1_reg_1415_pp0_iter3_reg;
reg  signed [15:0] a_re_reg_1420;
reg  signed [15:0] a_im_reg_1426;
reg  signed [15:0] a_re_2_reg_1432;
reg  signed [15:0] a_im_2_reg_1438;
reg   [15:0] trunc_ln5_reg_1444;
reg   [15:0] trunc_ln53_1_reg_1449;
reg   [15:0] out_re_reg_1454;
reg   [15:0] out_im_reg_1459;
reg   [15:0] trunc_ln53_8_reg_1464;
reg   [15:0] trunc_ln53_9_reg_1469;
reg   [15:0] out_re_2_reg_1474;
reg   [15:0] out_im_2_reg_1479;
wire   [15:0] ap_phi_reg_pp0_iter0_out_im_11_reg_127;
reg   [15:0] ap_phi_reg_pp0_iter1_out_im_11_reg_127;
reg   [15:0] ap_phi_reg_pp0_iter2_out_im_11_reg_127;
reg   [15:0] ap_phi_reg_pp0_iter3_out_im_11_reg_127;
reg   [15:0] ap_phi_reg_pp0_iter4_out_im_11_reg_127;
reg   [15:0] ap_phi_reg_pp0_iter5_out_im_11_reg_127;
wire   [15:0] ap_phi_reg_pp0_iter0_out_im_10_reg_136;
reg   [15:0] ap_phi_reg_pp0_iter1_out_im_10_reg_136;
reg   [15:0] ap_phi_reg_pp0_iter2_out_im_10_reg_136;
reg   [15:0] ap_phi_reg_pp0_iter3_out_im_10_reg_136;
reg   [15:0] ap_phi_reg_pp0_iter4_out_im_10_reg_136;
reg   [15:0] ap_phi_reg_pp0_iter5_out_im_10_reg_136;
wire   [15:0] ap_phi_reg_pp0_iter0_out_im_9_reg_145;
reg   [15:0] ap_phi_reg_pp0_iter1_out_im_9_reg_145;
reg   [15:0] ap_phi_reg_pp0_iter2_out_im_9_reg_145;
reg   [15:0] ap_phi_reg_pp0_iter3_out_im_9_reg_145;
reg   [15:0] ap_phi_reg_pp0_iter4_out_im_9_reg_145;
reg   [15:0] ap_phi_reg_pp0_iter5_out_im_9_reg_145;
wire   [15:0] ap_phi_reg_pp0_iter0_out_im_8_reg_154;
reg   [15:0] ap_phi_reg_pp0_iter1_out_im_8_reg_154;
reg   [15:0] ap_phi_reg_pp0_iter2_out_im_8_reg_154;
reg   [15:0] ap_phi_reg_pp0_iter3_out_im_8_reg_154;
reg   [15:0] ap_phi_reg_pp0_iter4_out_im_8_reg_154;
reg   [15:0] ap_phi_reg_pp0_iter5_out_im_8_reg_154;
wire   [15:0] ap_phi_reg_pp0_iter0_out_re_11_reg_163;
reg   [15:0] ap_phi_reg_pp0_iter1_out_re_11_reg_163;
reg   [15:0] ap_phi_reg_pp0_iter2_out_re_11_reg_163;
reg   [15:0] ap_phi_reg_pp0_iter3_out_re_11_reg_163;
reg   [15:0] ap_phi_reg_pp0_iter4_out_re_11_reg_163;
reg   [15:0] ap_phi_reg_pp0_iter5_out_re_11_reg_163;
wire   [15:0] ap_phi_reg_pp0_iter0_out_re_10_reg_172;
reg   [15:0] ap_phi_reg_pp0_iter1_out_re_10_reg_172;
reg   [15:0] ap_phi_reg_pp0_iter2_out_re_10_reg_172;
reg   [15:0] ap_phi_reg_pp0_iter3_out_re_10_reg_172;
reg   [15:0] ap_phi_reg_pp0_iter4_out_re_10_reg_172;
reg   [15:0] ap_phi_reg_pp0_iter5_out_re_10_reg_172;
wire   [15:0] ap_phi_reg_pp0_iter0_out_re_9_reg_181;
reg   [15:0] ap_phi_reg_pp0_iter1_out_re_9_reg_181;
reg   [15:0] ap_phi_reg_pp0_iter2_out_re_9_reg_181;
reg   [15:0] ap_phi_reg_pp0_iter3_out_re_9_reg_181;
reg   [15:0] ap_phi_reg_pp0_iter4_out_re_9_reg_181;
reg   [15:0] ap_phi_reg_pp0_iter5_out_re_9_reg_181;
wire   [15:0] ap_phi_reg_pp0_iter0_out_re_8_reg_190;
reg   [15:0] ap_phi_reg_pp0_iter1_out_re_8_reg_190;
reg   [15:0] ap_phi_reg_pp0_iter2_out_re_8_reg_190;
reg   [15:0] ap_phi_reg_pp0_iter3_out_re_8_reg_190;
reg   [15:0] ap_phi_reg_pp0_iter4_out_re_8_reg_190;
reg   [15:0] ap_phi_reg_pp0_iter5_out_re_8_reg_190;
reg   [15:0] ap_sig_allocacmp_a_re;
reg   [15:0] ap_sig_allocacmp_a_re_1;
reg   [15:0] ap_sig_allocacmp_a_re_2;
reg   [15:0] ap_sig_allocacmp_a_re_3;
reg   [15:0] ap_sig_allocacmp_a_im;
reg   [15:0] ap_sig_allocacmp_a_im_1;
reg   [15:0] ap_sig_allocacmp_a_im_2;
reg   [15:0] ap_sig_allocacmp_a_im_3;
reg   [8:0] cyc_fu_110;
wire   [8:0] cyc_2_fu_213_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_cyc_1;
wire  signed [15:0] sext_ln63_1_fu_322_p0;
wire  signed [15:0] sext_ln63_5_fu_341_p0;
wire  signed [15:0] sext_ln63_6_fu_345_p0;
wire  signed [15:0] sext_ln136_2_fu_349_p0;
wire  signed [16:0] sext_ln136_2_fu_349_p1;
wire  signed [16:0] sext_ln136_3_fu_353_p1;
wire   [16:0] diff_re_1_fu_356_p2;
wire   [16:0] sum_re_1_fu_366_p2;
wire   [1:0] trunc_ln136_1_fu_362_p1;
wire   [0:0] icmp_ln53_4_fu_376_p2;
wire   [16:0] zext_ln53_4_fu_382_p1;
wire   [16:0] add_ln53_4_fu_386_p2;
wire   [1:0] trunc_ln134_1_fu_372_p1;
wire   [0:0] icmp_ln53_6_fu_402_p2;
wire   [16:0] zext_ln53_6_fu_408_p1;
wire   [16:0] add_ln53_6_fu_412_p2;
wire  signed [15:0] sext_ln136_6_fu_428_p0;
wire  signed [16:0] sext_ln136_6_fu_428_p1;
wire  signed [16:0] sext_ln136_7_fu_432_p1;
wire   [16:0] diff_re_3_fu_435_p2;
wire   [16:0] sum_re_3_fu_445_p2;
wire  signed [15:0] sext_ln137_6_fu_455_p0;
wire  signed [16:0] sext_ln137_6_fu_455_p1;
wire  signed [16:0] sext_ln137_7_fu_459_p1;
wire   [16:0] diff_im_3_fu_462_p2;
wire   [16:0] sum_im_3_fu_472_p2;
wire   [1:0] trunc_ln136_3_fu_441_p1;
wire   [0:0] icmp_ln53_12_fu_482_p2;
wire   [16:0] zext_ln53_12_fu_488_p1;
wire   [16:0] add_ln53_12_fu_492_p2;
wire   [1:0] trunc_ln137_3_fu_468_p1;
wire   [0:0] icmp_ln53_13_fu_508_p2;
wire   [16:0] zext_ln53_13_fu_514_p1;
wire   [16:0] add_ln53_13_fu_518_p2;
wire   [1:0] trunc_ln134_3_fu_451_p1;
wire   [0:0] icmp_ln53_14_fu_534_p2;
wire   [16:0] zext_ln53_14_fu_540_p1;
wire   [16:0] add_ln53_14_fu_544_p2;
wire   [1:0] trunc_ln135_3_fu_478_p1;
wire   [0:0] icmp_ln53_15_fu_560_p2;
wire   [16:0] zext_ln53_15_fu_566_p1;
wire   [16:0] add_ln53_15_fu_570_p2;
wire  signed [15:0] sext_ln63_2_fu_590_p0;
wire  signed [15:0] mul_ln63_1_fu_594_p0;
wire  signed [30:0] sext_ln63_2_fu_590_p1;
wire   [15:0] mul_ln63_1_fu_594_p1;
wire  signed [15:0] mul_ln64_1_fu_600_p0;
wire   [15:0] mul_ln64_1_fu_600_p1;
wire  signed [15:0] sext_ln137_2_fu_611_p0;
wire  signed [16:0] sext_ln137_2_fu_611_p1;
wire  signed [16:0] sext_ln137_3_fu_615_p1;
wire   [16:0] diff_im_1_fu_618_p2;
wire   [16:0] sum_im_1_fu_628_p2;
wire   [1:0] trunc_ln137_1_fu_624_p1;
wire   [0:0] icmp_ln53_5_fu_638_p2;
wire   [16:0] zext_ln53_5_fu_644_p1;
wire   [16:0] add_ln53_5_fu_648_p2;
wire   [1:0] trunc_ln135_1_fu_634_p1;
wire   [0:0] icmp_ln53_7_fu_664_p2;
wire   [16:0] zext_ln53_7_fu_670_p1;
wire   [16:0] add_ln53_7_fu_674_p2;
wire  signed [15:0] sext_ln136_fu_741_p0;
wire  signed [16:0] sext_ln136_fu_741_p1;
wire  signed [16:0] sext_ln136_1_fu_745_p1;
wire   [16:0] diff_re_fu_748_p2;
wire   [16:0] sum_re_fu_758_p2;
wire  signed [15:0] sext_ln137_fu_768_p0;
wire  signed [16:0] sext_ln137_fu_768_p1;
wire  signed [16:0] sext_ln137_1_fu_772_p1;
wire   [16:0] diff_im_fu_775_p2;
wire   [16:0] sum_im_fu_785_p2;
wire   [1:0] trunc_ln136_fu_754_p1;
wire   [0:0] icmp_ln53_fu_795_p2;
wire   [16:0] zext_ln53_fu_801_p1;
wire   [16:0] add_ln53_fu_805_p2;
wire   [1:0] trunc_ln137_fu_781_p1;
wire   [0:0] icmp_ln53_1_fu_821_p2;
wire   [16:0] zext_ln53_1_fu_827_p1;
wire   [16:0] add_ln53_1_fu_831_p2;
wire   [1:0] trunc_ln134_fu_764_p1;
wire   [0:0] icmp_ln53_2_fu_847_p2;
wire   [16:0] zext_ln53_2_fu_853_p1;
wire   [16:0] add_ln53_2_fu_857_p2;
wire   [1:0] trunc_ln135_fu_791_p1;
wire   [0:0] icmp_ln53_3_fu_873_p2;
wire   [16:0] zext_ln53_3_fu_879_p1;
wire   [16:0] add_ln53_3_fu_883_p2;
wire  signed [15:0] sext_ln136_4_fu_899_p0;
wire  signed [16:0] sext_ln136_4_fu_899_p1;
wire  signed [16:0] sext_ln136_5_fu_903_p1;
wire   [16:0] diff_re_2_fu_906_p2;
wire   [16:0] sum_re_2_fu_916_p2;
wire  signed [15:0] sext_ln137_4_fu_926_p0;
wire  signed [16:0] sext_ln137_4_fu_926_p1;
wire  signed [16:0] sext_ln137_5_fu_930_p1;
wire   [16:0] diff_im_2_fu_933_p2;
wire   [16:0] sum_im_2_fu_943_p2;
wire   [1:0] trunc_ln136_2_fu_912_p1;
wire   [0:0] icmp_ln53_8_fu_953_p2;
wire   [16:0] zext_ln53_8_fu_959_p1;
wire   [16:0] add_ln53_8_fu_963_p2;
wire   [1:0] trunc_ln137_2_fu_939_p1;
wire   [0:0] icmp_ln53_9_fu_979_p2;
wire   [16:0] zext_ln53_9_fu_985_p1;
wire   [16:0] add_ln53_9_fu_989_p2;
wire   [1:0] trunc_ln134_2_fu_922_p1;
wire   [0:0] icmp_ln53_10_fu_1005_p2;
wire   [16:0] zext_ln53_10_fu_1011_p1;
wire   [16:0] add_ln53_10_fu_1015_p2;
wire   [1:0] trunc_ln135_2_fu_949_p1;
wire   [0:0] icmp_ln53_11_fu_1031_p2;
wire   [16:0] zext_ln53_11_fu_1037_p1;
wire   [16:0] add_ln53_11_fu_1041_p2;
wire   [30:0] shl_ln63_1_fu_1068_p3;
wire  signed [30:0] sext_ln64_fu_1062_p1;
wire   [30:0] sub_ln63_1_fu_1075_p2;
wire  signed [30:0] sext_ln63_fu_1065_p1;
wire   [30:0] shl_ln_fu_1087_p3;
wire   [30:0] sub_ln64_fu_1094_p2;
wire   [30:0] pr_fu_1081_p2;
wire   [30:0] pi_fu_1100_p2;
wire  signed [30:0] grp_fu_1262_p3;
wire  signed [30:0] grp_fu_1270_p3;
wire   [30:0] shl_ln1_fu_1150_p3;
wire  signed [30:0] sext_ln63_3_fu_1144_p1;
wire   [30:0] shl_ln64_1_fu_1163_p3;
wire   [30:0] sub_ln64_2_fu_1170_p2;
wire  signed [30:0] sext_ln63_4_fu_1147_p1;
wire   [30:0] pr_2_fu_1157_p2;
wire   [30:0] pi_2_fu_1176_p2;
wire  signed [30:0] grp_fu_1287_p3;
wire  signed [30:0] grp_fu_1278_p3;
wire  signed [15:0] grp_fu_1262_p0;
wire   [14:0] grp_fu_1262_p1;
wire  signed [15:0] grp_fu_1270_p0;
wire  signed [15:0] grp_fu_1270_p1;
wire  signed [15:0] grp_fu_1278_p0;
wire  signed [16:0] sext_ln63_6_fu_345_p1;
wire  signed [15:0] grp_fu_1278_p1;
wire  signed [16:0] sext_ln63_5_fu_341_p1;
wire  signed [15:0] grp_fu_1278_p2;
wire  signed [15:0] grp_fu_1287_p0;
wire  signed [15:0] grp_fu_1287_p1;
wire  signed [15:0] grp_fu_1287_p2;
reg    grp_fu_1262_ce;
reg    grp_fu_1270_ce;
reg    grp_fu_1278_ce;
reg    grp_fu_1287_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
wire    ap_ST_iter3_fsm_state4_blk;
wire    ap_ST_iter4_fsm_state5_blk;
reg    ap_ST_iter5_fsm_state6_blk;
wire    ap_start_int;
reg    ap_condition_189;
reg    ap_condition_134;
reg    ap_condition_427;
reg    ap_condition_1232;
reg    ap_condition_183;
reg    ap_condition_453;
reg    ap_condition_1241;
reg    ap_condition_438;
reg    ap_condition_916;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_0 = 16'd0;
#0 void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_2_0 = 16'd0;
#0 void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_3_0 = 16'd0;
#0 void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_4_0 = 16'd0;
#0 void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_0 = 16'd0;
#0 void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_5_0 = 16'd0;
#0 void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_6_0 = 16'd0;
#0 void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_7_0 = 16'd0;
#0 cyc_fu_110 = 9'd0;
end

fft_mdf_mul_16s_16ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_16s_16ns_31_1_1_U157(
    .din0(mul_ln63_1_fu_594_p0),
    .din1(mul_ln63_1_fu_594_p1),
    .dout(mul_ln63_1_fu_594_p2)
);

fft_mdf_mul_16s_16ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_16s_16ns_31_1_1_U158(
    .din0(mul_ln64_1_fu_600_p0),
    .din1(mul_ln64_1_fu_600_p1),
    .dout(mul_ln64_1_fu_600_p2)
);

fft_mdf_mac_muladd_16s_15ns_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_15ns_31s_31_4_1_U159(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1262_p0),
    .din1(grp_fu_1262_p1),
    .din2(mul_ln63_1_reg_1400),
    .ce(grp_fu_1262_ce),
    .dout(grp_fu_1262_p3)
);

fft_mdf_mac_muladd_16s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_16s_31s_31_4_1_U160(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1270_p0),
    .din1(grp_fu_1270_p1),
    .din2(mul_ln64_1_reg_1405),
    .ce(grp_fu_1270_ce),
    .dout(grp_fu_1270_p3)
);

fft_mdf_am_addmul_16s_16s_16s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
am_addmul_16s_16s_16s_31_4_1_U161(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1278_p0),
    .din1(grp_fu_1278_p1),
    .din2(grp_fu_1278_p2),
    .ce(grp_fu_1278_ce),
    .dout(grp_fu_1278_p3)
);

fft_mdf_am_submul_16s_16s_16s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
am_submul_16s_16s_16s_31_4_1_U162(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1287_p0),
    .din1(grp_fu_1287_p1),
    .din2(grp_fu_1287_p2),
    .ce(grp_fu_1287_ce),
    .dout(grp_fu_1287_p3)
);

fft_mdf_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_189)) begin
        if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd0) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_im_10_reg_136 <= {{grp_fu_1270_p3[30:15]}};
        end else if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_im_10_reg_136 <= out_im_1_reg_1415_pp0_iter3_reg;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_out_im_10_reg_136 <= ap_phi_reg_pp0_iter4_out_im_10_reg_136;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_189)) begin
        if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd0) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_im_11_reg_127 <= {{pi_fu_1100_p2[30:15]}};
        end else if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_im_11_reg_127 <= out_im_reg_1459;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_out_im_11_reg_127 <= ap_phi_reg_pp0_iter4_out_im_11_reg_127;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_189)) begin
        if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd0) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_im_8_reg_154 <= {{grp_fu_1278_p3[30:15]}};
        end else if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_im_8_reg_154 <= out_im_3_reg_1395_pp0_iter3_reg;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_out_im_8_reg_154 <= ap_phi_reg_pp0_iter4_out_im_8_reg_154;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_189)) begin
        if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd0) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_im_9_reg_145 <= {{pi_2_fu_1176_p2[30:15]}};
        end else if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_im_9_reg_145 <= out_im_2_reg_1479;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_out_im_9_reg_145 <= ap_phi_reg_pp0_iter4_out_im_9_reg_145;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_189)) begin
        if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd0) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_re_10_reg_172 <= {{grp_fu_1262_p3[30:15]}};
        end else if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_re_10_reg_172 <= out_re_1_reg_1375_pp0_iter3_reg;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_out_re_10_reg_172 <= ap_phi_reg_pp0_iter4_out_re_10_reg_172;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_189)) begin
        if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd0) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_re_11_reg_163 <= {{pr_fu_1081_p2[30:15]}};
        end else if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_re_11_reg_163 <= out_re_reg_1454;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_out_re_11_reg_163 <= ap_phi_reg_pp0_iter4_out_re_11_reg_163;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_189)) begin
        if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd0) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_re_8_reg_190 <= {{grp_fu_1287_p3[30:15]}};
        end else if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_re_8_reg_190 <= out_re_3_reg_1390_pp0_iter3_reg;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_out_re_8_reg_190 <= ap_phi_reg_pp0_iter4_out_re_8_reg_190;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_189)) begin
        if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd0) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_re_9_reg_181 <= {{pr_2_fu_1157_p2[30:15]}};
        end else if (((trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_out_re_9_reg_181 <= out_re_2_reg_1474;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_out_re_9_reg_181 <= ap_phi_reg_pp0_iter4_out_re_9_reg_181;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_134)) begin
        if ((icmp_ln95_fu_207_p2 == 1'd0)) begin
            cyc_fu_110 <= cyc_2_fu_213_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            cyc_fu_110 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((1'b1 == ap_condition_1232)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_0 <= in_im_reg_1322_pp0_iter2_reg;
        end else if ((1'b1 == ap_condition_427)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_0 <= trunc_ln53_1_reg_1449;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((1'b1 == ap_condition_1241)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_5_0 <= in_im_1_reg_1334_pp0_iter1_reg;
        end else if ((1'b1 == ap_condition_453)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_5_0 <= trunc_ln53_5_reg_1410;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((1'b1 == ap_condition_1232)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_6_0 <= in_im_2_reg_1346_pp0_iter2_reg;
        end else if ((1'b1 == ap_condition_427)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_6_0 <= trunc_ln53_9_reg_1469;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((1'b1 == ap_condition_916)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_7_0 <= in_im_3_reg_1358;
        end else if ((1'b1 == ap_condition_438)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_7_0 <= trunc_ln53_2_reg_1385;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((1'b1 == ap_condition_1232)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_0 <= in_re_reg_1316_pp0_iter2_reg;
        end else if ((1'b1 == ap_condition_427)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_0 <= trunc_ln5_reg_1444;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((1'b1 == ap_condition_916)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_2_0 <= in_re_1_reg_1328;
        end else if ((1'b1 == ap_condition_438)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_2_0 <= trunc_ln53_4_reg_1370;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((1'b1 == ap_condition_1232)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_3_0 <= in_re_2_reg_1340_pp0_iter2_reg;
        end else if ((1'b1 == ap_condition_427)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_3_0 <= trunc_ln53_8_reg_1464;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((1'b1 == ap_condition_916)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_4_0 <= in_re_3_reg_1352;
        end else if ((1'b1 == ap_condition_438)) begin
            void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_4_0 <= trunc_ln53_s_reg_1380;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        a_im_2_reg_1438 <= ap_sig_allocacmp_a_im_2;
        a_im_reg_1426 <= ap_sig_allocacmp_a_im;
        a_re_2_reg_1432 <= ap_sig_allocacmp_a_re_2;
        a_re_reg_1420 <= ap_sig_allocacmp_a_re;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_phi_reg_pp0_iter4_out_im_10_reg_136 <= ap_phi_reg_pp0_iter3_out_im_10_reg_136;
        ap_phi_reg_pp0_iter4_out_im_11_reg_127 <= ap_phi_reg_pp0_iter3_out_im_11_reg_127;
        ap_phi_reg_pp0_iter4_out_im_8_reg_154 <= ap_phi_reg_pp0_iter3_out_im_8_reg_154;
        ap_phi_reg_pp0_iter4_out_im_9_reg_145 <= ap_phi_reg_pp0_iter3_out_im_9_reg_145;
        ap_phi_reg_pp0_iter4_out_re_10_reg_172 <= ap_phi_reg_pp0_iter3_out_re_10_reg_172;
        ap_phi_reg_pp0_iter4_out_re_11_reg_163 <= ap_phi_reg_pp0_iter3_out_re_11_reg_163;
        ap_phi_reg_pp0_iter4_out_re_8_reg_190 <= ap_phi_reg_pp0_iter3_out_re_8_reg_190;
        ap_phi_reg_pp0_iter4_out_re_9_reg_181 <= ap_phi_reg_pp0_iter3_out_re_9_reg_181;
        icmp_ln95_reg_1303_pp0_iter3_reg <= icmp_ln95_reg_1303_pp0_iter2_reg;
        out_im_1_reg_1415_pp0_iter3_reg <= out_im_1_reg_1415;
        out_im_2_reg_1479 <= {{add_ln53_11_fu_1041_p2[16:1]}};
        out_im_3_reg_1395_pp0_iter3_reg <= out_im_3_reg_1395_pp0_iter2_reg;
        out_im_reg_1459 <= {{add_ln53_3_fu_883_p2[16:1]}};
        out_re_1_reg_1375_pp0_iter3_reg <= out_re_1_reg_1375_pp0_iter2_reg;
        out_re_2_reg_1474 <= {{add_ln53_10_fu_1015_p2[16:1]}};
        out_re_3_reg_1390_pp0_iter3_reg <= out_re_3_reg_1390_pp0_iter2_reg;
        out_re_reg_1454 <= {{add_ln53_2_fu_857_p2[16:1]}};
        trunc_ln53_1_reg_1449 <= {{add_ln53_1_fu_831_p2[16:1]}};
        trunc_ln53_8_reg_1464 <= {{add_ln53_8_fu_963_p2[16:1]}};
        trunc_ln53_9_reg_1469 <= {{add_ln53_9_fu_989_p2[16:1]}};
        trunc_ln5_reg_1444 <= {{add_ln53_fu_805_p2[16:1]}};
        trunc_ln95_reg_1307_pp0_iter3_reg <= trunc_ln95_reg_1307_pp0_iter2_reg;
        y_last_reg_1311_pp0_iter3_reg <= y_last_reg_1311_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_phi_reg_pp0_iter1_out_im_10_reg_136 <= ap_phi_reg_pp0_iter0_out_im_10_reg_136;
        ap_phi_reg_pp0_iter1_out_im_11_reg_127 <= ap_phi_reg_pp0_iter0_out_im_11_reg_127;
        ap_phi_reg_pp0_iter1_out_im_8_reg_154 <= ap_phi_reg_pp0_iter0_out_im_8_reg_154;
        ap_phi_reg_pp0_iter1_out_im_9_reg_145 <= ap_phi_reg_pp0_iter0_out_im_9_reg_145;
        ap_phi_reg_pp0_iter1_out_re_10_reg_172 <= ap_phi_reg_pp0_iter0_out_re_10_reg_172;
        ap_phi_reg_pp0_iter1_out_re_11_reg_163 <= ap_phi_reg_pp0_iter0_out_re_11_reg_163;
        ap_phi_reg_pp0_iter1_out_re_8_reg_190 <= ap_phi_reg_pp0_iter0_out_re_8_reg_190;
        ap_phi_reg_pp0_iter1_out_re_9_reg_181 <= ap_phi_reg_pp0_iter0_out_re_9_reg_181;
        icmp_ln95_reg_1303 <= icmp_ln95_fu_207_p2;
        in_im_1_reg_1334 <= {{s6_dout[63:48]}};
        in_im_2_reg_1346 <= {{s6_dout[95:80]}};
        in_im_3_reg_1358 <= {{s6_dout[127:112]}};
        in_im_reg_1322 <= {{s6_dout[31:16]}};
        in_re_1_reg_1328 <= {{s6_dout[47:32]}};
        in_re_2_reg_1340 <= {{s6_dout[79:64]}};
        in_re_3_reg_1352 <= {{s6_dout[111:96]}};
        in_re_reg_1316 <= in_re_fu_231_p1;
        trunc_ln95_reg_1307 <= trunc_ln95_fu_219_p1;
        y_last_reg_1311 <= s6_dout[32'd128];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_phi_reg_pp0_iter2_out_im_10_reg_136 <= ap_phi_reg_pp0_iter1_out_im_10_reg_136;
        ap_phi_reg_pp0_iter2_out_im_11_reg_127 <= ap_phi_reg_pp0_iter1_out_im_11_reg_127;
        ap_phi_reg_pp0_iter2_out_im_8_reg_154 <= ap_phi_reg_pp0_iter1_out_im_8_reg_154;
        ap_phi_reg_pp0_iter2_out_im_9_reg_145 <= ap_phi_reg_pp0_iter1_out_im_9_reg_145;
        ap_phi_reg_pp0_iter2_out_re_10_reg_172 <= ap_phi_reg_pp0_iter1_out_re_10_reg_172;
        ap_phi_reg_pp0_iter2_out_re_11_reg_163 <= ap_phi_reg_pp0_iter1_out_re_11_reg_163;
        ap_phi_reg_pp0_iter2_out_re_8_reg_190 <= ap_phi_reg_pp0_iter1_out_re_8_reg_190;
        ap_phi_reg_pp0_iter2_out_re_9_reg_181 <= ap_phi_reg_pp0_iter1_out_re_9_reg_181;
        icmp_ln95_reg_1303_pp0_iter1_reg <= icmp_ln95_reg_1303;
        in_im_1_reg_1334_pp0_iter1_reg <= in_im_1_reg_1334;
        in_im_2_reg_1346_pp0_iter1_reg <= in_im_2_reg_1346;
        in_im_reg_1322_pp0_iter1_reg <= in_im_reg_1322;
        in_re_2_reg_1340_pp0_iter1_reg <= in_re_2_reg_1340;
        in_re_reg_1316_pp0_iter1_reg <= in_re_reg_1316;
        out_im_3_reg_1395 <= {{add_ln53_15_fu_570_p2[16:1]}};
        out_re_1_reg_1375 <= {{add_ln53_6_fu_412_p2[16:1]}};
        out_re_3_reg_1390 <= {{add_ln53_14_fu_544_p2[16:1]}};
        trunc_ln53_2_reg_1385 <= {{add_ln53_13_fu_518_p2[16:1]}};
        trunc_ln53_4_reg_1370 <= {{add_ln53_4_fu_386_p2[16:1]}};
        trunc_ln53_s_reg_1380 <= {{add_ln53_12_fu_492_p2[16:1]}};
        trunc_ln95_reg_1307_pp0_iter1_reg <= trunc_ln95_reg_1307;
        y_last_reg_1311_pp0_iter1_reg <= y_last_reg_1311;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_phi_reg_pp0_iter3_out_im_10_reg_136 <= ap_phi_reg_pp0_iter2_out_im_10_reg_136;
        ap_phi_reg_pp0_iter3_out_im_11_reg_127 <= ap_phi_reg_pp0_iter2_out_im_11_reg_127;
        ap_phi_reg_pp0_iter3_out_im_8_reg_154 <= ap_phi_reg_pp0_iter2_out_im_8_reg_154;
        ap_phi_reg_pp0_iter3_out_im_9_reg_145 <= ap_phi_reg_pp0_iter2_out_im_9_reg_145;
        ap_phi_reg_pp0_iter3_out_re_10_reg_172 <= ap_phi_reg_pp0_iter2_out_re_10_reg_172;
        ap_phi_reg_pp0_iter3_out_re_11_reg_163 <= ap_phi_reg_pp0_iter2_out_re_11_reg_163;
        ap_phi_reg_pp0_iter3_out_re_8_reg_190 <= ap_phi_reg_pp0_iter2_out_re_8_reg_190;
        ap_phi_reg_pp0_iter3_out_re_9_reg_181 <= ap_phi_reg_pp0_iter2_out_re_9_reg_181;
        icmp_ln95_reg_1303_pp0_iter2_reg <= icmp_ln95_reg_1303_pp0_iter1_reg;
        in_im_2_reg_1346_pp0_iter2_reg <= in_im_2_reg_1346_pp0_iter1_reg;
        in_im_reg_1322_pp0_iter2_reg <= in_im_reg_1322_pp0_iter1_reg;
        in_re_2_reg_1340_pp0_iter2_reg <= in_re_2_reg_1340_pp0_iter1_reg;
        in_re_reg_1316_pp0_iter2_reg <= in_re_reg_1316_pp0_iter1_reg;
        mul_ln63_1_reg_1400 <= mul_ln63_1_fu_594_p2;
        mul_ln64_1_reg_1405 <= mul_ln64_1_fu_600_p2;
        out_im_1_reg_1415 <= {{add_ln53_7_fu_674_p2[16:1]}};
        out_im_3_reg_1395_pp0_iter2_reg <= out_im_3_reg_1395;
        out_re_1_reg_1375_pp0_iter2_reg <= out_re_1_reg_1375;
        out_re_3_reg_1390_pp0_iter2_reg <= out_re_3_reg_1390;
        trunc_ln53_5_reg_1410 <= {{add_ln53_5_fu_648_p2[16:1]}};
        trunc_ln95_reg_1307_pp0_iter2_reg <= trunc_ln95_reg_1307_pp0_iter1_reg;
        y_last_reg_1311_pp0_iter2_reg <= y_last_reg_1311_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        icmp_ln95_reg_1303_pp0_iter4_reg <= icmp_ln95_reg_1303_pp0_iter3_reg;
        y_last_reg_1311_pp0_iter4_reg <= y_last_reg_1311_pp0_iter3_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

assign ap_ST_iter3_fsm_state4_blk = 1'b0;

assign ap_ST_iter4_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state6_pp0_stage0_iter5)) begin
        ap_ST_iter5_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_iter5_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (icmp_ln95_fu_207_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter5_fsm_state0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state5) & (trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
        ap_sig_allocacmp_a_im = trunc_ln53_1_reg_1449;
    end else begin
        ap_sig_allocacmp_a_im = void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter3_fsm_state4) & (trunc_ln95_reg_1307_pp0_iter2_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter2_reg == 1'd0))) begin
        ap_sig_allocacmp_a_im_1 = trunc_ln53_5_reg_1410;
    end else begin
        ap_sig_allocacmp_a_im_1 = void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_5_0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state5) & (trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
        ap_sig_allocacmp_a_im_2 = trunc_ln53_9_reg_1469;
    end else begin
        ap_sig_allocacmp_a_im_2 = void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_6_0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state3) & (trunc_ln95_reg_1307_pp0_iter1_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter1_reg == 1'd0))) begin
        ap_sig_allocacmp_a_im_3 = trunc_ln53_2_reg_1385;
    end else begin
        ap_sig_allocacmp_a_im_3 = void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_im_7_0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state5) & (trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
        ap_sig_allocacmp_a_re = trunc_ln5_reg_1444;
    end else begin
        ap_sig_allocacmp_a_re = void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state3) & (trunc_ln95_reg_1307_pp0_iter1_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter1_reg == 1'd0))) begin
        ap_sig_allocacmp_a_re_1 = trunc_ln53_4_reg_1370;
    end else begin
        ap_sig_allocacmp_a_re_1 = void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_2_0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state5) & (trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0))) begin
        ap_sig_allocacmp_a_re_2 = trunc_ln53_8_reg_1464;
    end else begin
        ap_sig_allocacmp_a_re_2 = void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_3_0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state3) & (trunc_ln95_reg_1307_pp0_iter1_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter1_reg == 1'd0))) begin
        ap_sig_allocacmp_a_re_3 = trunc_ln53_s_reg_1380;
    end else begin
        ap_sig_allocacmp_a_re_3 = void_stage_fb_7_1_stream_mdf_word_t_0_stream_mdf_word_t_0_delay_re_4_0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_cyc_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_cyc_1 = cyc_fu_110;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter3_fsm_state4)))) begin
        grp_fu_1262_ce = 1'b1;
    end else begin
        grp_fu_1262_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter3_fsm_state4)))) begin
        grp_fu_1270_ce = 1'b1;
    end else begin
        grp_fu_1270_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter3_fsm_state4)))) begin
        grp_fu_1278_ce = 1'b1;
    end else begin
        grp_fu_1278_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter3_fsm_state4)))) begin
        grp_fu_1287_ce = 1'b1;
    end else begin
        grp_fu_1287_ce = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (icmp_ln95_fu_207_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        s6_blk_n = s6_empty_n;
    end else begin
        s6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (icmp_ln95_fu_207_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        s6_read = 1'b1;
    end else begin
        s6_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter5_fsm_state6) & (icmp_ln95_reg_1303_pp0_iter4_reg == 1'd0))) begin
        s7_blk_n = s7_full_n;
    end else begin
        s7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6) & (icmp_ln95_reg_1303_pp0_iter4_reg == 1'd0))) begin
        s7_write = 1'b1;
    end else begin
        s7_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b0 == ap_block_state1_pp0_stage0_iter0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b0 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b0 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6) & (icmp_ln95_reg_1303_pp0_iter4_reg == 1'd1)))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

assign add_ln53_10_fu_1015_p2 = (sum_re_2_fu_916_p2 + zext_ln53_10_fu_1011_p1);

assign add_ln53_11_fu_1041_p2 = (sum_im_2_fu_943_p2 + zext_ln53_11_fu_1037_p1);

assign add_ln53_12_fu_492_p2 = (diff_re_3_fu_435_p2 + zext_ln53_12_fu_488_p1);

assign add_ln53_13_fu_518_p2 = (diff_im_3_fu_462_p2 + zext_ln53_13_fu_514_p1);

assign add_ln53_14_fu_544_p2 = (sum_re_3_fu_445_p2 + zext_ln53_14_fu_540_p1);

assign add_ln53_15_fu_570_p2 = (sum_im_3_fu_472_p2 + zext_ln53_15_fu_566_p1);

assign add_ln53_1_fu_831_p2 = (diff_im_fu_775_p2 + zext_ln53_1_fu_827_p1);

assign add_ln53_2_fu_857_p2 = (sum_re_fu_758_p2 + zext_ln53_2_fu_853_p1);

assign add_ln53_3_fu_883_p2 = (sum_im_fu_785_p2 + zext_ln53_3_fu_879_p1);

assign add_ln53_4_fu_386_p2 = (diff_re_1_fu_356_p2 + zext_ln53_4_fu_382_p1);

assign add_ln53_5_fu_648_p2 = (diff_im_1_fu_618_p2 + zext_ln53_5_fu_644_p1);

assign add_ln53_6_fu_412_p2 = (sum_re_1_fu_366_p2 + zext_ln53_6_fu_408_p1);

assign add_ln53_7_fu_674_p2 = (sum_im_1_fu_628_p2 + zext_ln53_7_fu_670_p1);

assign add_ln53_8_fu_963_p2 = (diff_re_2_fu_906_p2 + zext_ln53_8_fu_959_p1);

assign add_ln53_9_fu_989_p2 = (diff_im_2_fu_933_p2 + zext_ln53_9_fu_985_p1);

assign add_ln53_fu_805_p2 = (diff_re_fu_748_p2 + zext_ln53_fu_801_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state0 = ap_CS_iter5_fsm[32'd0];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((icmp_ln95_fu_207_p2 == 1'd0) & (s6_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((icmp_ln95_reg_1303_pp0_iter4_reg == 1'd0) & (s7_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_1232 = ((1'b1 == ap_CS_iter3_fsm_state4) & (trunc_ln95_reg_1307_pp0_iter2_reg == 1'd0) & (icmp_ln95_reg_1303_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1241 = ((1'b1 == ap_CS_iter2_fsm_state3) & (trunc_ln95_reg_1307_pp0_iter1_reg == 1'd0) & (icmp_ln95_reg_1303_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_134 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_183 = ~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5)));
end

always @ (*) begin
    ap_condition_189 = (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter5_fsm_state6) & (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5));
end

always @ (*) begin
    ap_condition_427 = ((1'b1 == ap_CS_iter4_fsm_state5) & (trunc_ln95_reg_1307_pp0_iter3_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_condition_438 = ((1'b1 == ap_CS_iter2_fsm_state3) & (trunc_ln95_reg_1307_pp0_iter1_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_453 = ((1'b1 == ap_CS_iter3_fsm_state4) & (trunc_ln95_reg_1307_pp0_iter2_reg == 1'd1) & (icmp_ln95_reg_1303_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_condition_916 = ((1'b1 == ap_CS_iter1_fsm_state2) & (trunc_ln95_reg_1307 == 1'd0) & (icmp_ln95_reg_1303 == 1'd0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_out_im_10_reg_136 = 'bx;

assign ap_phi_reg_pp0_iter0_out_im_11_reg_127 = 'bx;

assign ap_phi_reg_pp0_iter0_out_im_8_reg_154 = 'bx;

assign ap_phi_reg_pp0_iter0_out_im_9_reg_145 = 'bx;

assign ap_phi_reg_pp0_iter0_out_re_10_reg_172 = 'bx;

assign ap_phi_reg_pp0_iter0_out_re_11_reg_163 = 'bx;

assign ap_phi_reg_pp0_iter0_out_re_8_reg_190 = 'bx;

assign ap_phi_reg_pp0_iter0_out_re_9_reg_181 = 'bx;

assign ap_ready = internal_ap_ready;

assign cyc_2_fu_213_p2 = (ap_sig_allocacmp_cyc_1 + 9'd1);

assign diff_im_1_fu_618_p2 = ($signed(sext_ln137_2_fu_611_p1) - $signed(sext_ln137_3_fu_615_p1));

assign diff_im_2_fu_933_p2 = ($signed(sext_ln137_4_fu_926_p1) - $signed(sext_ln137_5_fu_930_p1));

assign diff_im_3_fu_462_p2 = ($signed(sext_ln137_6_fu_455_p1) - $signed(sext_ln137_7_fu_459_p1));

assign diff_im_fu_775_p2 = ($signed(sext_ln137_fu_768_p1) - $signed(sext_ln137_1_fu_772_p1));

assign diff_re_1_fu_356_p2 = ($signed(sext_ln136_2_fu_349_p1) - $signed(sext_ln136_3_fu_353_p1));

assign diff_re_2_fu_906_p2 = ($signed(sext_ln136_4_fu_899_p1) - $signed(sext_ln136_5_fu_903_p1));

assign diff_re_3_fu_435_p2 = ($signed(sext_ln136_6_fu_428_p1) - $signed(sext_ln136_7_fu_432_p1));

assign diff_re_fu_748_p2 = ($signed(sext_ln136_fu_741_p1) - $signed(sext_ln136_1_fu_745_p1));

assign grp_fu_1262_p0 = sext_ln63_1_fu_322_p1;

assign grp_fu_1262_p1 = 31'd23170;

assign grp_fu_1270_p0 = sext_ln63_1_fu_322_p1;

assign grp_fu_1270_p1 = 31'd2147460477;

assign grp_fu_1278_p0 = sext_ln63_6_fu_345_p1;

assign grp_fu_1278_p1 = sext_ln63_5_fu_341_p1;

assign grp_fu_1278_p2 = 31'd2147460477;

assign grp_fu_1287_p0 = sext_ln63_5_fu_341_p1;

assign grp_fu_1287_p1 = sext_ln63_6_fu_345_p1;

assign grp_fu_1287_p2 = 31'd2147460477;

assign icmp_ln53_10_fu_1005_p2 = ((trunc_ln134_2_fu_922_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_11_fu_1031_p2 = ((trunc_ln135_2_fu_949_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_12_fu_482_p2 = ((trunc_ln136_3_fu_441_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_13_fu_508_p2 = ((trunc_ln137_3_fu_468_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_14_fu_534_p2 = ((trunc_ln134_3_fu_451_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_15_fu_560_p2 = ((trunc_ln135_3_fu_478_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_1_fu_821_p2 = ((trunc_ln137_fu_781_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_2_fu_847_p2 = ((trunc_ln134_fu_764_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_3_fu_873_p2 = ((trunc_ln135_fu_791_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_4_fu_376_p2 = ((trunc_ln136_1_fu_362_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_5_fu_638_p2 = ((trunc_ln137_1_fu_624_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_6_fu_402_p2 = ((trunc_ln134_1_fu_372_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_7_fu_664_p2 = ((trunc_ln135_1_fu_634_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_8_fu_953_p2 = ((trunc_ln136_2_fu_912_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_9_fu_979_p2 = ((trunc_ln137_2_fu_939_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_795_p2 = ((trunc_ln136_fu_754_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_207_p2 = ((ap_sig_allocacmp_cyc_1 == 9'd256) ? 1'b1 : 1'b0);

assign in_re_fu_231_p1 = s6_dout[15:0];

assign mul_ln63_1_fu_594_p0 = sext_ln63_2_fu_590_p1;

assign mul_ln63_1_fu_594_p1 = 31'd23171;

assign mul_ln64_1_fu_600_p0 = sext_ln63_2_fu_590_p1;

assign mul_ln64_1_fu_600_p1 = 31'd23170;

assign pi_2_fu_1176_p2 = ($signed(sub_ln64_2_fu_1170_p2) - $signed(sext_ln63_4_fu_1147_p1));

assign pi_fu_1100_p2 = ($signed(sub_ln64_fu_1094_p2) - $signed(sext_ln64_fu_1062_p1));

assign pr_2_fu_1157_p2 = ($signed(shl_ln1_fu_1150_p3) - $signed(sext_ln63_3_fu_1144_p1));

assign pr_fu_1081_p2 = ($signed(sub_ln63_1_fu_1075_p2) + $signed(sext_ln63_fu_1065_p1));

assign s7_din = {{{{{{{{{y_last_reg_1311_pp0_iter4_reg}, {ap_phi_reg_pp0_iter5_out_im_8_reg_154}}, {ap_phi_reg_pp0_iter5_out_re_8_reg_190}}, {ap_phi_reg_pp0_iter5_out_im_9_reg_145}}, {ap_phi_reg_pp0_iter5_out_re_9_reg_181}}, {ap_phi_reg_pp0_iter5_out_im_10_reg_136}}, {ap_phi_reg_pp0_iter5_out_re_10_reg_172}}, {ap_phi_reg_pp0_iter5_out_im_11_reg_127}}, {ap_phi_reg_pp0_iter5_out_re_11_reg_163}};

assign sext_ln136_1_fu_745_p1 = in_re_reg_1316_pp0_iter2_reg;

assign sext_ln136_2_fu_349_p0 = ap_sig_allocacmp_a_re_1;

assign sext_ln136_2_fu_349_p1 = sext_ln136_2_fu_349_p0;

assign sext_ln136_3_fu_353_p1 = in_re_1_reg_1328;

assign sext_ln136_4_fu_899_p0 = ap_sig_allocacmp_a_re_2;

assign sext_ln136_4_fu_899_p1 = sext_ln136_4_fu_899_p0;

assign sext_ln136_5_fu_903_p1 = in_re_2_reg_1340_pp0_iter2_reg;

assign sext_ln136_6_fu_428_p0 = ap_sig_allocacmp_a_re_3;

assign sext_ln136_6_fu_428_p1 = sext_ln136_6_fu_428_p0;

assign sext_ln136_7_fu_432_p1 = in_re_3_reg_1352;

assign sext_ln136_fu_741_p0 = ap_sig_allocacmp_a_re;

assign sext_ln136_fu_741_p1 = sext_ln136_fu_741_p0;

assign sext_ln137_1_fu_772_p1 = in_im_reg_1322_pp0_iter2_reg;

assign sext_ln137_2_fu_611_p0 = ap_sig_allocacmp_a_im_1;

assign sext_ln137_2_fu_611_p1 = sext_ln137_2_fu_611_p0;

assign sext_ln137_3_fu_615_p1 = in_im_1_reg_1334_pp0_iter1_reg;

assign sext_ln137_4_fu_926_p0 = ap_sig_allocacmp_a_im_2;

assign sext_ln137_4_fu_926_p1 = sext_ln137_4_fu_926_p0;

assign sext_ln137_5_fu_930_p1 = in_im_2_reg_1346_pp0_iter2_reg;

assign sext_ln137_6_fu_455_p0 = ap_sig_allocacmp_a_im_3;

assign sext_ln137_6_fu_455_p1 = sext_ln137_6_fu_455_p0;

assign sext_ln137_7_fu_459_p1 = in_im_3_reg_1358;

assign sext_ln137_fu_768_p0 = ap_sig_allocacmp_a_im;

assign sext_ln137_fu_768_p1 = sext_ln137_fu_768_p0;

assign sext_ln63_1_fu_322_p0 = ap_sig_allocacmp_a_re_1;

assign sext_ln63_1_fu_322_p1 = sext_ln63_1_fu_322_p0;

assign sext_ln63_2_fu_590_p0 = ap_sig_allocacmp_a_im_1;

assign sext_ln63_2_fu_590_p1 = sext_ln63_2_fu_590_p0;

assign sext_ln63_3_fu_1144_p1 = a_re_2_reg_1432;

assign sext_ln63_4_fu_1147_p1 = a_im_2_reg_1438;

assign sext_ln63_5_fu_341_p0 = ap_sig_allocacmp_a_re_3;

assign sext_ln63_5_fu_341_p1 = sext_ln63_5_fu_341_p0;

assign sext_ln63_6_fu_345_p0 = ap_sig_allocacmp_a_im_3;

assign sext_ln63_6_fu_345_p1 = sext_ln63_6_fu_345_p0;

assign sext_ln63_fu_1065_p1 = a_im_reg_1426;

assign sext_ln64_fu_1062_p1 = a_re_reg_1420;

assign shl_ln1_fu_1150_p3 = {{a_im_2_reg_1438}, {15'd0}};

assign shl_ln63_1_fu_1068_p3 = {{a_re_reg_1420}, {15'd0}};

assign shl_ln64_1_fu_1163_p3 = {{a_re_2_reg_1432}, {15'd0}};

assign shl_ln_fu_1087_p3 = {{a_im_reg_1426}, {15'd0}};

assign start_out = real_start;

assign sub_ln63_1_fu_1075_p2 = ($signed(shl_ln63_1_fu_1068_p3) - $signed(sext_ln64_fu_1062_p1));

assign sub_ln64_2_fu_1170_p2 = (31'd0 - shl_ln64_1_fu_1163_p3);

assign sub_ln64_fu_1094_p2 = ($signed(shl_ln_fu_1087_p3) - $signed(sext_ln63_fu_1065_p1));

assign sum_im_1_fu_628_p2 = ($signed(sext_ln137_2_fu_611_p1) + $signed(sext_ln137_3_fu_615_p1));

assign sum_im_2_fu_943_p2 = ($signed(sext_ln137_4_fu_926_p1) + $signed(sext_ln137_5_fu_930_p1));

assign sum_im_3_fu_472_p2 = ($signed(sext_ln137_6_fu_455_p1) + $signed(sext_ln137_7_fu_459_p1));

assign sum_im_fu_785_p2 = ($signed(sext_ln137_fu_768_p1) + $signed(sext_ln137_1_fu_772_p1));

assign sum_re_1_fu_366_p2 = ($signed(sext_ln136_2_fu_349_p1) + $signed(sext_ln136_3_fu_353_p1));

assign sum_re_2_fu_916_p2 = ($signed(sext_ln136_4_fu_899_p1) + $signed(sext_ln136_5_fu_903_p1));

assign sum_re_3_fu_445_p2 = ($signed(sext_ln136_6_fu_428_p1) + $signed(sext_ln136_7_fu_432_p1));

assign sum_re_fu_758_p2 = ($signed(sext_ln136_fu_741_p1) + $signed(sext_ln136_1_fu_745_p1));

assign trunc_ln134_1_fu_372_p1 = sum_re_1_fu_366_p2[1:0];

assign trunc_ln134_2_fu_922_p1 = sum_re_2_fu_916_p2[1:0];

assign trunc_ln134_3_fu_451_p1 = sum_re_3_fu_445_p2[1:0];

assign trunc_ln134_fu_764_p1 = sum_re_fu_758_p2[1:0];

assign trunc_ln135_1_fu_634_p1 = sum_im_1_fu_628_p2[1:0];

assign trunc_ln135_2_fu_949_p1 = sum_im_2_fu_943_p2[1:0];

assign trunc_ln135_3_fu_478_p1 = sum_im_3_fu_472_p2[1:0];

assign trunc_ln135_fu_791_p1 = sum_im_fu_785_p2[1:0];

assign trunc_ln136_1_fu_362_p1 = diff_re_1_fu_356_p2[1:0];

assign trunc_ln136_2_fu_912_p1 = diff_re_2_fu_906_p2[1:0];

assign trunc_ln136_3_fu_441_p1 = diff_re_3_fu_435_p2[1:0];

assign trunc_ln136_fu_754_p1 = diff_re_fu_748_p2[1:0];

assign trunc_ln137_1_fu_624_p1 = diff_im_1_fu_618_p2[1:0];

assign trunc_ln137_2_fu_939_p1 = diff_im_2_fu_933_p2[1:0];

assign trunc_ln137_3_fu_468_p1 = diff_im_3_fu_462_p2[1:0];

assign trunc_ln137_fu_781_p1 = diff_im_fu_775_p2[1:0];

assign trunc_ln95_fu_219_p1 = ap_sig_allocacmp_cyc_1[0:0];

assign trunc_ln95_reg_1307_pp0_iter0_reg = trunc_ln95_reg_1307;

assign zext_ln53_10_fu_1011_p1 = icmp_ln53_10_fu_1005_p2;

assign zext_ln53_11_fu_1037_p1 = icmp_ln53_11_fu_1031_p2;

assign zext_ln53_12_fu_488_p1 = icmp_ln53_12_fu_482_p2;

assign zext_ln53_13_fu_514_p1 = icmp_ln53_13_fu_508_p2;

assign zext_ln53_14_fu_540_p1 = icmp_ln53_14_fu_534_p2;

assign zext_ln53_15_fu_566_p1 = icmp_ln53_15_fu_560_p2;

assign zext_ln53_1_fu_827_p1 = icmp_ln53_1_fu_821_p2;

assign zext_ln53_2_fu_853_p1 = icmp_ln53_2_fu_847_p2;

assign zext_ln53_3_fu_879_p1 = icmp_ln53_3_fu_873_p2;

assign zext_ln53_4_fu_382_p1 = icmp_ln53_4_fu_376_p2;

assign zext_ln53_5_fu_644_p1 = icmp_ln53_5_fu_638_p2;

assign zext_ln53_6_fu_408_p1 = icmp_ln53_6_fu_402_p2;

assign zext_ln53_7_fu_670_p1 = icmp_ln53_7_fu_664_p2;

assign zext_ln53_8_fu_959_p1 = icmp_ln53_8_fu_953_p2;

assign zext_ln53_9_fu_985_p1 = icmp_ln53_9_fu_979_p2;

assign zext_ln53_fu_801_p1 = icmp_ln53_fu_795_p2;

endmodule //fft_mdf_Loop_VITIS_LOOP_95_1_proc717
