-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_serial_fft_serial_Pipeline_bfly_loop17 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    re_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    re_ce0 : OUT STD_LOGIC;
    re_we0 : OUT STD_LOGIC;
    re_d0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    re_q0 : IN STD_LOGIC_VECTOR (16 downto 0);
    re_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    re_ce1 : OUT STD_LOGIC;
    re_we1 : OUT STD_LOGIC;
    re_d1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    re_q1 : IN STD_LOGIC_VECTOR (16 downto 0);
    re_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    re_1_ce0 : OUT STD_LOGIC;
    re_1_we0 : OUT STD_LOGIC;
    re_1_d0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    re_1_q0 : IN STD_LOGIC_VECTOR (16 downto 0);
    re_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    re_1_ce1 : OUT STD_LOGIC;
    re_1_we1 : OUT STD_LOGIC;
    re_1_d1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    re_1_q1 : IN STD_LOGIC_VECTOR (16 downto 0);
    clz_next_9 : IN STD_LOGIC_VECTOR (3 downto 0);
    im_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    im_ce0 : OUT STD_LOGIC;
    im_we0 : OUT STD_LOGIC;
    im_d0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    im_q0 : IN STD_LOGIC_VECTOR (16 downto 0);
    im_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    im_ce1 : OUT STD_LOGIC;
    im_we1 : OUT STD_LOGIC;
    im_d1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    im_q1 : IN STD_LOGIC_VECTOR (16 downto 0);
    im_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    im_1_ce0 : OUT STD_LOGIC;
    im_1_we0 : OUT STD_LOGIC;
    im_1_d0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    im_1_q0 : IN STD_LOGIC_VECTOR (16 downto 0);
    im_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    im_1_ce1 : OUT STD_LOGIC;
    im_1_we1 : OUT STD_LOGIC;
    im_1_d1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    im_1_q1 : IN STD_LOGIC_VECTOR (16 downto 0);
    TW_COS_LUT_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    TW_COS_LUT_ce0 : OUT STD_LOGIC;
    TW_COS_LUT_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    TW_SIN_LUT_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    TW_SIN_LUT_ce0 : OUT STD_LOGIC;
    TW_SIN_LUT_q0 : IN STD_LOGIC_VECTOR (14 downto 0) );
end;


architecture behav of fft_serial_fft_serial_Pipeline_bfly_loop17 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln132_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal icmp_ln132_reg_905 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln132_fu_276_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln132_reg_909 : STD_LOGIC_VECTOR (0 downto 0);
    signal re_addr_reg_917 : STD_LOGIC_VECTOR (8 downto 0);
    signal re_1_addr_reg_922 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln21_52_fu_418_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln21_52_reg_927 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_27_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_27_reg_932 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_28_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_28_reg_940 : STD_LOGIC_VECTOR (0 downto 0);
    signal im_addr_reg_948 : STD_LOGIC_VECTOR (8 downto 0);
    signal im_1_addr_reg_953 : STD_LOGIC_VECTOR (8 downto 0);
    signal re_addr_5_reg_958 : STD_LOGIC_VECTOR (8 downto 0);
    signal re_1_addr_5_reg_963 : STD_LOGIC_VECTOR (8 downto 0);
    signal im_addr_5_reg_968 : STD_LOGIC_VECTOR (8 downto 0);
    signal im_1_addr_5_reg_973 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln21_s_reg_978 : STD_LOGIC_VECTOR (1 downto 0);
    signal re_load_reg_995 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal re_1_load_reg_1000 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln21_fu_485_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln21_reg_1005 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_im_fu_624_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_im_reg_1012 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln159_fu_630_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln159_reg_1017 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln159_4_fu_634_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln159_4_reg_1023 : STD_LOGIC_VECTOR (31 downto 0);
    signal im_load_reg_1029 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal im_1_load_reg_1034 : STD_LOGIC_VECTOR (16 downto 0);
    signal v_21_fu_644_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal v_21_reg_1039 : STD_LOGIC_VECTOR (16 downto 0);
    signal b_im_16_fu_655_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal b_im_16_reg_1044 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln24_12_fu_659_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_12_reg_1049 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_im_17_fu_665_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal b_im_17_reg_1054 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln160_4_fu_670_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln160_4_reg_1059 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_re_19_fu_729_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_re_19_reg_1065 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal b_im_19_fu_759_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal b_im_19_reg_1070 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_im_19_fu_817_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_im_19_reg_1075 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal sext_ln160_fu_824_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln160_reg_1080 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln132_fu_290_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln141_fu_310_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln25_fu_474_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bfly_18_fu_124 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln132_fu_270_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_bfly : STD_LOGIC_VECTOR (9 downto 0);
    signal a_re_out_fu_839_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal b_re_out_fu_847_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal a_im_out_fu_867_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal b_im_out_fu_875_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal lshr_ln2_fu_280_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln141_8_cast_fu_302_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln21_26_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_25_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_24_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_23_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_22_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln21_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_fu_354_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln21_48_fu_368_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln21_10_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln21_11_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_49_fu_382_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln21_12_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_50_fu_396_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln21_51_fu_410_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal offset_fu_298_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln22_fu_456_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_448_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln23_fu_460_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal rom_addr_fu_466_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_20_fu_488_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln19_14_fu_495_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln24_11_fu_503_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln24_11_fu_509_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal rounded_14_fu_513_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal b_re_16_fu_499_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal b_re_17_fu_529_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal b_re_fu_519_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal b_re_18_fu_535_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln28_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln28_fu_562_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln28_fu_570_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln28_5_fu_580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln26_fu_553_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_re_21_fu_574_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln28_6_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln151_fu_549_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_re_22_fu_585_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln28_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal w_re_24_fu_612_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln151_3_fu_620_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal b_re_19_fu_542_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_re_23_fu_598_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal trunc_ln19_15_fu_651_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_673_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal v_fu_678_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln19_fu_683_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln24_fu_691_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln24_fu_697_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal rounded_fu_701_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal a_re_16_fu_687_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_re_17_fu_717_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_re_fu_707_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_re_18_fu_722_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln24_12_fu_736_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal rounded_15_fu_739_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal b_im_fu_744_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal b_im_18_fu_754_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal v_19_fu_766_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln19_13_fu_771_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln24_10_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln24_10_fu_785_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal rounded_13_fu_789_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal a_im_16_fu_775_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_im_17_fu_805_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_im_fu_795_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_im_18_fu_810_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_883_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal wb_re_s_fu_827_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln175_fu_836_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_891_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal wb_im_s_fu_855_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln176_fu_864_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_883_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_638_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_891_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_891_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_673_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_serial_mul_16s_16s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_serial_mac_mulsub_16s_16s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_serial_mac_muladd_16s_16s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_serial_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_16s_16s_32_4_1_U151 : component fft_serial_mul_16s_16s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => w_re_23_fu_598_p3,
        din1 => b_re_19_fu_542_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_638_p2);

    mul_16s_16s_32_4_1_U152 : component fft_serial_mul_16s_16s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => w_im_reg_1012,
        din1 => grp_fu_673_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_673_p2);

    mac_mulsub_16s_16s_32s_32_1_1_U153 : component fft_serial_mac_mulsub_16s_16s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_883_p0,
        din1 => b_im_19_reg_1070,
        din2 => grp_fu_638_p2,
        dout => grp_fu_883_p3);

    mac_muladd_16s_16s_32s_32_1_1_U154 : component fft_serial_mac_muladd_16s_16s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_891_p0,
        din1 => grp_fu_891_p1,
        din2 => grp_fu_673_p2,
        dout => grp_fu_891_p3);

    flow_control_loop_pipe_sequential_init_U : component fft_serial_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    bfly_18_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln132_fu_264_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    bfly_18_fu_124 <= add_ln132_fu_270_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    bfly_18_fu_124 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                a_im_19_reg_1075 <= a_im_19_fu_817_p3;
                sext_ln160_reg_1080 <= sext_ln160_fu_824_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                a_re_19_reg_1065 <= a_re_19_fu_729_p3;
                b_im_19_reg_1070 <= b_im_19_fu_759_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                b_im_16_reg_1044 <= b_im_16_fu_655_p1;
                b_im_17_reg_1054 <= b_im_17_fu_665_p2;
                icmp_ln24_12_reg_1049 <= icmp_ln24_12_fu_659_p2;
                sext_ln160_4_reg_1059 <= sext_ln160_4_fu_670_p1;
                v_21_reg_1039 <= v_21_fu_644_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln132_reg_905 <= icmp_ln132_fu_264_p2;
                icmp_ln21_27_reg_932 <= icmp_ln21_27_fu_426_p2;
                icmp_ln21_28_reg_940 <= icmp_ln21_28_fu_432_p2;
                    im_1_addr_5_reg_973(7 downto 0) <= zext_ln141_fu_310_p1(9 - 1 downto 0)(7 downto 0);
                    im_1_addr_reg_953(7 downto 0) <= zext_ln132_fu_290_p1(9 - 1 downto 0)(7 downto 0);
                    im_addr_5_reg_968(7 downto 0) <= zext_ln141_fu_310_p1(9 - 1 downto 0)(7 downto 0);
                    im_addr_reg_948(7 downto 0) <= zext_ln132_fu_290_p1(9 - 1 downto 0)(7 downto 0);
                    re_1_addr_5_reg_963(7 downto 0) <= zext_ln141_fu_310_p1(9 - 1 downto 0)(7 downto 0);
                    re_1_addr_reg_922(7 downto 0) <= zext_ln132_fu_290_p1(9 - 1 downto 0)(7 downto 0);
                    re_addr_5_reg_958(7 downto 0) <= zext_ln141_fu_310_p1(9 - 1 downto 0)(7 downto 0);
                    re_addr_reg_917(7 downto 0) <= zext_ln132_fu_290_p1(9 - 1 downto 0)(7 downto 0);
                select_ln21_52_reg_927 <= select_ln21_52_fu_418_p3;
                trunc_ln132_reg_909 <= trunc_ln132_fu_276_p1;
                trunc_ln21_s_reg_978 <= ap_sig_allocacmp_bfly(8 downto 7);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                im_1_load_reg_1034 <= im_1_q1;
                im_load_reg_1029 <= im_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                re_1_load_reg_1000 <= re_1_q1;
                re_load_reg_995 <= re_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                sext_ln159_4_reg_1023 <= sext_ln159_4_fu_634_p1;
                sext_ln159_reg_1017 <= sext_ln159_fu_630_p1;
                w_im_reg_1012 <= w_im_fu_624_p2;
                    zext_ln21_reg_1005(2 downto 0) <= zext_ln21_fu_485_p1(2 downto 0);
            end if;
        end if;
    end process;
    re_addr_reg_917(8) <= '0';
    re_1_addr_reg_922(8) <= '0';
    im_addr_reg_948(8) <= '0';
    im_1_addr_reg_953(8) <= '0';
    re_addr_5_reg_958(8) <= '1';
    re_1_addr_5_reg_963(8) <= '1';
    im_addr_5_reg_968(8) <= '1';
    im_1_addr_5_reg_973(8) <= '1';
    zext_ln21_reg_1005(15 downto 3) <= "0000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage4_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    TW_COS_LUT_address0 <= zext_ln25_fu_474_p1(8 - 1 downto 0);

    TW_COS_LUT_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            TW_COS_LUT_ce0 <= ap_const_logic_1;
        else 
            TW_COS_LUT_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    TW_SIN_LUT_address0 <= zext_ln25_fu_474_p1(8 - 1 downto 0);

    TW_SIN_LUT_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            TW_SIN_LUT_ce0 <= ap_const_logic_1;
        else 
            TW_SIN_LUT_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    a_im_16_fu_775_p1 <= v_19_fu_766_p3(16 - 1 downto 0);
    a_im_17_fu_805_p2 <= std_logic_vector(shift_left(unsigned(a_im_16_fu_775_p1),to_integer(unsigned('0' & zext_ln21_reg_1005(16-1 downto 0)))));
    a_im_18_fu_810_p3 <= 
        a_im_16_fu_775_p1 when (icmp_ln21_27_reg_932(0) = '1') else 
        a_im_17_fu_805_p2;
    a_im_19_fu_817_p3 <= 
        a_im_fu_795_p4 when (icmp_ln21_28_reg_940(0) = '1') else 
        a_im_18_fu_810_p3;
    a_im_fu_795_p4 <= rounded_13_fu_789_p2(16 downto 1);
    a_im_out_fu_867_p2 <= std_logic_vector(unsigned(wb_im_s_fu_855_p4) + unsigned(sext_ln176_fu_864_p1));
    a_re_16_fu_687_p1 <= v_fu_678_p3(16 - 1 downto 0);
    a_re_17_fu_717_p2 <= std_logic_vector(shift_left(unsigned(a_re_16_fu_687_p1),to_integer(unsigned('0' & zext_ln21_reg_1005(16-1 downto 0)))));
    a_re_18_fu_722_p3 <= 
        a_re_16_fu_687_p1 when (icmp_ln21_27_reg_932(0) = '1') else 
        a_re_17_fu_717_p2;
    a_re_19_fu_729_p3 <= 
        a_re_fu_707_p4 when (icmp_ln21_28_reg_940(0) = '1') else 
        a_re_18_fu_722_p3;
    a_re_fu_707_p4 <= rounded_fu_701_p2(16 downto 1);
    a_re_out_fu_839_p2 <= std_logic_vector(unsigned(wb_re_s_fu_827_p4) + unsigned(sext_ln175_fu_836_p1));
    add_ln132_fu_270_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_bfly) + unsigned(ap_const_lv10_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln132_fu_264_p2)
    begin
        if (((icmp_ln132_fu_264_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_bfly_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, bfly_18_fu_124, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_bfly <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_bfly <= bfly_18_fu_124;
        end if; 
    end process;

    b_im_16_fu_655_p1 <= v_21_fu_644_p3(16 - 1 downto 0);
    b_im_17_fu_665_p2 <= std_logic_vector(shift_left(unsigned(b_im_16_fu_655_p1),to_integer(unsigned('0' & zext_ln21_reg_1005(16-1 downto 0)))));
    b_im_18_fu_754_p3 <= 
        b_im_16_reg_1044 when (icmp_ln21_27_reg_932(0) = '1') else 
        b_im_17_reg_1054;
    b_im_19_fu_759_p3 <= 
        b_im_fu_744_p4 when (icmp_ln21_28_reg_940(0) = '1') else 
        b_im_18_fu_754_p3;
    b_im_fu_744_p4 <= rounded_15_fu_739_p2(16 downto 1);
    b_im_out_fu_875_p2 <= std_logic_vector(signed(sext_ln176_fu_864_p1) - signed(wb_im_s_fu_855_p4));
    b_re_16_fu_499_p1 <= v_20_fu_488_p3(16 - 1 downto 0);
    b_re_17_fu_529_p2 <= std_logic_vector(shift_left(unsigned(b_re_16_fu_499_p1),to_integer(unsigned('0' & zext_ln21_fu_485_p1(16-1 downto 0)))));
    b_re_18_fu_535_p3 <= 
        b_re_16_fu_499_p1 when (icmp_ln21_27_reg_932(0) = '1') else 
        b_re_17_fu_529_p2;
    b_re_19_fu_542_p3 <= 
        b_re_fu_519_p4 when (icmp_ln21_28_reg_940(0) = '1') else 
        b_re_18_fu_535_p3;
    b_re_fu_519_p4 <= rounded_14_fu_513_p2(16 downto 1);
    b_re_out_fu_847_p2 <= std_logic_vector(signed(sext_ln175_fu_836_p1) - signed(wb_re_s_fu_827_p4));
    grp_fu_673_p1 <= sext_ln159_reg_1017(16 - 1 downto 0);
    grp_fu_883_p0 <= sext_ln160_4_reg_1059(16 - 1 downto 0);
    grp_fu_891_p0 <= sext_ln159_4_reg_1023(16 - 1 downto 0);
    grp_fu_891_p1 <= sext_ln160_reg_1080(16 - 1 downto 0);
    icmp_ln132_fu_264_p2 <= "1" when (ap_sig_allocacmp_bfly = ap_const_lv10_200) else "0";
    icmp_ln21_22_fu_324_p2 <= "1" when (clz_next_9 = ap_const_lv4_6) else "0";
    icmp_ln21_23_fu_330_p2 <= "1" when (clz_next_9 = ap_const_lv4_5) else "0";
    icmp_ln21_24_fu_336_p2 <= "1" when (clz_next_9 = ap_const_lv4_4) else "0";
    icmp_ln21_25_fu_342_p2 <= "1" when (clz_next_9 = ap_const_lv4_3) else "0";
    icmp_ln21_26_fu_348_p2 <= "1" when (clz_next_9 = ap_const_lv4_2) else "0";
    icmp_ln21_27_fu_426_p2 <= "1" when (clz_next_9 = ap_const_lv4_1) else "0";
    icmp_ln21_28_fu_432_p2 <= "1" when (clz_next_9 = ap_const_lv4_0) else "0";
    icmp_ln21_fu_318_p2 <= "1" when (clz_next_9 = ap_const_lv4_7) else "0";
    icmp_ln24_10_fu_779_p2 <= "1" when (trunc_ln19_13_fu_771_p1 = ap_const_lv2_3) else "0";
    icmp_ln24_11_fu_503_p2 <= "1" when (trunc_ln19_14_fu_495_p1 = ap_const_lv2_3) else "0";
    icmp_ln24_12_fu_659_p2 <= "1" when (trunc_ln19_15_fu_651_p1 = ap_const_lv2_3) else "0";
    icmp_ln24_fu_691_p2 <= "1" when (trunc_ln19_fu_683_p1 = ap_const_lv2_3) else "0";
    icmp_ln28_5_fu_580_p2 <= "1" when (trunc_ln21_s_reg_978 = ap_const_lv2_1) else "0";
    icmp_ln28_6_fu_593_p2 <= "1" when (trunc_ln21_s_reg_978 = ap_const_lv2_0) else "0";
    icmp_ln28_fu_557_p2 <= "1" when (trunc_ln21_s_reg_978 = ap_const_lv2_2) else "0";
    im_1_address0 <= im_1_addr_5_reg_973;
    im_1_address1 <= im_1_addr_reg_953;

    im_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            im_1_ce0 <= ap_const_logic_1;
        else 
            im_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    im_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            im_1_ce1 <= ap_const_logic_1;
        else 
            im_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    im_1_d0 <= b_im_out_fu_875_p2;
    im_1_d1 <= a_im_out_fu_867_p2;

    im_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln132_reg_909)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln132_reg_909 = ap_const_lv1_1))) then 
            im_1_we0 <= ap_const_logic_1;
        else 
            im_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    im_1_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln132_reg_909)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln132_reg_909 = ap_const_lv1_1))) then 
            im_1_we1 <= ap_const_logic_1;
        else 
            im_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    im_address0 <= im_addr_5_reg_968;
    im_address1 <= im_addr_reg_948;

    im_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            im_ce0 <= ap_const_logic_1;
        else 
            im_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    im_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            im_ce1 <= ap_const_logic_1;
        else 
            im_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    im_d0 <= b_im_out_fu_875_p2;
    im_d1 <= a_im_out_fu_867_p2;

    im_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln132_reg_909)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln132_reg_909 = ap_const_lv1_0))) then 
            im_we0 <= ap_const_logic_1;
        else 
            im_we0 <= ap_const_logic_0;
        end if; 
    end process;


    im_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln132_reg_909)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln132_reg_909 = ap_const_lv1_0))) then 
            im_we1 <= ap_const_logic_1;
        else 
            im_we1 <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln2_fu_280_p4 <= ap_sig_allocacmp_bfly(8 downto 1);
    offset_fu_298_p1 <= ap_sig_allocacmp_bfly(7 - 1 downto 0);
    or_ln21_10_fu_376_p2 <= (icmp_ln21_24_fu_336_p2 or icmp_ln21_23_fu_330_p2);
    or_ln21_11_fu_390_p2 <= (icmp_ln21_fu_318_p2 or icmp_ln21_22_fu_324_p2);
    or_ln21_12_fu_404_p2 <= (or_ln21_fu_362_p2 or or_ln21_10_fu_376_p2);
    or_ln21_fu_362_p2 <= (icmp_ln21_26_fu_348_p2 or icmp_ln21_25_fu_342_p2);
    or_ln28_fu_606_p2 <= (icmp_ln28_fu_557_p2 or icmp_ln28_5_fu_580_p2);

    re_1_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, re_1_addr_5_reg_963, ap_block_pp0_stage0, zext_ln141_fu_310_p1, ap_block_pp0_stage4)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                re_1_address0 <= re_1_addr_5_reg_963;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                re_1_address0 <= zext_ln141_fu_310_p1(9 - 1 downto 0);
            else 
                re_1_address0 <= "XXXXXXXXX";
            end if;
        else 
            re_1_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    re_1_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, re_1_addr_reg_922, zext_ln132_fu_290_p1, ap_block_pp0_stage0, ap_block_pp0_stage4)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                re_1_address1 <= re_1_addr_reg_922;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                re_1_address1 <= zext_ln132_fu_290_p1(9 - 1 downto 0);
            else 
                re_1_address1 <= "XXXXXXXXX";
            end if;
        else 
            re_1_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    re_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            re_1_ce0 <= ap_const_logic_1;
        else 
            re_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    re_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            re_1_ce1 <= ap_const_logic_1;
        else 
            re_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    re_1_d0 <= b_re_out_fu_847_p2;
    re_1_d1 <= a_re_out_fu_839_p2;

    re_1_we0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, icmp_ln132_reg_905, trunc_ln132_reg_909, ap_block_pp0_stage4_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (trunc_ln132_reg_909 = ap_const_lv1_1) and (icmp_ln132_reg_905 = ap_const_lv1_0))) then 
            re_1_we0 <= ap_const_logic_1;
        else 
            re_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    re_1_we1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, icmp_ln132_reg_905, trunc_ln132_reg_909, ap_block_pp0_stage4_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (trunc_ln132_reg_909 = ap_const_lv1_1) and (icmp_ln132_reg_905 = ap_const_lv1_0))) then 
            re_1_we1 <= ap_const_logic_1;
        else 
            re_1_we1 <= ap_const_logic_0;
        end if; 
    end process;


    re_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, re_addr_5_reg_958, ap_block_pp0_stage0, zext_ln141_fu_310_p1, ap_block_pp0_stage4)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                re_address0 <= re_addr_5_reg_958;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                re_address0 <= zext_ln141_fu_310_p1(9 - 1 downto 0);
            else 
                re_address0 <= "XXXXXXXXX";
            end if;
        else 
            re_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    re_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, re_addr_reg_917, zext_ln132_fu_290_p1, ap_block_pp0_stage0, ap_block_pp0_stage4)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                re_address1 <= re_addr_reg_917;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                re_address1 <= zext_ln132_fu_290_p1(9 - 1 downto 0);
            else 
                re_address1 <= "XXXXXXXXX";
            end if;
        else 
            re_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    re_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            re_ce0 <= ap_const_logic_1;
        else 
            re_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    re_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            re_ce1 <= ap_const_logic_1;
        else 
            re_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    re_d0 <= b_re_out_fu_847_p2;
    re_d1 <= a_re_out_fu_839_p2;

    re_we0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, icmp_ln132_reg_905, trunc_ln132_reg_909, ap_block_pp0_stage4_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (trunc_ln132_reg_909 = ap_const_lv1_0) and (icmp_ln132_reg_905 = ap_const_lv1_0))) then 
            re_we0 <= ap_const_logic_1;
        else 
            re_we0 <= ap_const_logic_0;
        end if; 
    end process;


    re_we1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, icmp_ln132_reg_905, trunc_ln132_reg_909, ap_block_pp0_stage4_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (trunc_ln132_reg_909 = ap_const_lv1_0) and (icmp_ln132_reg_905 = ap_const_lv1_0))) then 
            re_we1 <= ap_const_logic_1;
        else 
            re_we1 <= ap_const_logic_0;
        end if; 
    end process;

    rom_addr_fu_466_p3 <= 
        sub_ln23_fu_460_p2 when (tmp_fu_448_p3(0) = '1') else 
        zext_ln22_fu_456_p1;
    rounded_13_fu_789_p2 <= std_logic_vector(unsigned(v_19_fu_766_p3) + unsigned(zext_ln24_10_fu_785_p1));
    rounded_14_fu_513_p2 <= std_logic_vector(unsigned(v_20_fu_488_p3) + unsigned(zext_ln24_11_fu_509_p1));
    rounded_15_fu_739_p2 <= std_logic_vector(unsigned(v_21_reg_1039) + unsigned(zext_ln24_12_fu_736_p1));
    rounded_fu_701_p2 <= std_logic_vector(unsigned(v_fu_678_p3) + unsigned(zext_ln24_fu_697_p1));
    select_ln21_48_fu_368_p3 <= 
        ap_const_lv3_3 when (icmp_ln21_24_fu_336_p2(0) = '1') else 
        ap_const_lv3_4;
    select_ln21_49_fu_382_p3 <= 
        ap_const_lv3_5 when (icmp_ln21_22_fu_324_p2(0) = '1') else 
        ap_const_lv3_6;
    select_ln21_50_fu_396_p3 <= 
        select_ln21_fu_354_p3 when (or_ln21_fu_362_p2(0) = '1') else 
        select_ln21_48_fu_368_p3;
    select_ln21_51_fu_410_p3 <= 
        select_ln21_49_fu_382_p3 when (or_ln21_11_fu_390_p2(0) = '1') else 
        ap_const_lv3_7;
    select_ln21_52_fu_418_p3 <= 
        select_ln21_50_fu_396_p3 when (or_ln21_12_fu_404_p2(0) = '1') else 
        select_ln21_51_fu_410_p3;
    select_ln21_fu_354_p3 <= 
        ap_const_lv3_1 when (icmp_ln21_26_fu_348_p2(0) = '1') else 
        ap_const_lv3_2;
    select_ln28_fu_562_p3 <= 
        TW_SIN_LUT_q0 when (icmp_ln28_fu_557_p2(0) = '1') else 
        TW_COS_LUT_q0;
        sext_ln159_4_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_re_23_fu_598_p3),32));

        sext_ln159_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(b_re_19_fu_542_p3),32));

        sext_ln160_4_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_im_reg_1012),32));

        sext_ln160_fu_824_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(b_im_19_reg_1070),32));

        sext_ln175_fu_836_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_re_19_reg_1065),17));

        sext_ln176_fu_864_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_im_19_reg_1075),17));

    sub_ln23_fu_460_p2 <= std_logic_vector(signed(ap_const_lv8_80) - signed(zext_ln22_fu_456_p1));
    tmp_fu_448_p3 <= ap_sig_allocacmp_bfly(7 downto 7);
    trunc_ln132_fu_276_p1 <= ap_sig_allocacmp_bfly(1 - 1 downto 0);
    trunc_ln19_13_fu_771_p1 <= v_19_fu_766_p3(2 - 1 downto 0);
    trunc_ln19_14_fu_495_p1 <= v_20_fu_488_p3(2 - 1 downto 0);
    trunc_ln19_15_fu_651_p1 <= v_21_fu_644_p3(2 - 1 downto 0);
    trunc_ln19_fu_683_p1 <= v_fu_678_p3(2 - 1 downto 0);
    v_19_fu_766_p3 <= 
        im_1_load_reg_1034 when (trunc_ln132_reg_909(0) = '1') else 
        im_load_reg_1029;
    v_20_fu_488_p3 <= 
        re_1_q0 when (trunc_ln132_reg_909(0) = '1') else 
        re_q0;
    v_21_fu_644_p3 <= 
        im_1_q0 when (trunc_ln132_reg_909(0) = '1') else 
        im_q0;
    v_fu_678_p3 <= 
        re_1_load_reg_1000 when (trunc_ln132_reg_909(0) = '1') else 
        re_load_reg_995;
    w_im_fu_624_p2 <= (zext_ln151_3_fu_620_p1 xor ap_const_lv16_FFFF);
    w_re_21_fu_574_p2 <= (zext_ln28_fu_570_p1 xor ap_const_lv16_FFFF);
    w_re_22_fu_585_p3 <= 
        zext_ln26_fu_553_p1 when (icmp_ln28_5_fu_580_p2(0) = '1') else 
        w_re_21_fu_574_p2;
    w_re_23_fu_598_p3 <= 
        zext_ln151_fu_549_p1 when (icmp_ln28_6_fu_593_p2(0) = '1') else 
        w_re_22_fu_585_p3;
    w_re_24_fu_612_p3 <= 
        TW_COS_LUT_q0 when (or_ln28_fu_606_p2(0) = '1') else 
        TW_SIN_LUT_q0;
    wb_im_s_fu_855_p4 <= grp_fu_891_p3(31 downto 15);
    wb_re_s_fu_827_p4 <= grp_fu_883_p3(31 downto 15);
    zext_ln132_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_280_p4),64));
    zext_ln141_8_cast_fu_302_p3 <= (ap_const_lv1_1 & lshr_ln2_fu_280_p4);
    zext_ln141_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln141_8_cast_fu_302_p3),64));
    zext_ln151_3_fu_620_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(w_re_24_fu_612_p3),16));
    zext_ln151_fu_549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(TW_COS_LUT_q0),16));
    zext_ln21_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln21_52_reg_927),16));
    zext_ln22_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(offset_fu_298_p1),8));
    zext_ln24_10_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln24_10_fu_779_p2),17));
    zext_ln24_11_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln24_11_fu_503_p2),17));
    zext_ln24_12_fu_736_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln24_12_reg_1049),17));
    zext_ln24_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln24_fu_691_p2),17));
    zext_ln25_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rom_addr_fu_466_p3),64));
    zext_ln26_fu_553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(TW_SIN_LUT_q0),16));
    zext_ln28_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln28_fu_562_p3),16));
end behav;
