// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_serial_fft_serial_Pipeline_bfly_loop13 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        re_address0,
        re_ce0,
        re_we0,
        re_d0,
        re_q0,
        re_address1,
        re_ce1,
        re_we1,
        re_d1,
        re_q1,
        re_1_address0,
        re_1_ce0,
        re_1_we0,
        re_1_d0,
        re_1_q0,
        re_1_address1,
        re_1_ce1,
        re_1_we1,
        re_1_d1,
        re_1_q1,
        clz_next_7,
        im_address0,
        im_ce0,
        im_we0,
        im_d0,
        im_q0,
        im_address1,
        im_ce1,
        im_we1,
        im_d1,
        im_q1,
        im_1_address0,
        im_1_ce0,
        im_1_we0,
        im_1_d0,
        im_1_q0,
        im_1_address1,
        im_1_ce1,
        im_1_we1,
        im_1_d1,
        im_1_q1,
        TW_COS_LUT_address0,
        TW_COS_LUT_ce0,
        TW_COS_LUT_q0,
        TW_SIN_LUT_address0,
        TW_SIN_LUT_ce0,
        TW_SIN_LUT_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] re_address0;
output   re_ce0;
output   re_we0;
output  [16:0] re_d0;
input  [16:0] re_q0;
output  [8:0] re_address1;
output   re_ce1;
output   re_we1;
output  [16:0] re_d1;
input  [16:0] re_q1;
output  [8:0] re_1_address0;
output   re_1_ce0;
output   re_1_we0;
output  [16:0] re_1_d0;
input  [16:0] re_1_q0;
output  [8:0] re_1_address1;
output   re_1_ce1;
output   re_1_we1;
output  [16:0] re_1_d1;
input  [16:0] re_1_q1;
input  [3:0] clz_next_7;
output  [8:0] im_address0;
output   im_ce0;
output   im_we0;
output  [16:0] im_d0;
input  [16:0] im_q0;
output  [8:0] im_address1;
output   im_ce1;
output   im_we1;
output  [16:0] im_d1;
input  [16:0] im_q1;
output  [8:0] im_1_address0;
output   im_1_ce0;
output   im_1_we0;
output  [16:0] im_1_d0;
input  [16:0] im_1_q0;
output  [8:0] im_1_address1;
output   im_1_ce1;
output   im_1_we1;
output  [16:0] im_1_d1;
input  [16:0] im_1_q1;
output  [7:0] TW_COS_LUT_address0;
output   TW_COS_LUT_ce0;
input  [14:0] TW_COS_LUT_q0;
output  [7:0] TW_SIN_LUT_address0;
output   TW_SIN_LUT_ce0;
input  [14:0] TW_SIN_LUT_q0;

reg ap_idle;
reg[8:0] re_address0;
reg re_ce0;
reg re_we0;
reg[8:0] re_address1;
reg re_ce1;
reg re_we1;
reg[8:0] re_1_address0;
reg re_1_ce0;
reg re_1_we0;
reg[8:0] re_1_address1;
reg re_1_ce1;
reg re_1_we1;
reg im_ce0;
reg im_we0;
reg im_ce1;
reg im_we1;
reg im_1_ce0;
reg im_1_we0;
reg im_1_ce1;
reg im_1_we1;
reg TW_COS_LUT_ce0;
reg TW_SIN_LUT_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln132_fu_272_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln132_reg_939;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln132_fu_284_p1;
reg   [0:0] trunc_ln132_reg_943;
reg   [8:0] re_addr_reg_951;
reg   [8:0] re_1_addr_reg_956;
wire   [2:0] select_ln21_78_fu_452_p3;
reg   [2:0] select_ln21_78_reg_961;
wire   [0:0] icmp_ln21_41_fu_460_p2;
reg   [0:0] icmp_ln21_41_reg_966;
wire   [0:0] icmp_ln21_42_fu_466_p2;
reg   [0:0] icmp_ln21_42_reg_974;
reg   [8:0] im_addr_reg_982;
reg   [8:0] im_1_addr_reg_987;
reg   [8:0] re_addr_7_reg_992;
reg   [8:0] re_1_addr_7_reg_997;
reg   [8:0] im_addr_7_reg_1002;
reg   [8:0] im_1_addr_7_reg_1007;
reg   [1:0] trunc_ln21_8_reg_1012;
reg   [16:0] re_load_reg_1029;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [16:0] re_1_load_reg_1034;
wire   [15:0] zext_ln21_fu_519_p1;
reg   [15:0] zext_ln21_reg_1039;
wire   [15:0] w_im_fu_658_p2;
reg  signed [15:0] w_im_reg_1046;
wire  signed [31:0] sext_ln159_fu_664_p1;
reg  signed [31:0] sext_ln159_reg_1051;
wire  signed [31:0] sext_ln159_6_fu_668_p1;
reg  signed [31:0] sext_ln159_6_reg_1057;
reg   [16:0] im_load_reg_1063;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [16:0] im_1_load_reg_1068;
wire   [16:0] v_27_fu_678_p3;
reg   [16:0] v_27_reg_1073;
wire   [15:0] b_im_24_fu_689_p1;
reg   [15:0] b_im_24_reg_1078;
wire   [0:0] icmp_ln24_18_fu_693_p2;
reg   [0:0] icmp_ln24_18_reg_1083;
wire   [15:0] b_im_25_fu_699_p2;
reg   [15:0] b_im_25_reg_1088;
wire  signed [31:0] sext_ln160_6_fu_704_p1;
reg  signed [31:0] sext_ln160_6_reg_1093;
wire   [15:0] a_re_27_fu_763_p3;
reg   [15:0] a_re_27_reg_1099;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire   [15:0] b_im_27_fu_793_p3;
reg  signed [15:0] b_im_27_reg_1104;
wire   [15:0] a_im_27_fu_851_p3;
reg   [15:0] a_im_27_reg_1109;
wire    ap_block_pp0_stage4_11001;
wire  signed [31:0] sext_ln160_fu_858_p1;
reg  signed [31:0] sext_ln160_reg_1114;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln140_fu_318_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln141_fu_332_p1;
wire   [63:0] zext_ln25_fu_508_p1;
reg   [9:0] bfly_fu_132;
wire   [9:0] bfly_10_fu_278_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_bfly_9;
wire   [16:0] a_re_out_fu_873_p2;
wire    ap_block_pp0_stage4;
wire   [16:0] b_re_out_fu_881_p2;
wire    ap_block_pp0_stage1;
wire   [16:0] a_im_out_fu_901_p2;
wire   [16:0] b_im_out_fu_909_p2;
wire   [1:0] tmp_s_fu_288_p4;
wire   [5:0] tmp_3_fu_298_p4;
wire   [8:0] lshr_ln140_5_fu_308_p4;
wire   [8:0] or_ln141_fu_326_p2;
wire   [4:0] trunc_ln142_fu_340_p1;
wire   [0:0] icmp_ln21_40_fu_382_p2;
wire   [0:0] icmp_ln21_39_fu_376_p2;
wire   [0:0] icmp_ln21_38_fu_370_p2;
wire   [0:0] icmp_ln21_37_fu_364_p2;
wire   [0:0] icmp_ln21_36_fu_358_p2;
wire   [0:0] icmp_ln21_fu_352_p2;
wire   [0:0] or_ln21_fu_396_p2;
wire   [2:0] select_ln21_fu_388_p3;
wire   [2:0] select_ln21_74_fu_402_p3;
wire   [0:0] or_ln21_16_fu_410_p2;
wire   [0:0] or_ln21_17_fu_424_p2;
wire   [2:0] select_ln21_75_fu_416_p3;
wire   [0:0] or_ln21_18_fu_438_p2;
wire   [2:0] select_ln21_76_fu_430_p3;
wire   [2:0] select_ln21_77_fu_444_p3;
wire   [6:0] tw_n_fu_344_p3;
wire   [7:0] zext_ln22_fu_490_p1;
wire   [0:0] tmp_fu_482_p3;
wire   [7:0] sub_ln23_fu_494_p2;
wire   [7:0] rom_addr_fu_500_p3;
wire   [16:0] v_26_fu_522_p3;
wire   [1:0] trunc_ln19_20_fu_529_p1;
wire   [0:0] icmp_ln24_17_fu_537_p2;
wire   [16:0] zext_ln24_17_fu_543_p1;
wire   [16:0] rounded_20_fu_547_p2;
wire   [15:0] b_re_24_fu_533_p1;
wire   [15:0] b_re_25_fu_563_p2;
wire   [15:0] b_re_fu_553_p4;
wire   [15:0] b_re_26_fu_569_p3;
wire   [0:0] icmp_ln28_fu_591_p2;
wire   [14:0] select_ln28_fu_596_p3;
wire   [15:0] zext_ln28_fu_604_p1;
wire   [0:0] icmp_ln28_9_fu_614_p2;
wire   [15:0] zext_ln26_fu_587_p1;
wire   [15:0] w_re_31_fu_608_p2;
wire   [0:0] icmp_ln28_10_fu_627_p2;
wire   [15:0] zext_ln151_fu_583_p1;
wire   [15:0] w_re_32_fu_619_p3;
wire   [0:0] or_ln28_fu_640_p2;
wire   [14:0] w_re_34_fu_646_p3;
wire   [15:0] zext_ln151_5_fu_654_p1;
wire  signed [15:0] b_re_27_fu_576_p3;
wire  signed [15:0] w_re_33_fu_632_p3;
wire    ap_block_pp0_stage2;
wire   [1:0] trunc_ln19_21_fu_685_p1;
wire  signed [15:0] grp_fu_707_p1;
wire    ap_block_pp0_stage3;
wire   [16:0] v_fu_712_p3;
wire   [1:0] trunc_ln19_fu_717_p1;
wire   [0:0] icmp_ln24_fu_725_p2;
wire   [16:0] zext_ln24_fu_731_p1;
wire   [16:0] rounded_fu_735_p2;
wire   [15:0] a_re_24_fu_721_p1;
wire   [15:0] a_re_25_fu_751_p2;
wire   [15:0] a_re_fu_741_p4;
wire   [15:0] a_re_26_fu_756_p3;
wire   [16:0] zext_ln24_18_fu_770_p1;
wire   [16:0] rounded_21_fu_773_p2;
wire   [15:0] b_im_fu_778_p4;
wire   [15:0] b_im_26_fu_788_p3;
wire   [16:0] v_25_fu_800_p3;
wire   [1:0] trunc_ln19_19_fu_805_p1;
wire   [0:0] icmp_ln24_16_fu_813_p2;
wire   [16:0] zext_ln24_16_fu_819_p1;
wire   [16:0] rounded_19_fu_823_p2;
wire   [15:0] a_im_24_fu_809_p1;
wire   [15:0] a_im_25_fu_839_p2;
wire   [15:0] a_im_fu_829_p4;
wire   [15:0] a_im_26_fu_844_p3;
wire  signed [31:0] grp_fu_917_p3;
wire   [16:0] wb_re_s_fu_861_p4;
wire  signed [16:0] sext_ln175_fu_870_p1;
wire  signed [31:0] grp_fu_925_p3;
wire   [16:0] wb_im_s_fu_889_p4;
wire  signed [16:0] sext_ln176_fu_898_p1;
wire  signed [15:0] grp_fu_917_p0;
wire  signed [31:0] grp_fu_672_p2;
wire  signed [15:0] grp_fu_925_p0;
wire  signed [15:0] grp_fu_925_p1;
wire  signed [31:0] grp_fu_707_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 bfly_fu_132 = 10'd0;
#0 ap_done_reg = 1'b0;
end

fft_serial_mul_16s_16s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_4_1_U119(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_re_33_fu_632_p3),
    .din1(b_re_27_fu_576_p3),
    .ce(1'b1),
    .dout(grp_fu_672_p2)
);

fft_serial_mul_16s_16s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_4_1_U120(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_im_reg_1046),
    .din1(grp_fu_707_p1),
    .ce(1'b1),
    .dout(grp_fu_707_p2)
);

fft_serial_mac_mulsub_16s_16s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_mulsub_16s_16s_32s_32_1_1_U121(
    .din0(grp_fu_917_p0),
    .din1(b_im_27_reg_1104),
    .din2(grp_fu_672_p2),
    .dout(grp_fu_917_p3)
);

fft_serial_mac_muladd_16s_16s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_1_1_U122(
    .din0(grp_fu_925_p0),
    .din1(grp_fu_925_p1),
    .din2(grp_fu_707_p2),
    .dout(grp_fu_925_p3)
);

fft_serial_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln132_fu_272_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            bfly_fu_132 <= bfly_10_fu_278_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            bfly_fu_132 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        a_im_27_reg_1109 <= a_im_27_fu_851_p3;
        sext_ln160_reg_1114 <= sext_ln160_fu_858_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        a_re_27_reg_1099 <= a_re_27_fu_763_p3;
        b_im_27_reg_1104 <= b_im_27_fu_793_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_im_24_reg_1078 <= b_im_24_fu_689_p1;
        b_im_25_reg_1088 <= b_im_25_fu_699_p2;
        icmp_ln24_18_reg_1083 <= icmp_ln24_18_fu_693_p2;
        sext_ln160_6_reg_1093 <= sext_ln160_6_fu_704_p1;
        v_27_reg_1073 <= v_27_fu_678_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln132_reg_939 <= icmp_ln132_fu_272_p2;
        icmp_ln21_41_reg_966 <= icmp_ln21_41_fu_460_p2;
        icmp_ln21_42_reg_974 <= icmp_ln21_42_fu_466_p2;
        im_1_addr_7_reg_1007[5 : 0] <= zext_ln141_fu_332_p1[5 : 0];
im_1_addr_7_reg_1007[8 : 7] <= zext_ln141_fu_332_p1[8 : 7];
        im_1_addr_reg_987[5 : 0] <= zext_ln140_fu_318_p1[5 : 0];
im_1_addr_reg_987[8 : 7] <= zext_ln140_fu_318_p1[8 : 7];
        im_addr_7_reg_1002[5 : 0] <= zext_ln141_fu_332_p1[5 : 0];
im_addr_7_reg_1002[8 : 7] <= zext_ln141_fu_332_p1[8 : 7];
        im_addr_reg_982[5 : 0] <= zext_ln140_fu_318_p1[5 : 0];
im_addr_reg_982[8 : 7] <= zext_ln140_fu_318_p1[8 : 7];
        re_1_addr_7_reg_997[5 : 0] <= zext_ln141_fu_332_p1[5 : 0];
re_1_addr_7_reg_997[8 : 7] <= zext_ln141_fu_332_p1[8 : 7];
        re_1_addr_reg_956[5 : 0] <= zext_ln140_fu_318_p1[5 : 0];
re_1_addr_reg_956[8 : 7] <= zext_ln140_fu_318_p1[8 : 7];
        re_addr_7_reg_992[5 : 0] <= zext_ln141_fu_332_p1[5 : 0];
re_addr_7_reg_992[8 : 7] <= zext_ln141_fu_332_p1[8 : 7];
        re_addr_reg_951[5 : 0] <= zext_ln140_fu_318_p1[5 : 0];
re_addr_reg_951[8 : 7] <= zext_ln140_fu_318_p1[8 : 7];
        select_ln21_78_reg_961 <= select_ln21_78_fu_452_p3;
        trunc_ln132_reg_943 <= trunc_ln132_fu_284_p1;
        trunc_ln21_8_reg_1012 <= {{ap_sig_allocacmp_bfly_9[6:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        im_1_load_reg_1068 <= im_1_q1;
        im_load_reg_1063 <= im_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        re_1_load_reg_1034 <= re_1_q1;
        re_load_reg_1029 <= re_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sext_ln159_6_reg_1057 <= sext_ln159_6_fu_668_p1;
        sext_ln159_reg_1051 <= sext_ln159_fu_664_p1;
        w_im_reg_1046 <= w_im_fu_658_p2;
        zext_ln21_reg_1039[2 : 0] <= zext_ln21_fu_519_p1[2 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW_COS_LUT_ce0 = 1'b1;
    end else begin
        TW_COS_LUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW_SIN_LUT_ce0 = 1'b1;
    end else begin
        TW_SIN_LUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln132_fu_272_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_bfly_9 = 10'd0;
    end else begin
        ap_sig_allocacmp_bfly_9 = bfly_fu_132;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_1_ce0 = 1'b1;
    end else begin
        im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_1_ce1 = 1'b1;
    end else begin
        im_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_943 == 1'd1))) begin
        im_1_we0 = 1'b1;
    end else begin
        im_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_943 == 1'd1))) begin
        im_1_we1 = 1'b1;
    end else begin
        im_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_ce0 = 1'b1;
    end else begin
        im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_ce1 = 1'b1;
    end else begin
        im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_943 == 1'd0))) begin
        im_we0 = 1'b1;
    end else begin
        im_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_943 == 1'd0))) begin
        im_we1 = 1'b1;
    end else begin
        im_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_1_address0 = re_1_addr_7_reg_997;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_1_address0 = zext_ln141_fu_332_p1;
        end else begin
            re_1_address0 = 'bx;
        end
    end else begin
        re_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_1_address1 = re_1_addr_reg_956;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_1_address1 = zext_ln140_fu_318_p1;
        end else begin
            re_1_address1 = 'bx;
        end
    end else begin
        re_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_1_ce0 = 1'b1;
    end else begin
        re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_1_ce1 = 1'b1;
    end else begin
        re_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_943 == 1'd1) & (icmp_ln132_reg_939 == 1'd0))) begin
        re_1_we0 = 1'b1;
    end else begin
        re_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_943 == 1'd1) & (icmp_ln132_reg_939 == 1'd0))) begin
        re_1_we1 = 1'b1;
    end else begin
        re_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_address0 = re_addr_7_reg_992;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_address0 = zext_ln141_fu_332_p1;
        end else begin
            re_address0 = 'bx;
        end
    end else begin
        re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_address1 = re_addr_reg_951;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_address1 = zext_ln140_fu_318_p1;
        end else begin
            re_address1 = 'bx;
        end
    end else begin
        re_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_ce0 = 1'b1;
    end else begin
        re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_ce1 = 1'b1;
    end else begin
        re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_943 == 1'd0) & (icmp_ln132_reg_939 == 1'd0))) begin
        re_we0 = 1'b1;
    end else begin
        re_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_943 == 1'd0) & (icmp_ln132_reg_939 == 1'd0))) begin
        re_we1 = 1'b1;
    end else begin
        re_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign TW_COS_LUT_address0 = zext_ln25_fu_508_p1;

assign TW_SIN_LUT_address0 = zext_ln25_fu_508_p1;

assign a_im_24_fu_809_p1 = v_25_fu_800_p3[15:0];

assign a_im_25_fu_839_p2 = a_im_24_fu_809_p1 << zext_ln21_reg_1039;

assign a_im_26_fu_844_p3 = ((icmp_ln21_41_reg_966[0:0] == 1'b1) ? a_im_24_fu_809_p1 : a_im_25_fu_839_p2);

assign a_im_27_fu_851_p3 = ((icmp_ln21_42_reg_974[0:0] == 1'b1) ? a_im_fu_829_p4 : a_im_26_fu_844_p3);

assign a_im_fu_829_p4 = {{rounded_19_fu_823_p2[16:1]}};

assign a_im_out_fu_901_p2 = ($signed(wb_im_s_fu_889_p4) + $signed(sext_ln176_fu_898_p1));

assign a_re_24_fu_721_p1 = v_fu_712_p3[15:0];

assign a_re_25_fu_751_p2 = a_re_24_fu_721_p1 << zext_ln21_reg_1039;

assign a_re_26_fu_756_p3 = ((icmp_ln21_41_reg_966[0:0] == 1'b1) ? a_re_24_fu_721_p1 : a_re_25_fu_751_p2);

assign a_re_27_fu_763_p3 = ((icmp_ln21_42_reg_974[0:0] == 1'b1) ? a_re_fu_741_p4 : a_re_26_fu_756_p3);

assign a_re_fu_741_p4 = {{rounded_fu_735_p2[16:1]}};

assign a_re_out_fu_873_p2 = ($signed(wb_re_s_fu_861_p4) + $signed(sext_ln175_fu_870_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_im_24_fu_689_p1 = v_27_fu_678_p3[15:0];

assign b_im_25_fu_699_p2 = b_im_24_fu_689_p1 << zext_ln21_reg_1039;

assign b_im_26_fu_788_p3 = ((icmp_ln21_41_reg_966[0:0] == 1'b1) ? b_im_24_reg_1078 : b_im_25_reg_1088);

assign b_im_27_fu_793_p3 = ((icmp_ln21_42_reg_974[0:0] == 1'b1) ? b_im_fu_778_p4 : b_im_26_fu_788_p3);

assign b_im_fu_778_p4 = {{rounded_21_fu_773_p2[16:1]}};

assign b_im_out_fu_909_p2 = ($signed(sext_ln176_fu_898_p1) - $signed(wb_im_s_fu_889_p4));

assign b_re_24_fu_533_p1 = v_26_fu_522_p3[15:0];

assign b_re_25_fu_563_p2 = b_re_24_fu_533_p1 << zext_ln21_fu_519_p1;

assign b_re_26_fu_569_p3 = ((icmp_ln21_41_reg_966[0:0] == 1'b1) ? b_re_24_fu_533_p1 : b_re_25_fu_563_p2);

assign b_re_27_fu_576_p3 = ((icmp_ln21_42_reg_974[0:0] == 1'b1) ? b_re_fu_553_p4 : b_re_26_fu_569_p3);

assign b_re_fu_553_p4 = {{rounded_20_fu_547_p2[16:1]}};

assign b_re_out_fu_881_p2 = ($signed(sext_ln175_fu_870_p1) - $signed(wb_re_s_fu_861_p4));

assign bfly_10_fu_278_p2 = (ap_sig_allocacmp_bfly_9 + 10'd1);

assign grp_fu_707_p1 = sext_ln159_reg_1051;

assign grp_fu_917_p0 = sext_ln160_6_reg_1093;

assign grp_fu_925_p0 = sext_ln159_6_reg_1057;

assign grp_fu_925_p1 = sext_ln160_reg_1114;

assign icmp_ln132_fu_272_p2 = ((ap_sig_allocacmp_bfly_9 == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln21_36_fu_358_p2 = ((clz_next_7 == 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln21_37_fu_364_p2 = ((clz_next_7 == 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln21_38_fu_370_p2 = ((clz_next_7 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln21_39_fu_376_p2 = ((clz_next_7 == 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln21_40_fu_382_p2 = ((clz_next_7 == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln21_41_fu_460_p2 = ((clz_next_7 == 4'd1) ? 1'b1 : 1'b0);

assign icmp_ln21_42_fu_466_p2 = ((clz_next_7 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_352_p2 = ((clz_next_7 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln24_16_fu_813_p2 = ((trunc_ln19_19_fu_805_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_17_fu_537_p2 = ((trunc_ln19_20_fu_529_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_18_fu_693_p2 = ((trunc_ln19_21_fu_685_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_725_p2 = ((trunc_ln19_fu_717_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln28_10_fu_627_p2 = ((trunc_ln21_8_reg_1012 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_9_fu_614_p2 = ((trunc_ln21_8_reg_1012 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_591_p2 = ((trunc_ln21_8_reg_1012 == 2'd2) ? 1'b1 : 1'b0);

assign im_1_address0 = im_1_addr_7_reg_1007;

assign im_1_address1 = im_1_addr_reg_987;

assign im_1_d0 = b_im_out_fu_909_p2;

assign im_1_d1 = a_im_out_fu_901_p2;

assign im_address0 = im_addr_7_reg_1002;

assign im_address1 = im_addr_reg_982;

assign im_d0 = b_im_out_fu_909_p2;

assign im_d1 = a_im_out_fu_901_p2;

assign lshr_ln140_5_fu_308_p4 = {{{tmp_s_fu_288_p4}, {1'd0}}, {tmp_3_fu_298_p4}};

assign or_ln141_fu_326_p2 = (lshr_ln140_5_fu_308_p4 | 9'd64);

assign or_ln21_16_fu_410_p2 = (icmp_ln21_38_fu_370_p2 | icmp_ln21_37_fu_364_p2);

assign or_ln21_17_fu_424_p2 = (icmp_ln21_fu_352_p2 | icmp_ln21_36_fu_358_p2);

assign or_ln21_18_fu_438_p2 = (or_ln21_fu_396_p2 | or_ln21_16_fu_410_p2);

assign or_ln21_fu_396_p2 = (icmp_ln21_40_fu_382_p2 | icmp_ln21_39_fu_376_p2);

assign or_ln28_fu_640_p2 = (icmp_ln28_fu_591_p2 | icmp_ln28_9_fu_614_p2);

assign re_1_d0 = b_re_out_fu_881_p2;

assign re_1_d1 = a_re_out_fu_873_p2;

assign re_d0 = b_re_out_fu_881_p2;

assign re_d1 = a_re_out_fu_873_p2;

assign rom_addr_fu_500_p3 = ((tmp_fu_482_p3[0:0] == 1'b1) ? sub_ln23_fu_494_p2 : zext_ln22_fu_490_p1);

assign rounded_19_fu_823_p2 = (v_25_fu_800_p3 + zext_ln24_16_fu_819_p1);

assign rounded_20_fu_547_p2 = (v_26_fu_522_p3 + zext_ln24_17_fu_543_p1);

assign rounded_21_fu_773_p2 = (v_27_reg_1073 + zext_ln24_18_fu_770_p1);

assign rounded_fu_735_p2 = (v_fu_712_p3 + zext_ln24_fu_731_p1);

assign select_ln21_74_fu_402_p3 = ((icmp_ln21_38_fu_370_p2[0:0] == 1'b1) ? 3'd3 : 3'd4);

assign select_ln21_75_fu_416_p3 = ((icmp_ln21_36_fu_358_p2[0:0] == 1'b1) ? 3'd5 : 3'd6);

assign select_ln21_76_fu_430_p3 = ((or_ln21_fu_396_p2[0:0] == 1'b1) ? select_ln21_fu_388_p3 : select_ln21_74_fu_402_p3);

assign select_ln21_77_fu_444_p3 = ((or_ln21_17_fu_424_p2[0:0] == 1'b1) ? select_ln21_75_fu_416_p3 : 3'd7);

assign select_ln21_78_fu_452_p3 = ((or_ln21_18_fu_438_p2[0:0] == 1'b1) ? select_ln21_76_fu_430_p3 : select_ln21_77_fu_444_p3);

assign select_ln21_fu_388_p3 = ((icmp_ln21_40_fu_382_p2[0:0] == 1'b1) ? 3'd1 : 3'd2);

assign select_ln28_fu_596_p3 = ((icmp_ln28_fu_591_p2[0:0] == 1'b1) ? TW_SIN_LUT_q0 : TW_COS_LUT_q0);

assign sext_ln159_6_fu_668_p1 = w_re_33_fu_632_p3;

assign sext_ln159_fu_664_p1 = b_re_27_fu_576_p3;

assign sext_ln160_6_fu_704_p1 = w_im_reg_1046;

assign sext_ln160_fu_858_p1 = b_im_27_reg_1104;

assign sext_ln175_fu_870_p1 = $signed(a_re_27_reg_1099);

assign sext_ln176_fu_898_p1 = $signed(a_im_27_reg_1109);

assign sub_ln23_fu_494_p2 = ($signed(8'd128) - $signed(zext_ln22_fu_490_p1));

assign tmp_3_fu_298_p4 = {{ap_sig_allocacmp_bfly_9[6:1]}};

assign tmp_fu_482_p3 = ap_sig_allocacmp_bfly_9[32'd5];

assign tmp_s_fu_288_p4 = {{ap_sig_allocacmp_bfly_9[8:7]}};

assign trunc_ln132_fu_284_p1 = ap_sig_allocacmp_bfly_9[0:0];

assign trunc_ln142_fu_340_p1 = ap_sig_allocacmp_bfly_9[4:0];

assign trunc_ln19_19_fu_805_p1 = v_25_fu_800_p3[1:0];

assign trunc_ln19_20_fu_529_p1 = v_26_fu_522_p3[1:0];

assign trunc_ln19_21_fu_685_p1 = v_27_fu_678_p3[1:0];

assign trunc_ln19_fu_717_p1 = v_fu_712_p3[1:0];

assign tw_n_fu_344_p3 = {{trunc_ln142_fu_340_p1}, {2'd0}};

assign v_25_fu_800_p3 = ((trunc_ln132_reg_943[0:0] == 1'b1) ? im_1_load_reg_1068 : im_load_reg_1063);

assign v_26_fu_522_p3 = ((trunc_ln132_reg_943[0:0] == 1'b1) ? re_1_q0 : re_q0);

assign v_27_fu_678_p3 = ((trunc_ln132_reg_943[0:0] == 1'b1) ? im_1_q0 : im_q0);

assign v_fu_712_p3 = ((trunc_ln132_reg_943[0:0] == 1'b1) ? re_1_load_reg_1034 : re_load_reg_1029);

assign w_im_fu_658_p2 = (zext_ln151_5_fu_654_p1 ^ 16'd65535);

assign w_re_31_fu_608_p2 = (zext_ln28_fu_604_p1 ^ 16'd65535);

assign w_re_32_fu_619_p3 = ((icmp_ln28_9_fu_614_p2[0:0] == 1'b1) ? zext_ln26_fu_587_p1 : w_re_31_fu_608_p2);

assign w_re_33_fu_632_p3 = ((icmp_ln28_10_fu_627_p2[0:0] == 1'b1) ? zext_ln151_fu_583_p1 : w_re_32_fu_619_p3);

assign w_re_34_fu_646_p3 = ((or_ln28_fu_640_p2[0:0] == 1'b1) ? TW_COS_LUT_q0 : TW_SIN_LUT_q0);

assign wb_im_s_fu_889_p4 = {{grp_fu_925_p3[31:15]}};

assign wb_re_s_fu_861_p4 = {{grp_fu_917_p3[31:15]}};

assign zext_ln140_fu_318_p1 = lshr_ln140_5_fu_308_p4;

assign zext_ln141_fu_332_p1 = or_ln141_fu_326_p2;

assign zext_ln151_5_fu_654_p1 = w_re_34_fu_646_p3;

assign zext_ln151_fu_583_p1 = TW_COS_LUT_q0;

assign zext_ln21_fu_519_p1 = select_ln21_78_reg_961;

assign zext_ln22_fu_490_p1 = tw_n_fu_344_p3;

assign zext_ln24_16_fu_819_p1 = icmp_ln24_16_fu_813_p2;

assign zext_ln24_17_fu_543_p1 = icmp_ln24_17_fu_537_p2;

assign zext_ln24_18_fu_770_p1 = icmp_ln24_18_reg_1083;

assign zext_ln24_fu_731_p1 = icmp_ln24_fu_725_p2;

assign zext_ln25_fu_508_p1 = rom_addr_fu_500_p3;

assign zext_ln26_fu_587_p1 = TW_SIN_LUT_q0;

assign zext_ln28_fu_604_p1 = select_ln28_fu_596_p3;

always @ (posedge ap_clk) begin
    re_addr_reg_951[6] <= 1'b0;
    re_1_addr_reg_956[6] <= 1'b0;
    im_addr_reg_982[6] <= 1'b0;
    im_1_addr_reg_987[6] <= 1'b0;
    re_addr_7_reg_992[6] <= 1'b1;
    re_1_addr_7_reg_997[6] <= 1'b1;
    im_addr_7_reg_1002[6] <= 1'b1;
    im_1_addr_7_reg_1007[6] <= 1'b1;
    zext_ln21_reg_1039[15:3] <= 13'b0000000000000;
end

endmodule //fft_serial_fft_serial_Pipeline_bfly_loop13
