// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_serial_fft_serial_Pipeline_bfly_loop3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        re_address0,
        re_ce0,
        re_we0,
        re_d0,
        re_q0,
        re_address1,
        re_ce1,
        re_we1,
        re_d1,
        re_q1,
        re_1_address0,
        re_1_ce0,
        re_1_we0,
        re_1_d0,
        re_1_q0,
        re_1_address1,
        re_1_ce1,
        re_1_we1,
        re_1_d1,
        re_1_q1,
        clz_next_2,
        im_address0,
        im_ce0,
        im_we0,
        im_d0,
        im_q0,
        im_address1,
        im_ce1,
        im_we1,
        im_d1,
        im_q1,
        im_1_address0,
        im_1_ce0,
        im_1_we0,
        im_1_d0,
        im_1_q0,
        im_1_address1,
        im_1_ce1,
        im_1_we1,
        im_1_d1,
        im_1_q1,
        TW_COS_LUT_address0,
        TW_COS_LUT_ce0,
        TW_COS_LUT_q0,
        TW_SIN_LUT_address0,
        TW_SIN_LUT_ce0,
        TW_SIN_LUT_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] re_address0;
output   re_ce0;
output   re_we0;
output  [16:0] re_d0;
input  [16:0] re_q0;
output  [8:0] re_address1;
output   re_ce1;
output   re_we1;
output  [16:0] re_d1;
input  [16:0] re_q1;
output  [8:0] re_1_address0;
output   re_1_ce0;
output   re_1_we0;
output  [16:0] re_1_d0;
input  [16:0] re_1_q0;
output  [8:0] re_1_address1;
output   re_1_ce1;
output   re_1_we1;
output  [16:0] re_1_d1;
input  [16:0] re_1_q1;
input  [3:0] clz_next_2;
output  [8:0] im_address0;
output   im_ce0;
output   im_we0;
output  [16:0] im_d0;
input  [16:0] im_q0;
output  [8:0] im_address1;
output   im_ce1;
output   im_we1;
output  [16:0] im_d1;
input  [16:0] im_q1;
output  [8:0] im_1_address0;
output   im_1_ce0;
output   im_1_we0;
output  [16:0] im_1_d0;
input  [16:0] im_1_q0;
output  [8:0] im_1_address1;
output   im_1_ce1;
output   im_1_we1;
output  [16:0] im_1_d1;
input  [16:0] im_1_q1;
output  [7:0] TW_COS_LUT_address0;
output   TW_COS_LUT_ce0;
input  [14:0] TW_COS_LUT_q0;
output  [7:0] TW_SIN_LUT_address0;
output   TW_SIN_LUT_ce0;
input  [14:0] TW_SIN_LUT_q0;

reg ap_idle;
reg[8:0] re_address0;
reg re_ce0;
reg re_we0;
reg[8:0] re_address1;
reg re_ce1;
reg re_we1;
reg[8:0] re_1_address0;
reg re_1_ce0;
reg re_1_we0;
reg[8:0] re_1_address1;
reg re_1_ce1;
reg re_1_we1;
reg im_ce0;
reg im_we0;
reg im_ce1;
reg im_we1;
reg im_1_ce0;
reg im_1_we0;
reg im_1_ce1;
reg im_1_we1;
reg TW_COS_LUT_ce0;
reg TW_SIN_LUT_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln132_fu_264_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln132_reg_889;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln132_fu_276_p1;
reg   [0:0] trunc_ln132_reg_893;
wire   [1:0] j_fu_280_p1;
reg   [1:0] j_reg_901;
reg   [8:0] re_addr_reg_908;
reg   [8:0] re_1_addr_reg_913;
wire   [2:0] select_ln21_19_fu_434_p3;
reg   [2:0] select_ln21_19_reg_918;
wire   [0:0] icmp_ln21_14_fu_442_p2;
reg   [0:0] icmp_ln21_14_reg_923;
wire   [0:0] icmp_ln21_15_fu_448_p2;
reg   [0:0] icmp_ln21_15_reg_931;
reg   [8:0] im_addr_reg_939;
reg   [8:0] im_1_addr_reg_944;
reg   [8:0] re_addr_4_reg_949;
reg   [8:0] re_1_addr_4_reg_954;
reg   [8:0] im_addr_4_reg_959;
reg   [8:0] im_1_addr_4_reg_964;
reg   [16:0] re_load_reg_979;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [16:0] re_1_load_reg_984;
wire   [15:0] zext_ln21_fu_469_p1;
reg   [15:0] zext_ln21_reg_989;
wire   [15:0] w_im_fu_608_p2;
reg  signed [15:0] w_im_reg_996;
wire  signed [31:0] sext_ln159_3_fu_614_p1;
reg  signed [31:0] sext_ln159_3_reg_1001;
wire  signed [31:0] sext_ln159_fu_618_p1;
reg  signed [31:0] sext_ln159_reg_1007;
reg   [16:0] im_load_reg_1013;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [16:0] im_1_load_reg_1018;
wire   [16:0] v_17_fu_628_p3;
reg   [16:0] v_17_reg_1023;
wire   [15:0] b_im_fu_639_p1;
reg   [15:0] b_im_reg_1028;
wire   [0:0] icmp_ln24_7_fu_643_p2;
reg   [0:0] icmp_ln24_7_reg_1033;
wire   [15:0] b_im_13_fu_649_p2;
reg   [15:0] b_im_13_reg_1038;
wire  signed [31:0] sext_ln160_3_fu_654_p1;
reg  signed [31:0] sext_ln160_3_reg_1043;
wire   [15:0] a_re_15_fu_713_p3;
reg   [15:0] a_re_15_reg_1049;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire   [15:0] b_im_15_fu_743_p3;
reg  signed [15:0] b_im_15_reg_1054;
wire   [15:0] a_im_15_fu_801_p3;
reg   [15:0] a_im_15_reg_1059;
wire    ap_block_pp0_stage4_11001;
wire  signed [31:0] sext_ln160_2_fu_808_p1;
reg  signed [31:0] sext_ln160_2_reg_1064;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln140_fu_312_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln141_fu_326_p1;
wire   [63:0] select_ln25_fu_454_p3;
reg   [9:0] bfly_3_fu_124;
wire   [9:0] bfly_6_fu_270_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_bfly;
wire   [16:0] a_re_out_fu_823_p2;
wire    ap_block_pp0_stage4;
wire   [16:0] b_re_out_fu_831_p2;
wire    ap_block_pp0_stage1;
wire   [16:0] a_im_out_fu_851_p2;
wire   [16:0] b_im_out_fu_859_p2;
wire   [6:0] tmp_3_fu_284_p4;
wire   [0:0] tmp_fu_294_p3;
wire   [8:0] lshr_ln1_fu_302_p4;
wire   [8:0] or_ln141_fu_320_p2;
wire   [0:0] icmp_ln21_13_fu_364_p2;
wire   [0:0] icmp_ln21_12_fu_358_p2;
wire   [0:0] icmp_ln21_11_fu_352_p2;
wire   [0:0] icmp_ln21_10_fu_346_p2;
wire   [0:0] icmp_ln21_9_fu_340_p2;
wire   [0:0] icmp_ln21_8_fu_334_p2;
wire   [0:0] or_ln21_4_fu_378_p2;
wire   [2:0] select_ln21_fu_370_p3;
wire   [2:0] select_ln21_15_fu_384_p3;
wire   [0:0] or_ln21_5_fu_392_p2;
wire   [0:0] or_ln21_6_fu_406_p2;
wire   [2:0] select_ln21_16_fu_398_p3;
wire   [0:0] or_ln21_7_fu_420_p2;
wire   [2:0] select_ln21_17_fu_412_p3;
wire   [2:0] select_ln21_18_fu_426_p3;
wire   [16:0] v_16_fu_472_p3;
wire   [1:0] trunc_ln19_11_fu_479_p1;
wire   [0:0] icmp_ln24_6_fu_487_p2;
wire   [16:0] zext_ln24_6_fu_493_p1;
wire   [16:0] rounded_11_fu_497_p2;
wire   [15:0] b_re_fu_483_p1;
wire   [15:0] b_re_13_fu_513_p2;
wire   [15:0] b_re_6_fu_503_p4;
wire   [15:0] b_re_14_fu_519_p3;
wire   [0:0] icmp_ln28_fu_541_p2;
wire   [14:0] select_ln28_fu_546_p3;
wire   [15:0] zext_ln28_fu_554_p1;
wire   [0:0] icmp_ln28_1_fu_564_p2;
wire   [15:0] zext_ln26_fu_537_p1;
wire   [15:0] w_re_16_fu_558_p2;
wire   [0:0] icmp_ln28_2_fu_577_p2;
wire   [15:0] zext_ln151_fu_533_p1;
wire   [15:0] w_re_17_fu_569_p3;
wire   [0:0] or_ln28_fu_590_p2;
wire   [14:0] w_re_19_fu_596_p3;
wire   [15:0] zext_ln151_1_fu_604_p1;
wire  signed [15:0] b_re_15_fu_526_p3;
wire  signed [15:0] w_re_18_fu_582_p3;
wire    ap_block_pp0_stage2;
wire   [1:0] trunc_ln19_12_fu_635_p1;
wire  signed [15:0] grp_fu_657_p1;
wire    ap_block_pp0_stage3;
wire   [16:0] v_12_fu_662_p3;
wire   [1:0] trunc_ln19_fu_667_p1;
wire   [0:0] icmp_ln24_4_fu_675_p2;
wire   [16:0] zext_ln24_4_fu_681_p1;
wire   [16:0] rounded_fu_685_p2;
wire   [15:0] a_re_fu_671_p1;
wire   [15:0] a_re_13_fu_701_p2;
wire   [15:0] a_re_6_fu_691_p4;
wire   [15:0] a_re_14_fu_706_p3;
wire   [16:0] zext_ln24_7_fu_720_p1;
wire   [16:0] rounded_12_fu_723_p2;
wire   [15:0] b_im_6_fu_728_p4;
wire   [15:0] b_im_14_fu_738_p3;
wire   [16:0] v_15_fu_750_p3;
wire   [1:0] trunc_ln19_10_fu_755_p1;
wire   [0:0] icmp_ln24_5_fu_763_p2;
wire   [16:0] zext_ln24_5_fu_769_p1;
wire   [16:0] rounded_10_fu_773_p2;
wire   [15:0] a_im_fu_759_p1;
wire   [15:0] a_im_13_fu_789_p2;
wire   [15:0] a_im_6_fu_779_p4;
wire   [15:0] a_im_14_fu_794_p3;
wire  signed [31:0] grp_fu_867_p3;
wire   [16:0] wb_re_s_fu_811_p4;
wire  signed [16:0] sext_ln175_fu_820_p1;
wire  signed [31:0] grp_fu_875_p3;
wire   [16:0] wb_im_s_fu_839_p4;
wire  signed [16:0] sext_ln176_fu_848_p1;
wire  signed [15:0] grp_fu_867_p0;
wire  signed [31:0] grp_fu_622_p2;
wire  signed [15:0] grp_fu_875_p0;
wire  signed [15:0] grp_fu_875_p1;
wire  signed [31:0] grp_fu_657_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 bfly_3_fu_124 = 10'd0;
#0 ap_done_reg = 1'b0;
end

fft_serial_mul_16s_16s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_4_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_re_18_fu_582_p3),
    .din1(b_re_15_fu_526_p3),
    .ce(1'b1),
    .dout(grp_fu_622_p2)
);

fft_serial_mul_16s_16s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_4_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_im_reg_996),
    .din1(grp_fu_657_p1),
    .ce(1'b1),
    .dout(grp_fu_657_p2)
);

fft_serial_mac_mulsub_16s_16s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_mulsub_16s_16s_32s_32_1_1_U39(
    .din0(grp_fu_867_p0),
    .din1(b_im_15_reg_1054),
    .din2(grp_fu_622_p2),
    .dout(grp_fu_867_p3)
);

fft_serial_mac_muladd_16s_16s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_1_1_U40(
    .din0(grp_fu_875_p0),
    .din1(grp_fu_875_p1),
    .din2(grp_fu_657_p2),
    .dout(grp_fu_875_p3)
);

fft_serial_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln132_fu_264_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            bfly_3_fu_124 <= bfly_6_fu_270_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            bfly_3_fu_124 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        a_im_15_reg_1059 <= a_im_15_fu_801_p3;
        sext_ln160_2_reg_1064 <= sext_ln160_2_fu_808_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        a_re_15_reg_1049 <= a_re_15_fu_713_p3;
        b_im_15_reg_1054 <= b_im_15_fu_743_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_im_13_reg_1038 <= b_im_13_fu_649_p2;
        b_im_reg_1028 <= b_im_fu_639_p1;
        icmp_ln24_7_reg_1033 <= icmp_ln24_7_fu_643_p2;
        sext_ln160_3_reg_1043 <= sext_ln160_3_fu_654_p1;
        v_17_reg_1023 <= v_17_fu_628_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln132_reg_889 <= icmp_ln132_fu_264_p2;
        icmp_ln21_14_reg_923 <= icmp_ln21_14_fu_442_p2;
        icmp_ln21_15_reg_931 <= icmp_ln21_15_fu_448_p2;
        im_1_addr_4_reg_964[0] <= zext_ln141_fu_326_p1[0];
im_1_addr_4_reg_964[8 : 2] <= zext_ln141_fu_326_p1[8 : 2];
        im_1_addr_reg_944[0] <= zext_ln140_fu_312_p1[0];
im_1_addr_reg_944[8 : 2] <= zext_ln140_fu_312_p1[8 : 2];
        im_addr_4_reg_959[0] <= zext_ln141_fu_326_p1[0];
im_addr_4_reg_959[8 : 2] <= zext_ln141_fu_326_p1[8 : 2];
        im_addr_reg_939[0] <= zext_ln140_fu_312_p1[0];
im_addr_reg_939[8 : 2] <= zext_ln140_fu_312_p1[8 : 2];
        j_reg_901 <= j_fu_280_p1;
        re_1_addr_4_reg_954[0] <= zext_ln141_fu_326_p1[0];
re_1_addr_4_reg_954[8 : 2] <= zext_ln141_fu_326_p1[8 : 2];
        re_1_addr_reg_913[0] <= zext_ln140_fu_312_p1[0];
re_1_addr_reg_913[8 : 2] <= zext_ln140_fu_312_p1[8 : 2];
        re_addr_4_reg_949[0] <= zext_ln141_fu_326_p1[0];
re_addr_4_reg_949[8 : 2] <= zext_ln141_fu_326_p1[8 : 2];
        re_addr_reg_908[0] <= zext_ln140_fu_312_p1[0];
re_addr_reg_908[8 : 2] <= zext_ln140_fu_312_p1[8 : 2];
        select_ln21_19_reg_918 <= select_ln21_19_fu_434_p3;
        trunc_ln132_reg_893 <= trunc_ln132_fu_276_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        im_1_load_reg_1018 <= im_1_q1;
        im_load_reg_1013 <= im_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        re_1_load_reg_984 <= re_1_q1;
        re_load_reg_979 <= re_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sext_ln159_3_reg_1001 <= sext_ln159_3_fu_614_p1;
        sext_ln159_reg_1007 <= sext_ln159_fu_618_p1;
        w_im_reg_996 <= w_im_fu_608_p2;
        zext_ln21_reg_989[2 : 0] <= zext_ln21_fu_469_p1[2 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW_COS_LUT_ce0 = 1'b1;
    end else begin
        TW_COS_LUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW_SIN_LUT_ce0 = 1'b1;
    end else begin
        TW_SIN_LUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln132_fu_264_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_bfly = 10'd0;
    end else begin
        ap_sig_allocacmp_bfly = bfly_3_fu_124;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_1_ce0 = 1'b1;
    end else begin
        im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_1_ce1 = 1'b1;
    end else begin
        im_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_893 == 1'd1))) begin
        im_1_we0 = 1'b1;
    end else begin
        im_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_893 == 1'd1))) begin
        im_1_we1 = 1'b1;
    end else begin
        im_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_ce0 = 1'b1;
    end else begin
        im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        im_ce1 = 1'b1;
    end else begin
        im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_893 == 1'd0))) begin
        im_we0 = 1'b1;
    end else begin
        im_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln132_reg_893 == 1'd0))) begin
        im_we1 = 1'b1;
    end else begin
        im_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_1_address0 = re_1_addr_4_reg_954;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_1_address0 = zext_ln141_fu_326_p1;
        end else begin
            re_1_address0 = 'bx;
        end
    end else begin
        re_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_1_address1 = re_1_addr_reg_913;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_1_address1 = zext_ln140_fu_312_p1;
        end else begin
            re_1_address1 = 'bx;
        end
    end else begin
        re_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_1_ce0 = 1'b1;
    end else begin
        re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_1_ce1 = 1'b1;
    end else begin
        re_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_893 == 1'd1) & (icmp_ln132_reg_889 == 1'd0))) begin
        re_1_we0 = 1'b1;
    end else begin
        re_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_893 == 1'd1) & (icmp_ln132_reg_889 == 1'd0))) begin
        re_1_we1 = 1'b1;
    end else begin
        re_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_address0 = re_addr_4_reg_949;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_address0 = zext_ln141_fu_326_p1;
        end else begin
            re_address0 = 'bx;
        end
    end else begin
        re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            re_address1 = re_addr_reg_908;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            re_address1 = zext_ln140_fu_312_p1;
        end else begin
            re_address1 = 'bx;
        end
    end else begin
        re_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_ce0 = 1'b1;
    end else begin
        re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        re_ce1 = 1'b1;
    end else begin
        re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_893 == 1'd0) & (icmp_ln132_reg_889 == 1'd0))) begin
        re_we0 = 1'b1;
    end else begin
        re_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (trunc_ln132_reg_893 == 1'd0) & (icmp_ln132_reg_889 == 1'd0))) begin
        re_we1 = 1'b1;
    end else begin
        re_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign TW_COS_LUT_address0 = select_ln25_fu_454_p3;

assign TW_SIN_LUT_address0 = select_ln25_fu_454_p3;

assign a_im_13_fu_789_p2 = a_im_fu_759_p1 << zext_ln21_reg_989;

assign a_im_14_fu_794_p3 = ((icmp_ln21_14_reg_923[0:0] == 1'b1) ? a_im_fu_759_p1 : a_im_13_fu_789_p2);

assign a_im_15_fu_801_p3 = ((icmp_ln21_15_reg_931[0:0] == 1'b1) ? a_im_6_fu_779_p4 : a_im_14_fu_794_p3);

assign a_im_6_fu_779_p4 = {{rounded_10_fu_773_p2[16:1]}};

assign a_im_fu_759_p1 = v_15_fu_750_p3[15:0];

assign a_im_out_fu_851_p2 = ($signed(wb_im_s_fu_839_p4) + $signed(sext_ln176_fu_848_p1));

assign a_re_13_fu_701_p2 = a_re_fu_671_p1 << zext_ln21_reg_989;

assign a_re_14_fu_706_p3 = ((icmp_ln21_14_reg_923[0:0] == 1'b1) ? a_re_fu_671_p1 : a_re_13_fu_701_p2);

assign a_re_15_fu_713_p3 = ((icmp_ln21_15_reg_931[0:0] == 1'b1) ? a_re_6_fu_691_p4 : a_re_14_fu_706_p3);

assign a_re_6_fu_691_p4 = {{rounded_fu_685_p2[16:1]}};

assign a_re_fu_671_p1 = v_12_fu_662_p3[15:0];

assign a_re_out_fu_823_p2 = ($signed(wb_re_s_fu_811_p4) + $signed(sext_ln175_fu_820_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_im_13_fu_649_p2 = b_im_fu_639_p1 << zext_ln21_reg_989;

assign b_im_14_fu_738_p3 = ((icmp_ln21_14_reg_923[0:0] == 1'b1) ? b_im_reg_1028 : b_im_13_reg_1038);

assign b_im_15_fu_743_p3 = ((icmp_ln21_15_reg_931[0:0] == 1'b1) ? b_im_6_fu_728_p4 : b_im_14_fu_738_p3);

assign b_im_6_fu_728_p4 = {{rounded_12_fu_723_p2[16:1]}};

assign b_im_fu_639_p1 = v_17_fu_628_p3[15:0];

assign b_im_out_fu_859_p2 = ($signed(sext_ln176_fu_848_p1) - $signed(wb_im_s_fu_839_p4));

assign b_re_13_fu_513_p2 = b_re_fu_483_p1 << zext_ln21_fu_469_p1;

assign b_re_14_fu_519_p3 = ((icmp_ln21_14_reg_923[0:0] == 1'b1) ? b_re_fu_483_p1 : b_re_13_fu_513_p2);

assign b_re_15_fu_526_p3 = ((icmp_ln21_15_reg_931[0:0] == 1'b1) ? b_re_6_fu_503_p4 : b_re_14_fu_519_p3);

assign b_re_6_fu_503_p4 = {{rounded_11_fu_497_p2[16:1]}};

assign b_re_fu_483_p1 = v_16_fu_472_p3[15:0];

assign b_re_out_fu_831_p2 = ($signed(sext_ln175_fu_820_p1) - $signed(wb_re_s_fu_811_p4));

assign bfly_6_fu_270_p2 = (ap_sig_allocacmp_bfly + 10'd1);

assign grp_fu_657_p1 = sext_ln159_3_reg_1001;

assign grp_fu_867_p0 = sext_ln160_3_reg_1043;

assign grp_fu_875_p0 = sext_ln159_reg_1007;

assign grp_fu_875_p1 = sext_ln160_2_reg_1064;

assign icmp_ln132_fu_264_p2 = ((ap_sig_allocacmp_bfly == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln21_10_fu_346_p2 = ((clz_next_2 == 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln21_11_fu_352_p2 = ((clz_next_2 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln21_12_fu_358_p2 = ((clz_next_2 == 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln21_13_fu_364_p2 = ((clz_next_2 == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln21_14_fu_442_p2 = ((clz_next_2 == 4'd1) ? 1'b1 : 1'b0);

assign icmp_ln21_15_fu_448_p2 = ((clz_next_2 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln21_8_fu_334_p2 = ((clz_next_2 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln21_9_fu_340_p2 = ((clz_next_2 == 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln24_4_fu_675_p2 = ((trunc_ln19_fu_667_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_5_fu_763_p2 = ((trunc_ln19_10_fu_755_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_6_fu_487_p2 = ((trunc_ln19_11_fu_479_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln24_7_fu_643_p2 = ((trunc_ln19_12_fu_635_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln28_1_fu_564_p2 = ((j_reg_901 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln28_2_fu_577_p2 = ((j_reg_901 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_541_p2 = ((j_reg_901 == 2'd2) ? 1'b1 : 1'b0);

assign im_1_address0 = im_1_addr_4_reg_964;

assign im_1_address1 = im_1_addr_reg_944;

assign im_1_d0 = b_im_out_fu_859_p2;

assign im_1_d1 = a_im_out_fu_851_p2;

assign im_address0 = im_addr_4_reg_959;

assign im_address1 = im_addr_reg_939;

assign im_d0 = b_im_out_fu_859_p2;

assign im_d1 = a_im_out_fu_851_p2;

assign j_fu_280_p1 = ap_sig_allocacmp_bfly[1:0];

assign lshr_ln1_fu_302_p4 = {{{tmp_3_fu_284_p4}, {1'd0}}, {tmp_fu_294_p3}};

assign or_ln141_fu_320_p2 = (lshr_ln1_fu_302_p4 | 9'd2);

assign or_ln21_4_fu_378_p2 = (icmp_ln21_13_fu_364_p2 | icmp_ln21_12_fu_358_p2);

assign or_ln21_5_fu_392_p2 = (icmp_ln21_11_fu_352_p2 | icmp_ln21_10_fu_346_p2);

assign or_ln21_6_fu_406_p2 = (icmp_ln21_9_fu_340_p2 | icmp_ln21_8_fu_334_p2);

assign or_ln21_7_fu_420_p2 = (or_ln21_5_fu_392_p2 | or_ln21_4_fu_378_p2);

assign or_ln28_fu_590_p2 = (icmp_ln28_fu_541_p2 | icmp_ln28_1_fu_564_p2);

assign re_1_d0 = b_re_out_fu_831_p2;

assign re_1_d1 = a_re_out_fu_823_p2;

assign re_d0 = b_re_out_fu_831_p2;

assign re_d1 = a_re_out_fu_823_p2;

assign rounded_10_fu_773_p2 = (v_15_fu_750_p3 + zext_ln24_5_fu_769_p1);

assign rounded_11_fu_497_p2 = (v_16_fu_472_p3 + zext_ln24_6_fu_493_p1);

assign rounded_12_fu_723_p2 = (v_17_reg_1023 + zext_ln24_7_fu_720_p1);

assign rounded_fu_685_p2 = (v_12_fu_662_p3 + zext_ln24_4_fu_681_p1);

assign select_ln21_15_fu_384_p3 = ((icmp_ln21_11_fu_352_p2[0:0] == 1'b1) ? 3'd3 : 3'd4);

assign select_ln21_16_fu_398_p3 = ((icmp_ln21_9_fu_340_p2[0:0] == 1'b1) ? 3'd5 : 3'd6);

assign select_ln21_17_fu_412_p3 = ((or_ln21_4_fu_378_p2[0:0] == 1'b1) ? select_ln21_fu_370_p3 : select_ln21_15_fu_384_p3);

assign select_ln21_18_fu_426_p3 = ((or_ln21_6_fu_406_p2[0:0] == 1'b1) ? select_ln21_16_fu_398_p3 : 3'd7);

assign select_ln21_19_fu_434_p3 = ((or_ln21_7_fu_420_p2[0:0] == 1'b1) ? select_ln21_17_fu_412_p3 : select_ln21_18_fu_426_p3);

assign select_ln21_fu_370_p3 = ((icmp_ln21_13_fu_364_p2[0:0] == 1'b1) ? 3'd1 : 3'd2);

assign select_ln25_fu_454_p3 = ((trunc_ln132_fu_276_p1[0:0] == 1'b1) ? 64'd128 : 64'd0);

assign select_ln28_fu_546_p3 = ((icmp_ln28_fu_541_p2[0:0] == 1'b1) ? TW_SIN_LUT_q0 : TW_COS_LUT_q0);

assign sext_ln159_3_fu_614_p1 = b_re_15_fu_526_p3;

assign sext_ln159_fu_618_p1 = w_re_18_fu_582_p3;

assign sext_ln160_2_fu_808_p1 = b_im_15_reg_1054;

assign sext_ln160_3_fu_654_p1 = w_im_reg_996;

assign sext_ln175_fu_820_p1 = $signed(a_re_15_reg_1049);

assign sext_ln176_fu_848_p1 = $signed(a_im_15_reg_1059);

assign tmp_3_fu_284_p4 = {{ap_sig_allocacmp_bfly[8:2]}};

assign tmp_fu_294_p3 = ap_sig_allocacmp_bfly[32'd1];

assign trunc_ln132_fu_276_p1 = ap_sig_allocacmp_bfly[0:0];

assign trunc_ln19_10_fu_755_p1 = v_15_fu_750_p3[1:0];

assign trunc_ln19_11_fu_479_p1 = v_16_fu_472_p3[1:0];

assign trunc_ln19_12_fu_635_p1 = v_17_fu_628_p3[1:0];

assign trunc_ln19_fu_667_p1 = v_12_fu_662_p3[1:0];

assign v_12_fu_662_p3 = ((trunc_ln132_reg_893[0:0] == 1'b1) ? re_1_load_reg_984 : re_load_reg_979);

assign v_15_fu_750_p3 = ((trunc_ln132_reg_893[0:0] == 1'b1) ? im_1_load_reg_1018 : im_load_reg_1013);

assign v_16_fu_472_p3 = ((trunc_ln132_reg_893[0:0] == 1'b1) ? re_1_q0 : re_q0);

assign v_17_fu_628_p3 = ((trunc_ln132_reg_893[0:0] == 1'b1) ? im_1_q0 : im_q0);

assign w_im_fu_608_p2 = (zext_ln151_1_fu_604_p1 ^ 16'd65535);

assign w_re_16_fu_558_p2 = (zext_ln28_fu_554_p1 ^ 16'd65535);

assign w_re_17_fu_569_p3 = ((icmp_ln28_1_fu_564_p2[0:0] == 1'b1) ? zext_ln26_fu_537_p1 : w_re_16_fu_558_p2);

assign w_re_18_fu_582_p3 = ((icmp_ln28_2_fu_577_p2[0:0] == 1'b1) ? zext_ln151_fu_533_p1 : w_re_17_fu_569_p3);

assign w_re_19_fu_596_p3 = ((or_ln28_fu_590_p2[0:0] == 1'b1) ? TW_COS_LUT_q0 : TW_SIN_LUT_q0);

assign wb_im_s_fu_839_p4 = {{grp_fu_875_p3[31:15]}};

assign wb_re_s_fu_811_p4 = {{grp_fu_867_p3[31:15]}};

assign zext_ln140_fu_312_p1 = lshr_ln1_fu_302_p4;

assign zext_ln141_fu_326_p1 = or_ln141_fu_320_p2;

assign zext_ln151_1_fu_604_p1 = w_re_19_fu_596_p3;

assign zext_ln151_fu_533_p1 = TW_COS_LUT_q0;

assign zext_ln21_fu_469_p1 = select_ln21_19_reg_918;

assign zext_ln24_4_fu_681_p1 = icmp_ln24_4_fu_675_p2;

assign zext_ln24_5_fu_769_p1 = icmp_ln24_5_fu_763_p2;

assign zext_ln24_6_fu_493_p1 = icmp_ln24_6_fu_487_p2;

assign zext_ln24_7_fu_720_p1 = icmp_ln24_7_reg_1033;

assign zext_ln26_fu_537_p1 = TW_SIN_LUT_q0;

assign zext_ln28_fu_554_p1 = select_ln28_fu_546_p3;

always @ (posedge ap_clk) begin
    re_addr_reg_908[1] <= 1'b0;
    re_1_addr_reg_913[1] <= 1'b0;
    im_addr_reg_939[1] <= 1'b0;
    im_1_addr_reg_944[1] <= 1'b0;
    re_addr_4_reg_949[1] <= 1'b1;
    re_1_addr_4_reg_954[1] <= 1'b1;
    im_addr_4_reg_959[1] <= 1'b1;
    im_1_addr_4_reg_964[1] <= 1'b1;
    zext_ln21_reg_989[15:3] <= 13'b0000000000000;
end

endmodule //fft_serial_fft_serial_Pipeline_bfly_loop3
